### ISSUE TITLE
Restructure new "FAQ" content

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev-lang-python#252]
We've added a new FAQ page to the docs, but I think that we can organize it slightly better. Logically, if one is having an issue, clicking on "FAQ" probably isn't going to be their first thought. I think it would make sense to rename that page to "Troubleshooting" or similar for now.

cc @ndward

**Comment by ddemidov** [comment]
It looks like we could move the whole section of the README after [User resources](https://github.com/rhempel/ev3dev-lang-python#user-resources) into the FAQ page.

**Comment by WasabiFan** [comment]
Hmmm, good point. That would clean up our README as well.

**Comment by dwalton76** [comment]
@WasabiFan want to take this one?

**Comment by WasabiFan** [comment]
I don't think I have the cycles to commit to this right now; Next week I should be more free and I'll try to look through all the issues on this repo then.

**Comment by dwalton76** [comment]
cool

**Comment by dwalton76** [comment]
The docs have changed a lot in two years...is there still work to do on this one?

**Comment by WasabiFan** [comment]
The FAQ page still exists and has the same problem.

**Comment by bpmerkel** [comment]
Let me take this one gentlemen. Branching now...
