### ISSUE TITLE
led blink code regressed again, we should maybe offer a thread based led animator

### ISSUE THREAD

**Issue by ensonic** [ev3dev/ev3dev-lang-python#324]
- **ev3dev version:** 4.4.47-19-ev3dev-ev3
- **ev3dev-lang-python version:** 0.8.1

Take a look at https://github.com/OpenRoberta/robertalab-ev3dev/commit/a95051b7b10219f8bd3c0f23578b17b1fbf1dec5, before I was using the trigger feature and e.g. when using this with color=orange for left+right, the blinking was completely out of sync, one got the left led first turning green and maybe orange and then red and so on. With a blink thread we can do much more.

**Comment by WasabiFan** [comment]
How's the performance of that blink code on the EV3? Is the blink consistent?

**Comment by dwalton76** [comment]
@ensonic I like the idea of a thread to control led blinking...did you get this going?

**Comment by dwalton76** [comment]
If we had a thread class to control LED(s) would that kill the need to tackle #262 ?

**Comment by ensonic** [comment]
Yes it works fine for me. I had a few courses by now and no complaints. And yes it solved the problem in #262 as well.

**Comment by dwalton76** [comment]
@ensonic would you be willing to port it to here?

**Comment by ensonic** [comment]
I'll take a look.

**Comment by bonmotwang** [comment]
I am still getting the error
Traceback (most recent call last):
  File "led_test.py", line 21, in <module>
    Leds.set(Leds.LEFT, brightness_pct=0.5, trigger='timer')
  File "/usr/lib/python3/dist-packages/ev3dev/ev3.py", line 90, in set
    setattr(led, k, kwargs[k])
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 2516, in trigger
    raise Exception('"{}" attribute has wrong permissions'.format(attr))
Exception: "delay_on" attribute has wrong permissions

My code:
Leds.all_off()

Leds.set(Leds.LEFT, brightness_pct=0.5, trigger='timer')
Leds.set(Leds.LEFT, delay_on=3000, delay_off=500)
Leds.set_color(Leds.LEFT, Leds.RED)

**Comment by dlech** [comment]
Try putting a delay between setting the trigger to 'timer' and setting the delay_* attributes. Udev needs time to properly set the permissions of those attributes.

```python
import time

Leds.all_off()

Leds.set(Leds.LEFT, brightness_pct=0.5, trigger='timer')
time.sleep(0.5)
Leds.set(Leds.LEFT, delay_on=3000, delay_off=500)
Leds.set_color(Leds.LEFT, Leds.RED)
```
