### ISSUE TITLE
video call to hammer out some things?

### ISSUE THREAD

**Issue by dwalton76** [ev3dev/ev3dev-lang-python#351]
Would folks be interested in having a video call sometime to discuss:
- moving the `demo` code to its own repo #338 
- Separation of driver interface from high level library #348 
- branch naming #339 
- equivalent APIs for EV3-G motor and sensor blocks
- micropython vs. cpython...how exactly do we want to handle supporting both

It feels like there is enough to discuss that it would be far faster to do a call than it would to hash everything out via comments on issues/PRs.

What timezone is everyone in?  I am on the US east coast.

**Comment by ddemidov** [comment]
Why not, it sounds fun. I am on Europe/Moscow time (UTC+3).

**Comment by WasabiFan** [comment]
Yeah, I'm up for it. I can't say I have a particularly good track record with these things (slept through the last one :laughing:) but I think it's a good idea. I'm in PST (UTC-7 or -8, depending on DST). The 11-hour offset makes things interesting!

**Comment by dwalton76** [comment]
I could do tomorrow (sat sept 9th) at 4:00pm UTC? If not maybe we aim for a weekday next week.

**Comment by WasabiFan** [comment]
That'll be a bit tight for me... can we shoot for sometime next week, excluding Monday? 9:00 my time (4:00PM UTC) is fine though.

**Comment by dwalton76** [comment]
Yep I can do Tues, Wed or Thursday at that time.

**Comment by ddemidov** [comment]
4pm UTC works for me on any week day.

**Comment by rhempel** [comment]
I am unable to join - but support all of the work you are doing together to make this happen. Please make sure you properly credit yourselves with this work - just because the repo is on my GitHub area and I'm not actively contributing😏

**Comment by ensonic** [comment]
I'd join too (CEST here). 4:00PM UTC would be okay.

**Comment by dwalton76** [comment]
Cool...if you guys/gals can send me your email addresses I'll setup a call for Tuesday at 4pm UTC

**Comment by ddemidov** [comment]
dennis.demidov@gmail.com

**Comment by WasabiFan** [comment]
kaelin_laundry at hotmail.com

**Comment by ensonic** [comment]
st.kost at gmail.com

**Comment by dlech** [comment]
david at lechnology dot com, or if you are doing a google hangout extraspecialdave at gmail dot com

**Comment by WasabiFan** [comment]
Here are the notes from the meeting:

---

- Branch naming
	- Banch off current master for ev3dev-jessie
	- Continue on master + develop for Stretch
	- Versioning: jessie releases after moving onto stretch will require suffix
- Autogen
	- Could remove autogen only on Jessie and maintain manually
	- Stretch would become primary supported platform for autogen spec
- Performance: sysfs vs. character device (external)
- Separating demos into individual repo
	- Would enable downloading all demos as ZIPball
	- Ship demos as Debian package
		- Preinstall
		- Installs demos to `/home/robot/demo`?
- High-level API
	- Each block in EV3-G would have an equivalent class in Python (e.g., motor block -> motor object)
	- Keep existing internal API available, but document friendly methods primarily
	- Further investigation:
		- Build wiki page with mapping of current API to EV3-G blocks
		- Build friendly functions so that their argument names aren't dependent on internal sysfs names
- Micropython vs cpython
	- Micropython-first, but we support cpython
	- Further investigation:
		- Replacement for display and sound APIs
- Pre-compile module?
- Future video calls?

---

I'm going to go ahead and update various issues that we discussed as well as open new ones for a few of the above points.
