### ISSUE TITLE
EV3-G API: buttons

### ISSUE THREAD

**Issue by dwalton76** [ev3dev/ev3dev-lang-python#354]
![buttons-01](https://user-images.githubusercontent.com/468309/30606495-e1333fa4-9d3f-11e7-8ac4-10fbb8e1fca5.png)

**Comment by dwalton76** [comment]
What we have right now for `class Button` in `ev3dev/ev3.py` looks pretty good to me.  Is there anything to be done for this one?

PS
How does one use the on_left(), etc methods?

**Comment by dwalton76** [comment]
@WasabiFan @dlech can you spot anything that we are missing to be EV3-G 1:1?  If not lets close this one.

**Comment by dlech** [comment]
How do you wait for a button to be pressed/released/bumped?

**Comment by dwalton76** [comment]
We don't have a way to do that but from looking at the EV3-G block it doesn't either?  It sounds useful though (and we have it for TouchSensor), we can add it.

**Comment by dlech** [comment]
And what about bumped?

**Comment by dwalton76** [comment]
I'll add pressed, released and bumped

**Comment by dlech** [comment]
Here is a more fleshed out view of the EV3-G buttons blocks:

![image](https://user-images.githubusercontent.com/963645/30870787-6b2cc56c-a2aa-11e7-963c-25fb31fd971d.png)

![image](https://user-images.githubusercontent.com/963645/30870801-76beeb9e-a2aa-11e7-8f8f-5b5c8d4b0a0e.png)

![image](https://user-images.githubusercontent.com/963645/30870836-91f28466-a2aa-11e7-940a-8dd17e548fbd.png)

![image](https://user-images.githubusercontent.com/963645/30870853-a0fae494-a2aa-11e7-9008-c8436b413065.png)

![image](https://user-images.githubusercontent.com/963645/30870877-b1a907c6-a2aa-11e7-99e7-2314e0506326.png)

**Comment by dwalton76** [comment]
@dlech for EVB what should its _buttons be now?  This is what we have for EV3
```
    _buttons = { 
            'up': {'name': '/dev/input/by-path/platform-gpio_keys-event', 'value': 103},
            'down': {'name': '/dev/input/by-path/platform-gpio_keys-event', 'value': 108},
            'left': {'name': '/dev/input/by-path/platform-gpio_keys-event', 'value': 105},
            'right': {'name': '/dev/input/by-path/platform-gpio_keys-event', 'value': 106},
            'enter': {'name': '/dev/input/by-path/platform-gpio_keys-event', 'value': 28},
            'backspace': {'name': '/dev/input/by-path/platform-gpio_keys-event', 'value': 14},
        }
```

EVB barfs on
```
robot@evb[bin]# ./buttons.py 
Traceback (most recent call last):
  File "./buttons.py", line 19, in <module>
    btn = Button()
  File "/usr/local/lib/python3.5/dist-packages/python_ev3dev-0.8.0.post69-py3.5.egg/ev3dev/core.py", line 3178, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/dev/input/by-path/platform-gpio_keys-event'
robot@evb[bin]# 
```


Am running this on my EVB:
```
robot@evb[ev3dev-lang-python]# ev3dev-sysinfo 
Image file:         ev3dev-stretch-bone-generic-2017-09-01
Kernel version:     4.9.41-ev3dev-1.4.0-bb.org
/usr/bin/ev3dev-sysinfo: line 68: warning: command substitution: ignored null byte in input
Board:              TI AM335x BeagleBone Black
Revision:           000c
Brickman:           0.10.0
ev3devKit:          0.5.2
robot@evb[ev3dev-lang-python]# 
```

**Comment by dwalton76** [comment]
you know what, I probably need to update my EVB, ignore this for a bit

**Comment by dwalton76** [comment]
nope same issue
```
robot@evb[bin]# ev3dev-sysinfo 
Image file:         ev3dev-stretch-bone-generic-2017-09-01
Kernel version:     4.9.50-ev3dev-1.5.1-bb.org
Brickman:           0.10.0
ev3devKit:          0.5.2
Board:              board0
BOARD_INFO_HW_REV=000C
BOARD_INFO_MODEL=A335BNLT
BOARD_INFO_SERIAL_NUM=4214BBBK2552
BOARD_INFO_TYPE=main
Board:              board1
BOARD_INFO_MODEL=FatcatLab EVB
BOARD_INFO_TYPE=aux
robot@evb[bin]# 
```

**Comment by dlech** [comment]
```
robot@ev3dev-bbg:~$ ls /dev/input/by-path/
platform-44e0b000.i2c-platform-tps65217-pwrbutton-event  platform-evb-sound-event
platform-evb-buttons-event
```

Looks like `/dev/input/by-path/platform-evb-buttons-event` will work.

**Comment by dwalton76** [comment]
Will the kernel set `select.POLLPRI` when `/dev/input/by-path/platform-evb-buttons-event` is modified?  It doesn't seem to be...the `_wait()` that I wrote is almost identical to the one used by TouchSensor but I never get an event that the file changed.

**Comment by dlech** [comment]
Try `select.POLLIN`. It is rare to use POLLPRI.

**Comment by dwalton76** [comment]
ok it turns out polling for TouchSensor isn't working, I just thought it was because POLLIN never blocks.  What I am seeing...

## Motor wait()
- POLLPRI blocks until the file is touched, perfect
- POLLIN does not block

## TouchSensor _wait()
- POLLPRI does not block
- POLLIN does not block

## buttons _wait()
- POLLPRI blocks but doesn't fire when the file is touched
- POLLIN does not block

**Comment by dlech** [comment]
Which kernel version? POLLIN is working for me on `4.9.49-ev3dev-1.5.1-ev3` on motors and buttons (haven't tried sensors).

**Comment by dlech** [comment]
Actually, I take that back about buttons. I'm just reading directly on a background thread without polling. `read` blocks until there is data available.

**Comment by dwalton76** [comment]
```
robot@evb[ev3dev-lang-python]# ev3dev-sysinfo 
Image file:         ev3dev-stretch-bone-generic-2017-09-01
Kernel version:     4.9.50-ev3dev-1.5.1-bb.org
Brickman:           0.10.0
ev3devKit:          0.5.2
Board:              board0
BOARD_INFO_MODEL=FatcatLab EVB
BOARD_INFO_TYPE=aux
Board:              board1
BOARD_INFO_HW_REV=000C
BOARD_INFO_MODEL=A335BNLT
BOARD_INFO_SERIAL_NUM=4214BBBK2552
BOARD_INFO_TYPE=main
robot@evb[ev3dev-lang-python]# 
```

**Comment by dwalton76** [comment]
@dlech want me to file an issue for POLLIN support on motors, sensors and buttons files?  Either that or POLLPRI for all three.

**Comment by dlech** [comment]
POLLIN works for me, so I can't really help much unless you have some code to reproduce the problem. I suspect that there is a problem with your code rather than a problem with ev3dev.

**Comment by dwalton76** [comment]
I haven't used poll much, I just followed what was done for motors.  Here is what I did for TouchSensor:
https://github.com/rhempel/ev3dev-lang-python/blob/develop/ev3dev/core.py#L2275-L2285

and here is the motors equivalent
https://github.com/rhempel/ev3dev-lang-python/blob/develop/ev3dev/core.py#L920-L940

**Comment by dlech** [comment]
I don't see that notification for sensors was ever implemented, so I don't expect that to work.

https://github.com/ev3dev/ev3dev/issues/498

**Comment by dlech** [comment]
After a bit more research, it seems that poll with sysfs only support POLLPRI, so what you observed with the motor state sysfs attribute is the expected behavior.

**Comment by dlech** [comment]
Another thing is that if you have never read a file, poll won't block. So you have to read at least once before calling poll if you want to see it block.

**Comment by dwalton76** [comment]
Ack will fix that for motors, that is the only place we are using POLLPRI
