### ISSUE TITLE
EV3-G API: color sensor

### ISSUE THREAD

**Issue by dwalton76** [ev3dev/ev3dev-lang-python#355]
![color-sensor-01](https://user-images.githubusercontent.com/468309/30606514-f08eb9d8-9d3f-11e7-85d4-d53b7ca1546d.png)

**Comment by dwalton76** [comment]
For the two calibrate methods per
http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-stretch/sensor_data.html

_[28] | This mode is not usable. When in COL-CAL mode, the color sensor does not respond to the keep-alive sent from the EV3 brick. As a result, the sensor will time out and reset._

so will skip those unless the quote above is no longer accurate.


I'm not sure what all we should add here...`wait_for_color(...)` might be handy.  What methods would make line followers easier to code?

**Comment by dwalton76** [comment]
Do you guys see the RGB values that come from the sensor as very very dark?  I can point mine at the white side of a rubiks cube and it comes back with numbers like (34, 58, 46) on 0-255 scale.  That is basically dark green:
https://www.w3schools.com/colors/colors_converter.asp

I'm wondering if this thing is broken.

**Comment by dwalton76** [comment]
Prior to this commit `ColorSensor.rgb()` took the raw RGB values and scaled them to 0-255 based on a 0-1020 scale (since that is the official range of the values returned by the sensor).  The color sensor never returns anything close to 1020 though so the end result was that we got very dark RGB values out of `rgb()`.  A typical MINDCUBER scan of a rubiks cube would look like this:

![color-sensor-before](https://user-images.githubusercontent.com/468309/31440882-67b59556-ae5f-11e7-8226-2a0d15e76932.png)

Now we have a `calibrate_white()` function the user can call (to be called when the color sensor is looking at something white) to figure out what are the maximum RGB values we can expect to see. `ColorSensor.rgb()` will then scale the results to 0-255 based on those max values.  The result is that you get much brighter/accurate data:

![color-sensor-after](https://user-images.githubusercontent.com/468309/31440982-c743af9e-ae5f-11e7-9490-1932c4990eb5.png)

Note that the two pics above are of different rubiks cubes but you get the idea, the colors in the second one are much more accurate than the first.

**Comment by dlech** [comment]
FYI, converting to HSV or some other colorspace would be even more accurate.

**Comment by dwalton76** [comment]
RGB is very handy for printing in web pages for debugging color issues but sucks for computing color distances of one color vs. another.  HSV I never had much luck with for color comparison.  I found that Lab color space works best for comparing colors, you take the euclidean distance between the two colors and that works really well.  This is what I use for all of the color resolving that has to happen in cranecuber.

I have a function that converts RGB to Lab without importing any additional modules.  I'll add a `lab()` method to the ColorSensor.

**Comment by dwalton76** [comment]
PS
This is a good article on python and color sorting
http://www.alanzucconi.com/2015/09/30/colour-sorting/
