### ISSUE TITLE
EV3-G API: display

### ISSUE THREAD

**Issue by dwalton76** [ev3dev/ev3dev-lang-python#356]
![display-01](https://user-images.githubusercontent.com/468309/30606535-02bac070-9d40-11e7-8437-94807f035fcf.png)

**Comment by dwalton76** [comment]
Should we rename `display.py -> screen.py` since the class is `Screen` or do we want leave to the filename alone and change our class from `Screen` to `Display`?

**Comment by dwalton76** [comment]
I am going to guess that we cannot include the screen `.bmp` files here due to copyright reasons?
https://sites.google.com/site/ev3basic/ev3-basic-programming/using-buttons-the-screen-and-the-leds/lego-ev3-standard-bitmaps

**Comment by ddemidov** [comment]
> Should we rename

I vote to stick with `Screen` as class name and rename the file.

**Comment by WasabiFan** [comment]
https://github.com/ev3dev/ev3dev/issues/970

> Should we rename...

When I say "screen" a few times in my head it loses all meaning... I feel like "display" is a bit more clear. I don't have a strong opinion though.

**Comment by ensonic** [comment]
For the assents, we could start a collection of free replacement images. I don't think we can get LEGO to license them to us in a useful way, since content if often done by sub contracting companies.
For the bars, gauges and eyes, I'd love to have classes where one can properly animate them though.

**Comment by dlech** [comment]
See https://github.com/ev3dev/ev3dev/issues/970

**Comment by dwalton76** [comment]
Let's look to see what EV3-G calls this block (screen or display) and follow that...I'll take a look this evening.

**Comment by dwalton76** [comment]
ok EV3-G calls their block `Display` to lets stick with display.py but change the name of our class from Screen to Display so we are 1:1

**Comment by dwalton76** [comment]
Some references on display

- http://ev3lessons.com/translations/en-us/beginner/Display.pdf
- http://www.mainerobotics.org/uploads/8/3/4/4/8344007/using_the_ev3_display_block.pdf
