### ISSUE TITLE
Ship library as pre-compiled module

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev-lang-python#359]
This will speed up loading times for the module (although it won't help with execution speed).

**Comment by dlech** [comment]
You already are.

    ls /usr/lib/python3/dist-packages/ev3dev/__pycache__/

**Comment by WasabiFan** [comment]
No, we are not; we ship source packages which are interpreted, compiled and cached at the client's discretion. This issue is a direct result of the suggestion you made in the call, where you said that we should be shipping separate binary packages with the module pre-compiled.

**Comment by WasabiFan** [comment]
If this is a misinterpretation of your request, please elaborate on the suggestion.

**Comment by dlech** [comment]
Debian compiles all modules as part of the post-build step when installing any Debian python package, including this one. Perhaps you are referring to my comment about doing the same for MicroPython? Debian doesn't know anything about MicroPython, this won't happen automatically in that case.

**Comment by WasabiFan** [comment]
@dlech yes. This issue is about _us_ shipping packages with the module precompiled, with the specific goal of optimizing for Micropython. I believe that is what you were referring to during our call.

**Comment by dlech** [comment]
So really, the issue at hand is to create a new binary package that contains the micropython version of ev3dev-lang-python.

**Comment by WasabiFan** [comment]
Yes, that is correct.

**Comment by dwalton76** [comment]
What did we ever decide on micropython?

**Comment by dlech** [comment]
I quit working on MicroPython because I was getting so much pushback.

**Comment by WasabiFan** [comment]
The decision was to support it with this library -- it's just a matter of configuring the packaging; as of last time I tested it, the core modules were all fully-compatible.

**Comment by dwalton76** [comment]
Now that we support micropython does that kill the need to pre-compile modules? Also wouldn’t the speed boost from a pre-compiled module only be a benefit the first time you load it?

**Comment by WasabiFan** [comment]
I think the original discussion here was around Micropython, the packaging for which is covered by https://github.com/ev3dev/ev3dev-lang-python/issues/521. I'm calling this a dupe.
