### ISSUE TITLE
EV3-G API: touch sensor

### ISSUE THREAD

**Issue by dwalton76** [ev3dev/ev3dev-lang-python#361]
Need to get screenshots of the touch sensor blocks

**Comment by dlech** [comment]
![image](https://user-images.githubusercontent.com/963645/30651706-21a04a58-9dec-11e7-8b54-ce355ca002f0.png)

**Comment by dwalton76** [comment]
@dlech wrong image :)

**Comment by dlech** [comment]
Buttons are a touch sensors of sorts :wink: 

Here is the correct screenshot:

![image](https://user-images.githubusercontent.com/963645/30656253-19319108-9df9-11e7-98a2-dad21965a7a4.png)

**Comment by laurensvalk** [comment]
---> [This](https://github.com/ev3dev/lms2012-compat/issues/51) may be relevant when looking to replicate EV3-G, including or excluding original bugs.

If that post doesn't make sense, ask away :)

**Comment by dwalton76** [comment]
@dlech does ev3dev support the `bumped` value?  I've been `cat value0` over and over while touching the sensor but I only ever see 0 or 1

**Comment by WasabiFan** [comment]
@dwalton76 ev3dev's built-in touch sensor driver doesn't support `bumped`; it only reports whether or not the button is pressed (which I think is the correct behavior). If we want to support that logic, we'll have to implement it in Python. I'd say we should just omit it for now.

**Comment by dwalton76** [comment]
works for me
