### ISSUE TITLE
EV3-G API: Gyro sensor

### ISSUE THREAD

**Issue by dwalton76** [ev3dev/ev3dev-lang-python#362]
Need to get screenshots of the gyro sensor blocks

**Comment by dlech** [comment]
![image](https://user-images.githubusercontent.com/963645/30653386-92543b84-9df0-11e7-9a34-b474a7efc728.png)

**Comment by dlech** [comment]
Implementation note on Reset block:

This block puts the sensor into GYRO-ANGLE mode, plus sends a command to the sensor (I'll have to look it up later). Sending the command would have to be done with the `direct` attribute in ev3dev.

UPDATE: The reset command writes a single byte, `17` to the sensor.

**Comment by dlech** [comment]
Newer versions of these sensors also have an additional second axis accessible via the `TILT-ANGLE` and `TILT-RATE` modes that is not usable using the official EV3-G blocks. 

https://www.youtube.com/watch?v=KjlT0BUJr-w
