### ISSUE TITLE
EV3-G API: Infared sensor

### ISSUE THREAD

**Issue by dwalton76** [ev3dev/ev3dev-lang-python#363]
Need to get screenshots of the infared sensor blocks

**Comment by dlech** [comment]
![image](https://user-images.githubusercontent.com/963645/30653695-613bef82-9df1-11e7-8359-ca552135a597.png)

**Comment by dwalton76** [comment]
```
    def reflected_light_intensity(self):
        """
        Reflected light intensity as a percentage. Light on sensor is red.
        """

        if self.auto_mode:
            self.mode = self.MODE_COL_REFLECT

        return self.value(0)
```

Is there a scenario where auto_mode would be False?  Doesn't seem like anything would work if it were unless the user also did `self.mode = self.MODE_COL_REFLECT` so you have the same behavior in the end.  I'm scratching my head a bit on why we have this.

**Comment by dwalton76** [comment]
TouchSensor class also has the mysterious self.auto_mode

**Comment by ddemidov** [comment]
Every sensor has `auto_mode` field. When it is on, the appropriate mode will be selected before reading a value (e.g. when we read RGB from color sensor, it's mode will be set to 'RAW'). When it is off, user have to make sure sensor is in correct mode. This makes sense when user needs as much performance as possible.

**Comment by dwalton76** [comment]
The mode has to be set correctly anyway though...I'm missing how it increases performance by having the user set the mode vs us setting it for them?  We could just cache what the current mode is and only update that attribute when it needs to be in a different mode....then we could chop the auto_mode variable.

**Comment by ddemidov** [comment]
User can set the mode once and read the value many times. Caching current mode could work as long as we assume no one will change the mode from under our feet (e.g. another thread or process).
