### ISSUE TITLE
not working on Debian Stretch

### ISSUE THREAD

**Issue by hashworks** [ev3dev/ev3dev-lang-python#384]
Hi, how is the progress of `ev3dev-lang-python` for Debian Stretch?

I'm using images that descend from the [ev3dev-stretch-ev3-generic](https://hub.docker.com/r/ev3dev/ev3dev-stretch-ev3-generic/tags/) docker builds on ev3 bricks.

When starting robertlab I get a `File not found` error since it tries to use `/dev/input/by-path/platform-gpio-keys.0-event`, which apperently got replaced by `/dev/input/by-path/platform-gpio_keys-event`.
Since both linked to `/dev/input/event0` I can simply add that file, but then I get another error:

```
INFO:roberta:--- starting ---
INFO:roberta.lab:python path: /usr/bin:/usr/lib/python35.zip:/usr/lib/python3.5:/usr/lib/python3.5/plat-arm-linux-gnueabi:/usr/lib/python3.5/lib-dynload:/usr/local/lib/python3.5/dist-packages:/usr/lib/python3/dist-packages

INFO:roberta.lab:status changed: disconnected
Traceback (most recent call last):
  File "/usr/bin/openrobertalab", line 41, in <module>
    main()
  File "/usr/bin/openrobertalab", line 36, in main
    service = Service('/org/openroberta/Lab1')
  File "/usr/lib/python3/dist-packages/roberta/lab.py", line 88, in __init__
    self.hal.clearDisplay()
  File "/usr/lib/python3/dist-packages/roberta/ev3.py", line 179, in clearDisplay
    self.lcd.update()
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 3135, in update
    self.mmap[:] = self._img.tobytes("raw", "1;IR")
IndexError: mmap slice assignment is wrong size
INFO:roberta:--- done ---
```

I opened an [issue on the robertalab repo](https://github.com/OpenRoberta/robertalab-ev3dev/issues/49), but @ensonic told me this needs to be updated first before he can do anything.

**Comment by ddemidov** [comment]
Related to #381

**Comment by hashworks** [comment]
Ah, sorry. Completly missed that one

**Comment by WasabiFan** [comment]
Yeah, we're currently working on an initial Stretch release. I'm hoping to get that out for testing within a week or two at most. Until then, you'll either have to download a work-in-progress version of the library for use temporarily or use ev3dev-jessie.

**Comment by dwalton76** [comment]
See PR #400 (assigning to Denis)

**Comment by dwalton76** [comment]
Any objections to closing this one? We have pretty good stretch support now.

**Comment by WasabiFan** [comment]
Yeah, I think we're good to close this.
