### ISSUE TITLE
MoveTank on_for_rotations method problem

### ISSUE THREAD

**Issue by gregcowell** [ev3dev/ev3dev-lang-python#393]
- **ev3dev version:** 4.4.87-22-ev3dev-ev3
- **ev3dev-lang-python version:** develop branch

If I run the code below, the wheels/tracks do not rotate in opposite directions as expected:
```
tank = ev3.MoveTank('outB', 'outC')
tank.on_for_rotations(left_speed_pct=5, right_speed_pct=-5, rotations=1.35)
```
This also affects the MoveSteering on_for_rotations method since it uses the MoveTank equivalent. I will submit a proposed fix as a pull request.

**Comment by dlech** [comment]
I notice that you are using kernel 4.4.87-22-ev3dev-ev3, which is ev3dev-jessie. The develop branch of ev3dev-lang-python is for ev3dev-stretch (the next generation ev3dev release). Did you intent for this problem to be fixed in ev3dev-jessie as well?

**Comment by WasabiFan** [comment]
I don't think the steering classes exist in the Jessie branch... Not sure though.
