### ISSUE TITLE
Move this repo to https://github.com/ev3dev/

### ISSUE THREAD

**Issue by dwalton76** [ev3dev/ev3dev-lang-python#404]
We should move it there to be with all of the other official repos for ev3dev

**Comment by dlech** [comment]
@rhempel will have to transfer ownership of the repository, otherwise the only thing I can do is start a new repository from scratch.

**Comment by jabrena** [comment]
In my humble opinion,

I think that it is necessary to differentiate the Linux Distro from the Application usage, the programming language ecosystem. Maybe, `ev3dev-lang-python` should have his own organization but not merge on `ev3dev`.

Cheers

Juan Antonio

**Comment by rhempel** [comment]
Ownership transferred to ev3dev - thanks for your continued support - it's in good hands :-)
