### ISSUE TITLE
How to add new users to this repo?

### ISSUE THREAD

**Issue by dwalton76** [ev3dev/ev3dev-lang-python#405]
I want to assign issue #404 to @dlech but when I click on `Assignees` it only lists myself, ralph, wasabi and denis.  How do we add users to the repo so that we can assign them issues, etc?  I'm sure @rhempel has permission to add users but does anyone else?

I have the same issue over in https://github.com/ev3dev/ev3dev-lang-python-demo I want to assign https://github.com/ev3dev/ev3dev-lang-python-demo/issues/2 to @gregcowell

**Comment by dlech** [comment]
I'll see what I can do about the demo repo.

**Comment by WasabiFan** [comment]
I don't have permission either. I think repos owned by a single user might not allow multiple admins.

**Comment by rhempel** [comment]
If you have users that you trust I will add them.

**Comment by rhempel** [comment]
I am ok moving this to the formal ev3dev organization - @dlech let me know what steps to take and I'll do it tonight

**Comment by dlech** [comment]
Under the settings for this repository, there is an option to "transfer" the repository. Just use that to transfer it to "ev3dev" and GitHub will transfer everything and setup redirects for all of the links.

**Comment by rhempel** [comment]
Transferred ownership of this repo to ev3dev organization.
