### ISSUE TITLE
add ev3.Leds.BLACK to the docs

### ISSUE THREAD

**Issue by fisherds** [ev3dev/ev3dev-lang-python#409]
I noticed in the docs that the LED color BLACK was missing.
http://python-ev3dev.readthedocs.io/en/stable/other.html#leds

Also right now the docs aren't displaying on latest:
http://python-ev3dev.readthedocs.io/en/latest/other.html#leds

First link (to stable) is fine, second link (to latest) fails for me.

**Comment by WasabiFan** [comment]
It looks like that documentation include statement is missing from https://github.com/rhempel/ev3dev-lang-python/blob/9b900bbe8c0746485f105742cb74989301d11362/docs/other.rst

> Also right now the docs aren't displaying on latest:

I have some WIP changes locally that'll fix this on all docs pages.

**Comment by WasabiFan** [comment]
I'm not sure if this was fixed in Jessie but it is in the upcoming Stretch release to I'm calling this finished.
