### ISSUE TITLE
Brickman

### ISSUE THREAD

**Issue by JolyCoder** [ev3dev/ev3dev-lang-python#416]
How to run python script in File Browser on Brickman

**Comment by ensonic** [comment]
Just select it and press the middle button. For that the script needs to be executable (+x) and needs to have the right she-bang (e.g. #!/usr/bin/python3) in the first line.

**Comment by WasabiFan** [comment]
In other words, follow this section of the README instructions: https://github.com/ev3dev/ev3dev-lang-python/blob/develop/README.rst#writing-python-programs-for-ev3dev

**Comment by WasabiFan** [comment]
@JolyDog Did this solve your problem? If so, please close the issue.
