### ISSUE TITLE
"address" argument on LEDs

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev-lang-python#422]
I was just looking at the LED code and realized that we define an "address" argument, but it's never actually used in that class — the only potential consumer I can think of is the device class's generic string conversion method. Can we remove it? I don't think there is any meaning for an "address" in the context of LEDs.

**Comment by ddemidov** [comment]
I wonder if non-system LEDs attached to output ports (as in ev3dev/ev3dev#990), have address attribute. If not, then this is a good idea.

**Comment by dwalton76** [comment]
If we remove it from the list of args we just need to set it to something so the `__str__()` doesn't barf

**Comment by ddemidov** [comment]
Would not overriding `__str__` for the `Led` class work as well?

**Comment by dwalton76** [comment]
yep that would work too

**Comment by dwalton76** [comment]
Actually, `Device.__str__()` is ok if no address is defined
```

    def __str__(self):
        if 'address' in self.kwargs:
            return "%s(%s)" % (self.__class__.__name__, self.kwargs.get('address'))
        else:
            return self.__class__.__name__
    
```
