### ISSUE TITLE
GyroBalancer: separate drive control loop and tuning from balance loop

### ISSUE THREAD

**Issue by gregcowell** [ev3dev/ev3dev-lang-python#429]
@laurensvalk has suggested [here](https://github.com/ev3dev/ev3dev-lang-python-demo/issues/8#issuecomment-340253122) that it would be nice to separate the drive control loop from the balance loop in the GyroBalancer class. I agree. 

The balance loop is the most complicated part of the code and requires knowledge of control theory to fully understand. We could leave the balance loop inside the GyroBalancer class and separate out the drive control loop into an example user script. The GyroBalancer class could then be used for many different programs rather than for a single remote control application. For example, someone may want to program BALANC3R to find its way through a maze or follow a line. Being able to utilise the balancing loop code without the drive control loop / remote control code would be very useful.

A related issue is the requirement to be able to easily tune the balancing loop parameters from a user script. 

If it is agreed that these changes would be worthwhile, I'd like to work on them.

**Comment by dwalton76** [comment]
Sounds good to me, go for it @gregcowell

**Comment by dwalton76** [comment]
Thank you @gregcowell for working on this!

**Comment by gregcowell** [comment]
> Thank you @gregcowell for working on this!

You're welcome! I really like working on this project.
