### ISSUE TITLE
MoveSteering? MotorPair?

### ISSUE THREAD

**Issue by AnishGDev** [ev3dev/ev3dev-lang-python#434]
- **ev3dev version:** 4.4.87-22-ev3dev-ev3

How do I implement a something like the move steering block in the official version of EV3 Mindstorms?

I need to control my robot via a direction ( 0 being straight) and speed. 

I have an urgent project due tomorrow. Any help will be GREATLY appreciated.

**Comment by dwalton76** [comment]
See the MoveSteering class in the develop branch. We’ve been working on an API that mimics the EVG blocks...this is one of them. 

https://github.com/ev3dev/ev3dev-lang-python/blob/develop/ev3dev/motor.py

**Comment by tasklist82** [comment]
I want to synchronize the motor.

so I want to use Motor MoveSteering class

I searched but the links including the above links do not work.

How do I use it?
