### ISSUE TITLE
Importing additional libraries

### ISSUE THREAD

**Issue by blueloose** [ev3dev/ev3dev-lang-python#438]
Hey
I wanted to install an additional library to python and it works as long as i run it as:
 `python foo.py`
but if I run it as:
`./foo.py`
it doesn't.
I know i have seen all this posts about running this command:
`sed -i 's/\r//g' <file>`
I also ran the chmod command but it still doesn't work. Do you have any suggestions or is it even possible to add an additional library?
Thank you!

**Comment by ddemidov** [comment]
What is the output of `./foo.py`?

**Comment by blueloose** [comment]
The following is the case:
I imported the pybluez library, which works if I run it as python but then the ev3dev library doesn't.
Error message: 
` import ev3dev.ev3 as ev3`
`ImportError: No module named ev3dev.ev3`

But if i execute `./foo.py` the following error message occurs:
`from: can't read /var/mail/bluetooth`
`foo.py: line 3: import: command not found`
`foo.py: line 6: syntax error near unexpected token ('`
`foo.py: line 6: client_socket=BluetoothSocket( RFCOMM )'`

**Comment by blueloose** [comment]
Im sorry i've wasted your time. The issue was, that I didn't include the following lines in my program:
`#!/usr/bin/env python3`
`# -*- coding: utf-8 -*-`
