### ISSUE TITLE
Error in the documentation for position_sp

### ISSUE THREAD

**Issue by ndward** [ev3dev/ev3dev-lang-python#440]
I think there is an error in the documentation for **position_sp** which refers to **counts_per_rot** which should be **count_per_rot**.

**Comment by ddemidov** [comment]
Should be fixed by 7578c1f123f84b4f6cf9553f058b8e64e4ac3e97

**Comment by ddemidov** [comment]
In fact, see #441

**Comment by WasabiFan** [comment]
It looks like this was fixed; closing.
