### ISSUE TITLE
Bluetooth: Android ->Bluetooth -> Ev3Dev

### ISSUE THREAD

**Issue by Crazydog974** [ev3dev/ev3dev-lang-python#448]
I can't make it work , send message by bluetooth _Android -> bluetooth -> Ev3dev._

I have this message :
read failed, socket might closed or timeout

I try with "bluetooth terminal".App  https://play.google.com/store/apps/details?id=Qwerty.BluetoothTerminal&hl=fr
and He can't connect too 

is it normal ?
> robot@ev3dev-alpha:~/Projects/Ev3Printer$ systemctl status rfcomm
> ● rfcomm.service
>    Loaded: not-found (Reason: No such file or directory)
>    Active: inactive (dead)

robot@ev3dev-alpha:~$ bluetoothctl

> Controller CC:78:AB:D7:A2:CB
>         Name: ev3dev-alpha
>         Alias: ev3dev-alpha
>         Class: 0x000100
>         Powered: yes
>         Discoverable: no
>         Pairable: yes
>         UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
>         UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
>         UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
>         UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
>         UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
>         Modalias: usb:v0694p0005d0316
>         Discovering: no
> 

my code:

```
#!/usr/bin/env python3
from ev3dev.ev3 import *

import socket
import bluetooth 

hostMACAddress = 'CC:78:AB:D7:A2:CB' # The MAC address of a Bluetooth adapter on the server. The server might have multiple Bluetooth adapters.
port = 1 # 3 is an arbitrary choice. However, it must match the port used by the client.
backlog = 1
size = 1024
s = socket.socket(socket.AF_BLUETOOTH, socket.SOCK_STREAM, socket.BTPROTO_RFCOMM)
s.bind((hostMACAddress,port))
s.listen(backlog)
try:
    client, address = s.accept()
    while 1:
        data = client.recv(size)
        if data:
            print(data)
            client.send(data)
except:	
    print("Closing socket")	
    client.close()
    s.close()
```
Please help me :)

**Comment by ensonic** [comment]
FYI: here is the bluetooth code (python) that I am using to send messages between two ev3s:
https://github.com/OpenRoberta/robertalab-ev3dev/blob/develop/roberta/ev3.py#L678

I also used this to send messages from linux to ev3, not sure if you find anything here to help with android and java.
