### ISSUE TITLE
branch naming updates

### ISSUE THREAD

**Issue by dwalton76** [ev3dev/ev3dev-lang-python#449]
Filing an issue here to bring in the changes discussed in https://github.com/ev3dev/ev3dev-lang-python-demo/issues/37

Proposal of things we should do
- ev3dev-lang-python delete as many stale repositories as we can and see where that leaves us
- ev3dev-lang-python rename develop to stretch
- ev3dev-lang-python can we delete master since we already have a jessie branch?

**Comment by dwalton76** [comment]
> ev3dev-lang-python delete as many stale repositories as we can and see where that leaves us

- @WasabiFan can ev3dev2-namespace be deleted?  It looks like it was merged
- @ddemidov what is stretch-stable...do we need this in addition to a `stretch` branch? 
- There are `micropython` and `support-micropython` branches, which of these is the most current and can we delete the other?

> ev3dev-lang-python rename develop to stretch

I will do this here in a sec assuming I have permissions

> ev3dev-lang-python can we delete master since we already have a jessie branch

I think we can, any objections? 

@dlech @rhempel  making sure you see this thread

**Comment by dwalton76** [comment]
Another one on the list was to make `jessie` the default branch so that we are consistent with other ev3dev repos. I do not have permissions to do so though, @dlech can you make this change?

**Comment by dwalton76** [comment]
Hmm I also do not have perms to rename `develop` to `jessie`
```
robot@ev3dev:~/ev3dev-lang-python$ git branch
* develop
robot@ev3dev:~/ev3dev-lang-python$ git branch -m stretch
robot@ev3dev:~/ev3dev-lang-python$ git push origin :develop stretch
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/ev3dev/ev3dev-lang-python.git
 * [new branch]      stretch -> stretch
 ! [remote rejected] develop (refusing to delete the current branch: refs/heads/develop)
error: failed to push some refs to 'https://github.com/ev3dev/ev3dev-lang-python.git'
robot@ev3dev:~/ev3dev-lang-python$ 
```

Am following https://multiplestates.wordpress.com/2015/02/05/rename-a-local-and-remote-branch-in-git/

**Comment by ddemidov** [comment]
> @ddemidov what is stretch-stable...do we need this in addition to a stretch branch?

It looks like we created `stretch-stable` to provide minimal support for stretch just before the recent major API changes.

**Comment by dwalton76** [comment]
Should we chop it? I would be fine with declaring “only new API is supported in stretch”.

**Comment by dlech** [comment]
I have updated the default branch to `jessie` on GitHub.

**Comment by ddemidov** [comment]
> Should we chop it?

Yes, let's do this.

**Comment by dwalton76** [comment]
I've deleted `stretch-stable`, I'll wait a few hours before I delete `master` in case anyone has objections.

I see there are now `develop` and `stretch` branches, they look identical to me.  @dlech did you make `stretch` today?  If so we should delete `develop`.

**Comment by dlech** [comment]
I didn't do anything other than change the default branch.

**Comment by dwalton76** [comment]
ok they were identical so I deleted `develop`....also deleted `master`. I think we can also delete `ev3dev2-namespace` but will wait to hear from @WasabiFan on that one.

**Comment by dwalton76** [comment]
@WasabiFan can we delete the `ev3dev2-namespace` branch?  That should be all that is left for this issue.

**Comment by WasabiFan** [comment]
Whoops, sorry; I guess I missed this notification. Yes, all changes from that branch were merged; I just deleted the branch.
