### ISSUE TITLE
Pixy  EV3DEV Problem Python3

### ISSUE THREAD

**Issue by kazerko** [ev3dev/ev3dev-lang-python#450]
hi, i need help with my code, after 5 hours trying i cant fix it :/

- **ev3dev version:** 4.4.87-22-ev3dev-ev3
- **ev3dev-lang-python version:** 3

**my code**:
```python
#!/usr/bin/env python3
from ev3dev.ev3 import *
import ev3dev.fonts as fonts
from PIL import Image, ImageDraw, ImageFont  # this line is optional

lcd = Screen()

# Connect Pixy camera
pixy = Sensor(address=INPUT_1)
#pixy = Sensor(address='in1:i2c1', driver_name='pixy-lego')
assert pixy.connected, "Error while connecting Pixy camera to port"

#Pixy nacitany
print("-Pixy nacitany")

# Connect LargeMotors
rmotor = LargeMotor(OUTPUT_A)
assert rmotor.connected, "Error while connecting right motor"
lmotor = LargeMotor(OUTPUT_B)
assert lmotor.connected, "Error while connecting left motor"

#motory nacitane
print("-motory nacitane")

# Connect TouchSensor
ts = TouchSensor(address=INPUT_4)
assert ts.connected, "Connecting TouchSensor"

#TouchSensor nacitany
print("-TouchSensor nacitany")

# Set mode
pixy.mode = 'TRACK'


while not ts.value():
  lcd.clear()
  if pixy.value(0) != 0:  # Object with SIG1 detected
    x = pixy.value(1) 
    y = pixy.value(2)
    w = pixy.value(3)
    h = pixy.value(4)
    dx = int(w/2)       # Half of the width of the rectangle
    dy = int(h/2)       # Half of the height of the rectangle
    xa = x - int(w/2)   # X-coordinate of bottom-right corner
    ya = y + int(h/2)   # Y-coordinate of the bottom-right corner
    xb = x + int(w/2)   # X-coordinate of bottom-right corner
    yb = y - int(h/2)   # Y-coordinate of the bottom-right corner
    lcd.draw.text((0,0), "Zaciatok Y:" + str(x), fill='black')
    lcd.draw.text((0,20), "Zaciatok X:" + str(y), fill='black')
    lcd.draw.text((0,40), "Koniec Y:" + str(w), fill='black')
    lcd.draw.text((0,60), "Koniec X:" + str(h), fill='black')
    lcd.draw.text((40,80), "Stred Y:" + str(x-w), fill='black')
    lcd.draw.text((40,100), "Stred X:" + str(y-h), fill='black')
    lcd.update()
    rmotor.run_to_rel_pos(position_sp=xa, speed_sp=-10, stop_action="coast")
    lmotor.run_to_rel_pos(position_sp=ya, speed_sp=10, stop_action="coast")
    
#koniec kodu
print("-koniec kodu")
```

**and this is output:**
```
Traceback (most recent call last):
 
 File "test.py", line 38, in <module>
    if pixy.value(0) != 0:  # Object with SIG1 detected
 
 File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 1758, in value
    self._value[n], value = self.get_attr_int(self._value[n], 'value'+str(n))
 
 File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 214, in get_attr_int
    attribute, value = self._get_attribute(attribute, name)
  
File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 196, in _get_attribute
    return attribute, attribute.read().strip().decode()
KeyboardInterrupt
```

thanks for help

**Comment by dlech** [comment]
I don't see a `TRACK` mode [here](http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-jessie/sensor_data.html#pixy-lego-modes). Perhaps you need to set the mode to `SIG1`?

**Comment by kazerko** [comment]
@dlech thanks for reply, but, when i use pixy.mode = 'SIG1' i see this:

```

Traceback (most recent call last):
  File "test.py", line 33, in <module>
    pixy.mode = 'SIG1'
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 1711, in mode
    self._mode = self.set_attr_string(self._mode, 'mode', value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 224, in set_attr_string
    return self._set_attribute(attribute, name, value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 207, in _set_attribute
    attribute.write(value.encode())
OSError: [Errno 22] Invalid argument


```

**Comment by dlech** [comment]
So you are using the mindsensors Pixy cam adapter?

**Comment by kazerko** [comment]
@dlech yes, pixi with mindstorm adapter connected to EV3 (when i tested it, camera wasnt connected to pc via usb)

can u help me with corect setting for camera and mode?

i need to control robotic arm with 3 motors by pixy cam, but i cant fix this :/

**Comment by dlech** [comment]
Your code doesn't match the [documentation](http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-jessie/sensor_data.html#ms-pixy-adapter-modes).

I would expect to see something like this...

```python
while not ts.value(0):
  lcd.clear()
  if pixy.value(0) != 0:  # Object with SIG1 detected
    x1 = pixy.value(2)  # upper left
    y1 = pixy.value(3)  # upper left
    x2 = pixy.value(4)  # lower right
    y2 = pixy.value(5)  # lower right
```

**Comment by kazerko** [comment]
@dlech hm, thanks, i see that i can use only single object with this, but i will need to use two objects in final project

it means that i need to use  I2C Sensors???

can i ask for help in next days please?...if i will need

**Comment by dlech** [comment]
The [footnote](http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-jessie/sensor_data.html#ms-pixy-adapter-mode0) gives you a hint on what to do.

It looks like there is a broken link in the footnote that is supposed to point to [this page](http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-jessie/i2c.html)

**Comment by kazerko** [comment]
@dlech ok, i want to set _poll_ms 0_, but i dont know where to write it, 
```python
pixy = Sensor(address='in1:i2c1', driver_name='ms-pixy-adapter', poll_ms='0')
```
is this correct? 
if yes, which _pixy.mode_ i will use now?

**Comment by dlech** [comment]
Personally, I would not try to use the `Sensor` class for this. Instead I would use direct I2C commands using the `smbus` module.

This is totally untested, but base on the information in ev3dev/ev3dev#445, which uses a different sensor but the same methods.

```python
from ev3dev.ev3 import *
from smbus import SMBus

# get a Port object to control the input port
in1 = Port(address=INPUT_1)
# force the port into i2c-other mode so that the default driver is not automatically loaded
in1.mode = 'i2c-other'

# might need a short delay here (e.g. time.sleep(0.5)) to wait for the I2C port to be setup
# note: this delay should only be needed in ev3dev-jessie (4.4.x kernel), not ev3dev-stretch (4.9.x kernel)

bus = SMBus(3)  # bus number is input port number + 2
I2C_ADDRESS = 0x01  # the default I2C address of the sensor

while True:
    # read the number of object detected
    num = bus.read_byte_data(I2C_ADDRESS, 0x42)
    if num:
        x1, y1, x2, y2 = bus.read_i2c_block_data(I2C_ADDRESS, 0x44, 4)
        # do stuff with coordinates
```

**Comment by kazerko** [comment]
@dlech after test this code (i changed "Port" in line 5 to "Sensor"):

```python
robot@ev3dev:~$ python3 get.py
Traceback (most recent call last):
  File "get.py", line 7, in <module>
    in1.mode = 'i2c-other'
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 1711, in mode
    self._mode = self.set_attr_string(self._mode, 'mode', value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 224, in set_attr_string
    return self._set_attribute(attribute, name, value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 211, in _set_attribute
    raise Exception('Device is not connected')
Exception: Device is not connected
```

...sorry i am stupid :@ ...oin brick i have "set mode" at "other-i2c"

**Comment by dlech** [comment]
> sorry i am stupid

What? You figured out that `other-i2c` was correct instead of `i2c-other` and that you can also set the mode on the brick. :smiley: 

I was lazy and didn't look at the [documentation](http://ev3dev-lang.readthedocs.io/projects/python-ev3dev/en/master/other.html#lego-port). It looks like I messed that up too. It should probably be:

    in1 = LegoPort(address=INPUT_1)

instead of

    in1 = Port(address=INPUT_1)

**Comment by kazerko** [comment]
@dlech now, it looks correct, but, its not responding and after ctrl+c cancel it write this:
```python
robot@ev3dev:~$ python3 get.py
^CTraceback (most recent call last):
  File "get.py", line 19, in <module>
    num = bus.read_byte_data(I2C_ADDRESS, 0x42)
KeyboardInterrupt
```
...i just wanted print(x1) for test..

**Comment by dlech** [comment]
What does the whole program look like now?

**Comment by kazerko** [comment]
```python
from ev3dev.ev3 import *
from smbus import SMBus

# get a Port object to control the input port
in1 = LegoPort(address=INPUT_1)
# force the port into i2c-other mode so that the default driver is not automatically loaded
in1.mode = 'other-i2c'

# might need a short delay here (e.g. time.sleep(0.5)) to wait for the I2C port to be setup
# note: this delay should only be needed in ev3dev-jessie (4.4.x kernel), not ev3dev-stretch (4.9.x kernel)

time.sleep(0.5)

bus = SMBus(3)  # bus number is input port number + 2
I2C_ADDRESS = 0x01  # the default I2C address of the sensor

while True:
    # read the number of object detected
    num = bus.read_byte_data(I2C_ADDRESS, 0x42)
    if num:
        x1, y1, x2, y2 = bus.read_i2c_block_data(I2C_ADDRESS, 0x44, 4)
        # do stuff with coordinates
        
print(x1)
```

**Comment by dlech** [comment]
The `while True:` causes an infinite loop, so the program never gets to the `print(x1)` statement at the end. You can delete that line (and change the indent of the later lines) if you just want to read the values once for testing.

**Comment by dlech** [comment]
or you can indent the `print(x1)` line to print the value many times.

**Comment by kazerko** [comment]
got it, thanks, but answer is just [0, 0, 0, 0]...
...and i cant cancel program with my touch sensor
```python
from ev3dev.ev3 import *
from smbus import SMBus

# get a Port object to control the input port
in1 = LegoPort(address=INPUT_1)
# force the port into i2c-other mode so that the default driver is not automatically loaded
in1.mode = 'other-i2c'

# might need a short delay here (e.g. time.sleep(0.5)) to wait for the I2C port to be setup
# note: this delay should only be needed in ev3dev-jessie (4.4.x kernel), not ev3dev-stretch (4.9.x kernel)

time.sleep(0.5)

# Connect TouchSensor
ts = Sensor(address=INPUT_4)
assert ts.connected, "Connecting TouchSensor"

bus = SMBus(3)  # bus number is input port number + 2
I2C_ADDRESS = 0x01  # the default I2C address of the sensor

while not ts.value():
    # read the number of object detected
    num = bus.read_byte_data(I2C_ADDRESS, 0x42)
    if num:
        x1, y1, x2, y2 = bus.read_i2c_block_data(I2C_ADDRESS, 0x44, 4)

        # do stuff with coordinates
    while True:
        print(bus.read_i2c_block_data(I2C_ADDRESS, 0x44, 4))        

```

**Comment by QuirkyCort** [comment]
Your program is stuck in the While True loop with the print() statement, that's why you can't exit the program using the touch sensor.

I don't have a Pixy, but from the serial protocol documentations (http://cmucam.org/projects/cmucam5/wiki/Pixy_Serial_Protocol), it seems that the Pixy streams its data continuously, and don't use registers like a normal i2c device.

There is also a PixyAdapter (https://www.generationrobots.com/media/PixyAdapter-User-Guide.pdf) that you may be using. If so, it'll behave like a normal i2c device, but the default address should be 0x02. I'll suggest taking it slow, and try reading the vendor/device ID first, just to make sure that your i2c connection is working correctly.

If you haven't trained your Pixy, you may also need to do that first.

**Comment by dlech** [comment]
> There is also a PixyAdapter (https://www.generationrobots.com/media/PixyAdapter-User-Guide.pdf) that you may be using

Yes, it has has already been stated here that this adapter is being used.

> but the default address should be 0x02

In Linux, the address is different from the one stated in the manufacturer's documentation. See http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-jessie/i2c.html for an explanation. 0x01 is the correct address and it has already been shown to be working.

> If you haven't trained your Pixy, you may also need to do that first.

This would explain an output of all zeros.

**Comment by kazerko** [comment]
hi, im back, time is running so fast and i just fixed canceling with touch sensor, program is answering only this [0, 0, 0, 0] and i dont know how to set correct adress if i want to use 2 objects

i2c is not so easy to understand for me and i need to: 
```python3
control #1motor with #1object at X axis
control #2motor with #1object at Y axis
control #3motor with #2object at X axis
```

actual part of code with address setting:
```python3
bus = SMBus(3)  # bus number is input port number + 2
I2C_ADDRESS = 0x01  # the default I2C address of the sensor


num = bus.read_byte_data(I2C_ADDRESS, 0x42)
if num:
    x1, y1, x2, y2 = bus.read_i2c_block_data(I2C_ADDRESS, 0x44, 4)

while not ts.value():
    print(bus.read_i2c_block_data(I2C_ADDRESS, 0x44, 4))
```

**Comment by dlech** [comment]
Did you train your Pixy cam as @QuirkyCort suggested? Also, make sure the USB cable is disconnected from the camera before running your python program.

The I2C commands are just taking the information from the "I2C Registers" section of the PixyCam Adapter users guide.

For example, when we say `num = bus.read_byte_data(I2C_ADDRESS, 0x42)`, that mean read one byte from register 0x42, which is the "Number of objects detected".

If we wanted to read the color of the 1st object, we would write `color1 = bus.read_byte_data(I2C_ADDRESS, 0x43)`

To read more than one register at a time, we can use `read_i2c_block_data` instead of `read_byte_data`. The last parameter is the number of bytes to read, so `bus.read_i2c_block_data(I2C_ADDRESS, 0x44, 4)` will read registers 0x44, 0x45, 0x46 and 0x47.

**Comment by kazerko** [comment]
USB is disconnected all time

so, if i want to use coordinates of tracking item, which address a need to use

**Comment by kazerko** [comment]
i dont know where is problem, i tryed all register codes from here:
[https://www.generationrobots.com/media/PixyAdapter-User-Guide.pdf](url)

answer is all time just [0,0,0,0] ... at 0x10 it is [80, 105, 120, 121]

```python
bus = SMBus(3)  # bus number is input port number + 2
I2C_ADDRESS = 0x01  # the default I2C address of the sensor

while not ts.value():
    print(bus.read_i2c_block_data(I2C_ADDRESS, 0x42))
```

**Comment by QuirkyCort** [comment]
Connection seems fine. If you haven't trained your PixyCam, you should do so. It's not gonna give you any results if you don't train it to recognise the color you want.

You may also want to use PixyMon to test out your PixyCam. You should be able to tell from there if your PixyCam is setup and working correctly.

As a long shot, try sending the command to unlock the tracking buffer. I doubt the lock would stay on through a power cycle, but I don't own a PixyCam so what would I know...

**Comment by kazerko** [comment]
@QuirkyCort with PixyMon work cam very good
 
and without using PC i trained cam like here: 
[https://youtu.be/J8sl3nMlYxM?t=1m56s](link)
...(LED on cam responding with correct color)

**Comment by QuirkyCort** [comment]
Well, your PixyCam is working fine, and you seem to be reading ok from the PixyAdapter (...the values that you got at 0x10 is the device ID). So the problem is probably between the PixyCam and the PixyAdapter.

From the PixyAdapter manual, try...

Configuring PixyCam
- Open the PixyMon viewer and configuration software.
- Select 'Configure' from 'File' Menu.
- Select the 'Interface' tab under the 'Pixy Parameters' tab.
- Make sure the UART baudrate is 115200 and click 'OK'

If you don't get this right, the PixyAdapter won't be able to read from the PixyCam.

**Comment by kazerko** [comment]
@QuirkyCort oh man, thanks, that was the problem! now, i can move on
(data out port was I2C and address 0x54 :/ )

**Comment by kazerko** [comment]
hi, i need to make condition of x2, if it will be increasing:
```python
rmotor.run_to_rel_pos(position_sp=10,` speed_sp=-50, stop_action="coast")
```

and if it will be decreasing:
```python
rmotor.run_to_rel_pos(position_sp=-10, speed_sp=-50, stop_action="coast")
```

but i dont know how its correct syntax for if

**Comment by kazerko** [comment]
@QuirkyCort @dlech  hi, my code is finally done, but i can't run it from brick without USB connection
error here:
[https://imgur.com/lRc8Z9O](https://imgur.com/lRc8Z9O)

do i need some optimization?

**Comment by dlech** [comment]
I don't see what this has to do with USB. The picture you posted says that there is a syntax error in your code.

**Comment by kazerko** [comment]
@dlech but its work correct when i run it via MobaXterm with "python3 get.py"
and when i want run it in brick in file browser i see that error

**Comment by dlech** [comment]
Make sure your program starts with `#!/usr/bin/env python3`

**Comment by kazerko** [comment]
@dlech  my last, "bonus" problem is how to get motors to default position on the end of the program 
you know, rotating with the motors and on the end it will return to position where it started

this is my actualy code:
```python
while True:
    if btn.any():                                       # Checks if any button is pressed.
        Sound.beep().wait()                             # Wait for the beep to finish.
        exit()                                          # Stop the program.
    else:
        lcd.draw.text((60,10),'RUNNING!')
        lcd.draw.text((0,30),'-pre manipulaciu stlacte')
        lcd.draw.text((5,40),'poistne tlacidlo')
        lcd.draw.text((0,70),'-pre vypnutie stlacte')
        lcd.draw.text((5,80),'lubovolne tlacidlo jednotky')
        lcd.draw.text((40,115),'TUZVO _ Jan Maro _ 2018')
        lcd.update()
        x1, y1, x2, y2 = bus.read_i2c_block_data(I2C_ADDRESS, 0x44, 4) #1 ITEM use only senond x y
        z1, w1, z2, w2 = bus.read_i2c_block_data(I2C_ADDRESS, 0x48, 4) #2 ITEM use only senond x y
        
        if ts.value():
            rmotor.run_to_rel_pos(position_sp=x1-70, speed_sp=50, stop_action="coast")
            lmotor.run_to_rel_pos(position_sp=y2-70, speed_sp=50, stop_action="coast")
            mmotor.run_to_rel_pos(position_sp=z1, speed_sp=50, stop_action="coast")
            print('item #1')
            print(bus.read_i2c_block_data(I2C_ADDRESS, 0x44, 4)) #1 ITEM 
            print('item #2')
            print(bus.read_i2c_block_data(I2C_ADDRESS, 0x48, 4)) #2 ITEM 
        else:
            rmotor.stop
            lmotor.stop
            mmotor.stop
```

...i tried this [solution](https://bricks.stackexchange.com/questions/2973/how-to-remember-initial-position-of-a-robot-and-return-to-it) but i cant use run_position_limited
