### ISSUE TITLE
ev3dev-lang-python-fast

### ISSUE THREAD

**Issue by QuirkyCort** [ev3dev/ev3dev-lang-python#451]
Hi everyone,

I started https://github.com/QuirkyCort/ev3dev-lang-python-fast which is a high (...or at least higher) performance drop-in replacement for ev3dev-lang-python. The performance comparison was only done on an EV3 running Jessie, so I'm not sure if it's still relevant with Stretch.

It's a clean re-implementation, and not a modification of ev3dev-lang-python, so I'm not entirely sure which changes resulted in the most performance improvements, but I'm guessing that the biggest contributors are through using bin_data instead of valueN, and from caching the mode and setting it only if necessary (...the latter can cause problems if there are multiple instances of the same sensor).

Anyway, it works for me, but I didn't test it enough to be confident of contributing these performance enhancements to ev3dev-lang-python.

**Comment by ddemidov** [comment]
Hi, the performance comparison looks very promising! I think we definitely should try to bring at least some of the changes here.

**Comment by dlech** [comment]
> using bin_data instead of valueN

One thing to watch out for here that `bin_data` is a "raw" value and `valueN` is a "scaled" value. For UART and most I2C sensors, these numbers are the same, but for analog sensors, you will have to do the scaling in python.


> the latter can cause problems if there are multiple instances of the same sensor

Do you mean exactly the same sensor or just the same kind of sensor?

**Comment by QuirkyCort** [comment]
> Do you mean exactly the same sensor or just the same kind of sensor?

Same sensor on the same port. Here's a demonstration of the problem...
```
instance1 = ColorSensor('in1')
instance2 = ColorSensor('in1')

print(instance1.reflected_light_intensity)
print(instance2.color)                     # Changes mode to color
print(instance1.reflected_light_intensity) # This will give the wrong value
```
ev3dev-lang-python should work correctly, as it sets the mode on every read, but my fast version will give the wrong value as it tracks the mode internally within each instance and only sets it if it thinks that there's a change.

I'm guessing there's not a lot of use cases for creating multiple instances of the same sensor, and the performance benefit of not setting the mode on every read may be very substantial, but this could break things if the user depended on this behavior.

**Comment by ensonic** [comment]
Wow, this sounds nice indeed. Regarding the scaling, don't we have to do this anyway?
https://github.com/OpenRoberta/robertalab-ev3dev/blob/develop/roberta/ev3.py#L581
``` python
def scaledValue(self, sensor):
    return sensor.value() / float(10.0 ** sensor.decimals)
```

**Comment by dlech** [comment]
> Regarding the scaling, don't we have to do this anyway?

Only if you care about the decimal place being in the "correct" place.

However, the scaling I am referring to are things like [this](https://github.com/ev3dev/lego-linux-drivers/blob/ev3dev-stretch/sensors/nxt_analog_sensor_defs.c#L200) that convert the 0-5V value to the proper unit of  measurement. In the NXT Light sensor example I linked, the `bin_data` value will return the analog voltage of the sensor (0 to 5000mV), which is scaled to 0 to 100% where 4116mV is 0% and 543mV is 100%.

**Comment by WasabiFan** [comment]
Thanks for letting us know about this. I'm going to close the issue to keep our issue tracker clearer as I don't believe there are any actionable changes mentioned here.
