### ISSUE TITLE
PiStorms - Exception 'LED is not connected'

### ISSUE THREAD

**Issue by KWSmit** [ev3dev/ev3dev-lang-python#452]
- **ev3dev version:** 4.9.59-ev3dev-1.6.0-rpi2
- **ev3dev-lang-python version:** 3
- **Hardware:** PiStorms v2 with RPi 3B

When trying to address the LEDs on my PiStorms I retrieve the Exception 'LED is not connected'.

Sample code:
```
#!/usr/bin/env python3
from time import sleep
import ev3dev.ev3 as ev3

ev3.Leds.all_off()
sleep(2)
```
The exception occurs on the first statement which addresses the LEDs, in this case `ev3.Leds.all_off()`, but also with other methods, like `ev3.Leds.set()` or `ev3.Leds.set_color()`.

Listing of /sys/class/leds:
```
input0::capslock    pistorms:BA:blue:brick-status
input0::compose     pistorms:BA:green:brick-status
input0::kana        pistorms:BA:red:brick-status
input0::numlock     pistorms:BB:blue:brick-status
input0::scrolllock  pistorms:BB:green:brick-status
led0                pistorms:BB:red:brick-status
led1
```

**Comment by dlech** [comment]
This is because you are importing `ev3dev.ev3`, which is the LEGO MINDSTORMS EV3 brick.

Starting with v1.2.0, you can now import `ev3dev.pistorms` instead of `ev3dev.ev3` and it should work.

**Comment by KWSmit** [comment]
When I do this I get an ImportError `No module named 'ev3dev.pistorms'` (using the same version of ev3dev as stated above: 4.9.59-ev3dev-1.6.0-rpi2). That's why I used `ev3dev.ev3` because everything seemed to work this way (except the Leds). Also tried `ev3dev.PiStorms` but same result.

**Comment by dlech** [comment]
It works for me. Please upgrade your packages or use the most recent snapshot image.

    sudo apt update
    sudo apt upgrade

**Comment by KWSmit** [comment]
Yes, upgrading packages did the trick. Now working with `4.14.39-ev3dev-2.0.1-rpi2` and it works fine, both using module `ev3dev.pistorms` and using leds. Also display on PiStorms screen works great with this version (kernel issue #1086, already closed). Thanks a lot David!
