### ISSUE TITLE
new display driver in kernel 4.14.x

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev-lang-python#455]
I just released a new ev3dev kernel on ev3dev-stretch that updates from 4.9.x to 4.14.x. This comes with a new display driver for the EV3 from the mainline kernel.

The new driver still provides a fbdev device (`/dev/fb0`) however, the memory layout is different. Because of limitations in the mainline kernel, there is no monochome. Instead it uses a 32-bit XRGB pixel format.

This causes an error with ev3dev-lang-python. See https://github.com/ev3dev/ev3dev/issues/1022#issuecomment-381444425

**Comment by dlech** [comment]
In reality, though, the display will now use 2-bit (4 color) grayscale :open_mouth:

**Comment by ddemidov** [comment]
So it looks like we should add a case for `self.var_info.bits_per_pixel == 32` here with an appropriate encoder:
https://github.com/ev3dev/ev3dev-lang-python/blob/55f57ada176905a1db073423f428bd83dfd6b6ca/ev3dev/core.py#L3314-L3319

**Comment by ddemidov** [comment]
3b34f78e4232f05f2304771a89dcb0231d6f5812 might help, but I did not have time to update to the 4.14 kernel and actually test it.

**Comment by ndward** [comment]
It's not clear to me whether the update() function in the 22 April Stretch image has been fixed. Is there something different I should be doing to be able to update the LCD? Should I expect a fix for this any time soon? Am I right in thinking that all the Stretch images released so far for the EV3 suffer either from the brickd hyperactivity bug or the update() function not working?

**Comment by dlech** [comment]
given the fact that this issue is still marked as open, I don't see why one would expect that it has been fixed.

in the meantime, if you want an older kernel with fixed brickd, I would suggest using an image older than 14 April and just upgrade the brickd package, but not the kernel (`sudo apt update && sudo apt install brickd`).

**Comment by ddemidov** [comment]
@ndward, you can help by testing if 3b34f78e4232f05f2304771a89dcb0231d6f5812 works. You can do it by doing something like this in the EV3 command line:
```sh
git clone -b display-4.14 https://github.com/ev3dev/ev3dev-lang-python test-display-fix
cd ./test-display-fix
# test display by running some script from this directory,
# or interactively by opening python3
```
If you run any script while in `test-display-fix` directory, then this version of ev3dev should be picked up instead of the one installed system-wide.

**Comment by ndward** [comment]
I followed your instructions, then put this script in the test-display-fix folder (specifically, I used SFTP Net Drive to copy this script from another folder, which caused the copy to no longer be executable, so I then made it executable with chmod). Is it correct that I put the script directly in the test-display-fix folder and not in a subfolder?
```
#!/usr/bin/env python3
from ev3dev.ev3 import *
from time import sleep
lcd = Screen()
lcd.clear()
lcd.update()
sleep(5)
```
When I ran that script (right-click + Run in the EV3 browser) I got
```
Starting: brickrun --directory=/home/robot/test-display-fix /home/robot/test-display-fix/lcdtestshort.py
Started.
----------
Traceback (most recent call last):
  File "/home/robot/test-display-fix/lcdtestshort.py", line 6, in <module>
    lcd.update()
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 3325, in update
    raise Exception("Not supported")
Exception: Not supported
----------
Exited with error code 1.
```
I got the same result using python3 interactively.

If the font is large in the above paragraph then that is not deliberate.
```
Image file:         ev3dev-stretch-ev3-generic-2018-04-22
Kernel version:     4.14.34-ev3dev-1.6.1-ev3
Brickman:           0.10.0
ev3devKit:          0.5.2
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=00165340377E
BOARD_INFO_TYPE=main
```

**Comment by ddemidov** [comment]
The main module is now named `ev3dev2` I think. Can you change the line
```py
from ev3dev.ev3 import *
```
to
```py
from ev3dev2.auto import *
```
?

**Comment by ddemidov** [comment]
Also, the `Screen` class is now called `Display`. There was some big restructuring recently in the `stretch` branch.

**Comment by ndward** [comment]
When I ran this script
```
#!/usr/bin/env python3
from ev3dev2.auto import *
from time import sleep
lcd = Display()
lcd.clear()
lcd.update()
sleep(5)
```
I got
Starting: brickrun --directory=/home/robot/test-display-fix /home/robot/test-display-fix/lcdtestshort.py
```
Started.
----------
Traceback (most recent call last):
  File "/home/robot/test-display-fix/lcdtestshort.py", line 6, in <module>
    lcd.update()
  File "/home/robot/test-display-fix/ev3dev2/display.py", line 290, in update
    self.mmap[:] = self._img_to_xrgb_bytes()
  File "/home/robot/test-display-fix/ev3dev2/display.py", line 277, in _img_to_xrgb_bytes
    return pack('H' * len(pixels), *pixels)
struct.error: ushort format requires 0 <= number <= (0x7fff * 2 + 1)
----------
Exited with error code 1.
```
Apart from Screen() becoming Display(), are there many other changes that need to be made in scripts? Is there a list of necessary changes somewhere?

**Comment by jabrena** [comment]
This is an important point, not only for Python library and users related. We should announce and track all changes to synchronize the changes or at least try. For Java, I will have to see how to solve the Display issue too, and it is complex. :(

**Comment by ddemidov** [comment]
@ndward, thanks for testing! I've pushed a fix that should address the problem. You can get it by doing `git pull` from inside `test-display-fix` directory. Can you try if that works?

**Comment by ddemidov** [comment]
The branch is yet to be released (this is a development branch). When that happens, I guess there will be a list of changes.

**Comment by ndward** [comment]
Same simple script now gives:
```
Starting: brickrun --directory=/home/robot/test-display-fix /home/robot/test-display-fix/lcdtestshort.py
Started.
----------
----------
Completed successfully.
```

**Comment by ndward** [comment]
I added a line to draw text:
```
#!/usr/bin/env python3
from ev3dev2.auto import *
from time import sleep
lcd = Display()
lcd.clear()
lcd.draw.text((10,10), 'Hello World!')
lcd.update()
sleep(5)
```

The script completed after 1m8s but no text was drawn.

**Comment by ddemidov** [comment]
@dlech, does this look correct to you?

https://github.com/ev3dev/ev3dev-lang-python/blob/de3029b9502ff3254c3553a2131d046995367219/ev3dev2/display.py#L269-L277

The only idea I have is to try and switch the byte order: now it is `0RGB`, the other options to try are `RGB0` or `BGR0`.

**Comment by ndward** [comment]
Thanks, @dlech for the suggestion as to how to obtain an older kernel with fixed brickd. It seems to work. For the first time I feel I can use VS Code with EV3 without having to worry about the brickd bug and while being able to run all the standard commands without problems, except that the load average still seems high. This capture was made while the EV3 was idle:
![upgradebrickd](https://user-images.githubusercontent.com/9800891/39253845-1c89052e-48a9-11e8-9158-d9b7d044f893.JPG)
Despite the high load average, the script
```
#!/usr/bin/env python3
from ev3dev.ev3 import *
from time import sleep
lcd = Screen()
lcd.clear()
lcd.update()
sleep(5)
```
completed in about 25s (including the sleep), which seems OK.

**Comment by dlech** [comment]
> @dlech, does this look correct to you?

Hmm... I think I would add a special case for EV3 int `Display.__init__()`. If platform == EV3 and self.var_info.bits_per_pixel != 1 then create an 8-bit grayscale (PIL type 'L') image.

Then, for the conversion function, take the 'L' image one byte at a time and expand it to a 32 bit value, making R, G and B each having the same value. 

```python
def _gray_xrgb(self, value): 
         """Convert grayscale to a 32-bit XRGB value. Value
         should be values 0 to 255. 
         """ 
return ((value << 16) | (value << 8) | value) 
```

**Comment by ndward** [comment]
I noticed when I did a screen capture with the latest version that the image was not monochrome - the highlight in Brickman was blue (and attractive).

Two suggestions for the screen capture:

- the captured image is tiny on a PC screen - it would be nice to have the option of capturing a double-sized image (double size in both dimensions). I know the image can be zoomed or saved and resized externally but it would be nice to be able to save the larger image straight from VS Code.
- Also, it would be good if the background of the image were not white since often the image will be viewed against a white background and the edges are then not visible.

@WasabiFan incorporated both these ideas in his capture script which is accessible at https://sites.google.com/site/ev3python/learn_ev3_python/screen . He used a background color which resembles that of the EV3 LCD which is RGB (173, 181, 120).

**Comment by ddemidov** [comment]
#462 is tested and works on stretch.

**Comment by dlech** [comment]
Fix released in v1.2.0

**Comment by dwalton76** [comment]
Can we close this one?

**Comment by WasabiFan** [comment]
I think so. https://github.com/ev3dev/ev3dev-lang-python/issues/501 covers the remaining work.
