### ISSUE TITLE
ev3dev-stretch: breaking kernel change: brickpi port prefix change

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev-lang-python#459]
In the `ev3dev-2.0.0` kernel release (currently uploading), there has been a change in the brickpi driver that resulted in the prefix being changed from `ttyAMA0` to `serial0-0`.

**Comment by dlech** [comment]
Fix released in v1.2.0

**Comment by WasabiFan** [comment]
Released in the v2 beta as well. Closing.
