### ISSUE TITLE
branch confusion

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev-lang-python#466]
1. There appears to be commits for ev3dev-stretch in the `jessie` branch
2. What is the purpose of the `ev3dev2-namespace` branch? It seems that the `stretch` branch contains the `ev3dev2` namespace already.
3. There is no branch for the 1.x releases (tags).

**Comment by dlech** [comment]
Re: item 3, the reason I am asking about this is because I am going to go ahead do a v1.2.0 release that fixes the kernel breakage in ev3dev-stretch since it doesn't appear that 2.x is ready for release yet.

**Comment by dwalton76** [comment]
Item 1: can you point me at some of them?

Item 2: I am pretty sure ev3dev2-namespace can be deleted but I was waiting for confirmation from @wasabifan, see #449.

**Comment by dlech** [comment]
> Item 1: can you point me at some of them?

* https://github.com/ev3dev/ev3dev-lang-python/commit/57e1991ace2d9011d073cb28f042c57473de03ff
* https://github.com/ev3dev/ev3dev-lang-python/commit/078b98a24b9c8fdc2b49dba86279df14df8e8769

**Comment by dwalton76** [comment]
I don’t have a good answer...looks like we made a mistake :(

**Comment by dlech** [comment]
So how should we fix it?

**Comment by WasabiFan** [comment]
I've been out of the loop; it looks like the only problematic changes in those two commits are the updates to the LED and button strings, is that correct? Assuming this wasn't already done, does anyone see a reason not to revert those two particular parts of those changes in a new commit? Also, why hasn't anyone encountered an issue with that yet (or have they, and I'm just oblivious)?

**Comment by ddemidov** [comment]
> Assuming this wasn't already done, does anyone see a reason not to revert those two particular parts of those changes in a new commit?

:+1:

> Also, why hasn't anyone encountered an issue with that yet (or have they, and I'm just oblivious)?

Probably because the changes to jessie were made after the package was released?

**Comment by WasabiFan** [comment]
I believe this has been fixed; please reopen if it's still an issue.
