### ISSUE TITLE
ev3dev-lang-python always uses /dev/fb0 unless the FRAMEBUFFER environment variable is set

### ISSUE THREAD

**Issue by KWSmit** [ev3dev/ev3dev-lang-python#469]
- **ev3dev version:** 4.14.39-ev3dev-2.0.1-rpi2
- **ev3dev-lang-python version:** 1.2.0

There is a bug in ev3dev-lang-python: it always uses `/dev/fb0` unless the `FRAMEBUFFER` environment variable is set. There is a method `FrameBuffer.get_fb_for_console()` that should actually be used internally.

**Comment by dwalton76** [comment]
The only reference I can find to ``FrameBuffer.get_fb_for_console()`` is in dlech's ev3dev-photo-booth repo:
https://github.com/dlech/ev3dev-photo-booth/blob/master/ev3dev-photo-booth.py

but this is three years old, I'm not sure how his class compares with our current ``FbMem`` and ``Display`` classes.

**Comment by dwalton76** [comment]
Given that
- `/dev/fb0` is almost always going to be the framebuffer used
- we support the `FRAMEBUFFER` environment variable to use something else
- the referenced `FrameBuffer.get_fb_for_console()` is in a different code base

I am going to close this one...feel free to re-open if you object.
