### ISSUE TITLE
BrickPi3 + RaspberryPi model B+ Python programming 

### ISSUE THREAD

**Issue by raphabenoi** [ev3dev/ev3dev-lang-python#471]
Hi there,

I read all the resources I could find but am still not really smarter. But I am sure you can help me out!

I am currently at the beginnings of a very ambitious project and I struggle to find the right way to program my BrickPis.

I want to build a car manufacturing supply chain with an assembly unit. My model will have 2 suppliers (vertical warehouses), one assembly unit and a Lego PowerFunctions train to connect the different modules.
The orchestration of all the different production steps will be done in the cloud. This is why I chose to go for the BrickPi since the Raspberry gives me easy connectivity.

But I don't know how to best program my robots. The different options I found are:
– The Dexter Industries based Raspbian Jessie distribution. However, I find the programming rather difficult and unintuitive (from the examples I saw. I couldn’t test it yet since it does not run on the latest Raspberry Pi B+. But it looks like there is a Beta out that will offer support.)
– EV3DEV Jessie distribution (couldn’t test it for the same reasons). Is EV3DEV2 the new standard? Does it work well with the BrickPi3 and the newest RaspberryPi?

In your eyes, what is the easiest way to program my robots?

I hope you can help me make the right choices from the beginning and not realize halfway through the project that I went with the wrong setup :)

Thank you and have a nice weekend!

**Comment by dwalton76** [comment]
I would start here https://sites.google.com/site/ev3python/learn_ev3_python lots of good lessons to try out
