### ISSUE TITLE
Problems using the 'Hi Technic Color Sensor'

### ISSUE THREAD

**Issue by APersonH** [ev3dev/ev3dev-lang-python#472]
ev3dev version: 4.4.87-22-ev3dev-ev3

Hi, I'm having trouble using the 'Hi Technic Color Sensor'. When I try the read it's output, I get this:
```
robot@ev3dev:~$ python3 test.py
<bound method Sensor.value of <ev3dev.core.Sensor object at 0xb6c3ad50>>
<bound method Sensor.value of <ev3dev.core.Sensor object at 0xb6c3ad50>>
<bound method Sensor.value of <ev3dev.core.Sensor object at 0xb6c3ad50>>
<bound method Sensor.value of <ev3dev.core.Sensor object at 0xb6c3ad50>>
<bound method Sensor.value of <ev3dev.core.Sensor object at 0xb6c3ad50>>
```

My program looks like this:
```
#!/usr/bin/env python3
import ev3dev.ev3 as ev3

m = ev3.LargeMotor('outA')
m.run_timed(time_sp=3000, speed_sp=500, stop_action='brake')

c = ev3.Sensor(address='in1:i2c1', driver_name='ht-nxt-color-v2')
count = 0
while count < 5:
        data = c.value
        print(data)
        count += 1
```
I have already read the thread [here](https://github.com/ev3dev/ev3dev-lang-python/issues/333,) but nothing there helped me out

**Comment by dlech** [comment]
`value` is a method. The line `data = c.value` assigns `data` to the method itself instead of calling the method. Try this instead: `data = c.value(0)`.

**Comment by WasabiFan** [comment]
@APersonH Were you able to resolve your issue with the information @dlech provided? If so, please close this issue.

**Comment by APersonH** [comment]
Yes, it worked, thank you
