### ISSUE TITLE
Update to new Stretch port names

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev-lang-python#476]
As mentioned in https://github.com/ev3dev/ev3dev-lang-python/issues/339, motor port names have changed in Stretch. We're going to need to update the library and test infrastructure.

**Comment by dwalton76** [comment]
@WasabiFan I think we can close this one?

**Comment by WasabiFan** [comment]
I think (?) my intent was to backport this to the 1.x branch: https://github.com/ev3dev/ev3dev-lang-python/commits/ev3dev-stretch-1.x

I can't tell if I did that though. That being said, no one's complaining, so stuff seems to work...
