### ISSUE TITLE
Should SpeedInteger actually be floating-point?

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev-lang-python#479]
We have these new `SpeedInteger` classes. But... as it turns out, it might make more sense to have them be `SpeedFloat`s (or, more likely, a better name like `SpeedMeasure` or simply `Speed`). My thinking is: given that we're converting from whatever input units are provided to native units (eventually), we should minimize intermediate truncations to enable the granularity that ticks-per-second provides. This should just be a matter of changing the name, inheritance and documentation mentions.

**Comment by dwalton76** [comment]
Makes sense to me

**Comment by WasabiFan** [comment]
@dwalton76 What were the motivations for implementing the `SpeedInteger` family so they were directly inherited from `int` rather than being their own class with a single field? I'm motivated to switch it to the latter for two reasons:

- The inheritance from a system type makes things like stringification [weird](https://github.com/ev3dev/ev3dev-lang-python/blob/ev3dev-stretch/ev3dev2/motor.py#L84)
- It seems that Micropython doesn't support the pattern

**Comment by dwalton76** [comment]
I think it was just “well we are adding to the behavior from int so let’s inherit from that”. I don’t have any objections to changing it.
