### ISSUE TITLE
why delete debian/x.y.z tags?

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev-lang-python#484]
I am wondering why @ddemidov deleted all of the debian/x.y.z tags just now. These are tags where debian packages were built from, so they were useful if we ever needed to rebuild those debian packages.

**Comment by ddemidov** [comment]
I did `push --tags` and saw that it pushed some new tags aside from 1.2.0. I deleted those. Do you want me to push them again?

**Comment by dlech** [comment]
Ah, they are probably from my repo when I was doing debian package releases for @rhempel. It would not hurt to have them in this repo as well just for historical purposes.

**Comment by ddemidov** [comment]
I've just repushed the tags.
