### ISSUE TITLE
Cannot update library

### ISSUE THREAD

**Issue by slendidev** [ev3dev/ev3dev-lang-python#494]
I have the old ev3dev-jessie library and cannot update to the new ev3dev-stretch library due to connection problems. I can send files to it over ssh. Can I forcly install it without apt(not working) and pip(takes way too long)?

**Comment by dlech** [comment]
You need to re-flash your microSD card to install ev3dev-stretch.

**Comment by slendidev** [comment]
Yesterday I downloaded and flashed the newest version from the website

**Comment by dlech** [comment]
From here?

https://oss.jfrog.org/list/oss-snapshot-local/org/ev3dev/brickstrap/2018-08-06/

**Comment by slendidev** [comment]
Let me quickly try that... Also, out of curiosity, what do you use to flash? I use Etcher

**Comment by dlech** [comment]
:+1: Etcher

**Comment by slendidev** [comment]
I will update you when the batteries are fully charged and then I flash it on an SD card

**Comment by xslendix** [comment]
Also, is an I'm file, do I exctract it or simply put the whole thing in Etcher?

**Comment by slendidev** [comment]
It worked! Yeeey! Thanks for the help! 🎉🎉🎉🎉
