### ISSUE TITLE
importing all the files

### ISSUE THREAD

**Issue by DigitalRookie** [ev3dev/ev3dev-lang-python#496]
hi i am trying to create a wiimote powered robot and a remote(the one that comes with it). i have tried everything such as installing pip via a Ubuntu app and also trying to use the environmental variables in my computer but i have  no clue how to install modules such as ev3dev.ev3, pyev3 and cwiid. 

please can you help and reply!

**Comment by DigitalRookie** [comment]
also whenever i try pip install cwiid which i have been told to do by PyPI it always comes up saying

Collecting cwiid
  Using cached https://files.pythonhosted.org/packages/fa/e8/d0f03c60bbdc583a7fa37a126e9b20055fb3752861820c25bd212dc62756/cwiid-3.0.0.tar.gz
Building wheels for collected packages: cwiid
  Running setup.py bdist_wheel for cwiid ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-KE1LtO/cwiid/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-ZYpotk --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'cwiid' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cwiidmodule.c -o build/temp.linux-x86_64-2.7/cwiidmodule.o
  cwiidmodule.c:138:15: error: variable ‘moduledef’ has initializer but incomplete type
   static struct PyModuleDef moduledef = {
                 ^
  cwiidmodule.c:139:2: error: ‘PyModuleDef_HEAD_INIT’ undeclared here (not in a function)
    PyModuleDef_HEAD_INIT,
    ^
  cwiidmodule.c:139:2: warning: excess elements in struct initializer
  cwiidmodule.c:139:2: note: (near initialization for ‘moduledef’)
  cwiidmodule.c:140:2: warning: excess elements in struct initializer
    "cwiid",        /* m_name */
    ^
  cwiidmodule.c:140:2: note: (near initialization for ‘moduledef’)
  cwiidmodule.c:141:2: warning: excess elements in struct initializer
    "Cwiid FFS!",   /* m_doc */
    ^
  cwiidmodule.c:141:2: note: (near initialization for ‘moduledef’)
  cwiidmodule.c:142:2: warning: excess elements in struct initializer
    -1,             /* m_size */
    ^
  cwiidmodule.c:142:2: note: (near initialization for ‘moduledef’)
  cwiidmodule.c:143:2: warning: excess elements in struct initializer
    Module_Methods, /* m_methods */
    ^
  cwiidmodule.c:143:2: note: (near initialization for ‘moduledef’)
  cwiidmodule.c: In function ‘PyInit_cwiid’:
  cwiidmodule.c:156:17: warning: implicit declaration of function ‘PyModule_Create’ [-Wimplicit-function-declaration]
    if (!(Module = PyModule_Create(&moduledef))) {
                   ^
  cwiidmodule.c:156:15: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
    if (!(Module = PyModule_Create(&moduledef))) {
                 ^
  cwiidmodule.c:162:10: warning: ‘return’ with a value, in function returning void
     return NULL;
            ^
  cwiidmodule.c:180:9: warning: ‘return’ with a value, in function returning void
    return Module;
           ^
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for cwiid
  Running setup.py clean for cwiid
Failed to build cwiid
Installing collected packages: cwiid
  Running setup.py install for cwiid ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-KE1LtO/cwiid/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-X0b7CR/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'cwiid' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cwiidmodule.c -o build/temp.linux-x86_64-2.7/cwiidmodule.o
    cwiidmodule.c:138:15: error: variable ‘moduledef’ has initializer but incomplete type
     static struct PyModuleDef moduledef = {
                   ^
    cwiidmodule.c:139:2: error: ‘PyModuleDef_HEAD_INIT’ undeclared here (not in a function)
      PyModuleDef_HEAD_INIT,
      ^
    cwiidmodule.c:139:2: warning: excess elements in struct initializer
    cwiidmodule.c:139:2: note: (near initialization for ‘moduledef’)
    cwiidmodule.c:140:2: warning: excess elements in struct initializer
      "cwiid",        /* m_name */
      ^
    cwiidmodule.c:140:2: note: (near initialization for ‘moduledef’)
    cwiidmodule.c:141:2: warning: excess elements in struct initializer
      "Cwiid FFS!",   /* m_doc */
      ^
    cwiidmodule.c:141:2: note: (near initialization for ‘moduledef’)
    cwiidmodule.c:142:2: warning: excess elements in struct initializer
      -1,             /* m_size */
      ^
    cwiidmodule.c:142:2: note: (near initialization for ‘moduledef’)
    cwiidmodule.c:143:2: warning: excess elements in struct initializer
      Module_Methods, /* m_methods */
      ^
    cwiidmodule.c:143:2: note: (near initialization for ‘moduledef’)
    cwiidmodule.c: In function ‘PyInit_cwiid’:
    cwiidmodule.c:156:17: warning: implicit declaration of function ‘PyModule_Create’ [-Wimplicit-function-declaration]
      if (!(Module = PyModule_Create(&moduledef))) {
                     ^
    cwiidmodule.c:156:15: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
      if (!(Module = PyModule_Create(&moduledef))) {
                   ^
    cwiidmodule.c:162:10: warning: ‘return’ with a value, in function returning void
       return NULL;
              ^
    cwiidmodule.c:180:9: warning: ‘return’ with a value, in function returning void
      return Module;
             ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-KE1LtO/cwiid/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-X0b7CR/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-KE1LtO/cwiid/

**Comment by dlech** [comment]
We recommend always installing python packages using the debian package system rather than pip.

Try this:

    sudo apt update
    sudo apt install python-cwiid

However, note that the ev3dev python library is python**3** only and the cwiiid library is python**2** only, so you won't be able to use both at the same time.

Instead, I think you can use the evdev library to get raw input events from the wiimote.

**Comment by DigitalRookie** [comment]
Ok, cheers but do you also need to get the updated module because i am using the more up to date version  ev3dev2 or something like that. also apparently i need a module called pyev3 but do i need to just use sudo apt install but with pyev3 instead. which python is pyev3 designed for. i think i found a way can the new ev3dev take both of the new software. i have got two types of python i have python 2.7 and python3.7. i am not entirely too sure which is python 2 and which is pyhton 3. about the wiimote, sorry about this but can you explain a bit more simply to me what you meant by "Instead, I think you can use the evdev library to get raw input events from the wiimote.". also i am very sorry if i am asking a lot of questions. i am quite experienced with python and i have almost started it a year ago.

**Comment by DigitalRookie** [comment]
also which terminal should i write the commands into because i have got a Ubuntu app and also a command line which i am not good with.  which one should i use

**Comment by DigitalRookie** [comment]
whats the command to get pyev3 and ev3dev.ev3

**Comment by DigitalRookie** [comment]
do i need to get ev3dev2 because i have tired to get it via sudo and pip and neither have worked

**Comment by dlech** [comment]
I am not familiar with "pyev3". The ev3dev2 python3 library comes pre-installed on the ev3dev-stretch 2018-08-06 image. Documentation for evdev library is [here](https://python-evdev.readthedocs.io/en/latest/) and there is an (older) example of using evdev with a PS3 controller [here](https://www.ev3dev.org/docs/tutorials/using-ps3-sixaxis/).

**Comment by dlech** [comment]
evdev is also pre-installed.

**Comment by DigitalRookie** [comment]
its pre installed on what
do you mean ev3dev2

**Comment by DigitalRookie** [comment]
would it be ok if i used a debian app to get it

**Comment by DigitalRookie** [comment]
ok can you recommend to me how to control the remote that comes with the
ev3 and how to code it via python

**Comment by DigitalRookie** [comment]
i have got python 27 and python 37 can you tell me which is python 3 and
which is python 2

**Comment by DigitalRookie** [comment]
i went into a python lang ev3dev stretch file and found a motor program but as soon as i ran it. it came up saying unable to import ev3dev2 and 
[ev3dev-lang-python-ev3dev-stretch.zip](https://github.com/ev3dev/ev3dev-lang-python/files/2290016/ev3dev-lang-python-ev3dev-stretch.zip)

**Comment by DigitalRookie** [comment]
^^^^^^^that is what code i have used and found

**Comment by DigitalRookie** [comment]
also whenever i try to run python27 with cwiid it says no module named cwiid

**Comment by DigitalRookie** [comment]
@dlech OK i am using vscode and in python2.7 cwiid does now work but in vscode it does not work. and this cwiid file is still not working because it can't find the libraries/modules. here is what @G33kDude has done (this is the person who created it). can you give me the up to date version of how this code would be written out.


import time

import cwiid
import pyev3

def clamp(value, lower, upper):
	return min(upper, max(value, lower))

print 'press 1+2 on the wiimote now'
time.sleep(1)
w = cwiid.Wiimote()
print 'connected?'
w.led = 6
w.rpt_mode = cwiid.RPT_ACC | cwiid.RPT_BTN

left_motor = pyev3.Motor(pyev3.OUTPUT_B)
left_motor.reset()
left_motor.run_mode = 'forever'
left_motor.regulation_mode = 'on'

right_motor = pyev3.Motor(pyev3.OUTPUT_C)
right_motor.reset()
right_motor.run_mode = 'forever'
right_motor.regulation_mode = 'on'

arm = pyev3.Motor(pyev3.OUTPUT_D)
arm.reset()
arm.run_mode = 'forever'
arm.regulation_mode = 'off'

target_distance = 8
top_speed = 720

left_motor.run = 1
right_motor.run = 1

last_btn_state = 0
move = 0

try:
	while True:
		state = w.state
		
		buttons = state['buttons']
		if buttons != last_btn_state:
			if buttons & cwiid.BTN_MINUS:
				top_speed -= 10
				print top_speed
			if buttons & cwiid.BTN_PLUS:
				top_speed += 10
				print top_speed
			if buttons & cwiid.BTN_2:
				move = 1
			elif buttons & cwiid.BTN_1:
				move = -1
			else:
				move = 0
			if buttons & cwiid.BTN_LEFT:
				arm.duty_cycle_sp = 100
				arm.run = 1
			elif buttons & cwiid.BTN_RIGHT:
				arm.duty_cycle_sp = -100
				arm.run = 1
			else:
				arm.run = 0
			print top_speed, move
			last_btn_state = buttons
		
		if move:
			acc = state['acc']
			tilt = (clamp(acc[1], 95, 145) - 120) / 25.0 # roughly between -0.5 and 0.5
			turn = top_speed * tilt
			turn = clamp(turn, -abs(top_speed), abs(top_speed))
			left_motor.pulses_per_second_sp = int(top_speed - turn) * move
			right_motor.pulses_per_second_sp = int(top_speed + turn) * move
		else:
			left_motor.pulses_per_second_sp = 0
			right_motor.pulses_per_second_sp = 0
finally:
	left_motor.run = 0
	right_motor.run = 0

**Comment by Will2004** [comment]
(this is still me)

**Comment by magicalpear** [comment]
> We recommend always installing python packages using the debian package system rather than pip.
> 
> Try this:
> 
> ```
> sudo apt update
> sudo apt install python-cwiid
> ```
> However, note that the ev3dev python library is python**3** only and the cwiiid library is python**2** only, so you won't be able to use both at the same time.
> 
> Instead, I think you can use the evdev library to get raw input events from the wiimote.

Or compile cwiid for python3 
https://github.com/azzra/python3-wiimote

After compiling python3-wiimote, I am able to use cwiid module in python 3 and use the ev3dev2 in the same code

Compilation may require to install many packages. Connection to wii control may fail sometime (during the "press 1+2" period). And sometimes Bluetooth device not showing up until next reboot (ev3dev driver issue).

**Comment by Will2004** [comment]
That is the problem!  When I run any code containing ev3dev2 it just comes up saying unable to import ev3dev2 and when I try to run the code on the robot it just waits the screen goes for about one fifth of a second and then goes back to the screen I was at before that.
