### ISSUE TITLE
Motors are inconsistant

### ISSUE THREAD

**Issue by Lenascha** [ev3dev/ev3dev-lang-python#499]
I have been working on a little Robot thats supposed to have ADAS. The program itself is not the problem though. For it to work the turns that the robot does as well as the distance it drives have to be the same each time it moves. However thats not the case. 
Has anyone else had this problem before? 
if I just tell the motors to run to a certain position and I run that program 3 times it covers a different distance each time. 
Is there a way to fix this?
Thank you!

**Comment by WasabiFan** [comment]
We can't help you unless you do what the issue template asks. You need to tell us the software versions you're using and give us a sample of your code.

```
<!--
    Before we can help you, we need some information about what you are trying to do and what software you are using.
    If you are reporting a bug or asking a usage question, please fill out the information below; otherwise you can delete this template.
-->

- **ev3dev version:** PASTE THE OUTPUT OF `uname -r` HERE
- **ev3dev-lang-python version:** INSERT ALL VERSIONS GIVEN BY `dpkg-query -l python3-ev3dev*` HERE

<!-- Now tell us about what you were trying to do, and include any error messages you received. Be specific and include any involved code, please! Make sure to include your import statements as well. -->

```
