### ISSUE TITLE
python3-ev3dev v2 play_tone() problems

### ISSUE THREAD

**Issue by ndward** [ev3dev/ev3dev-lang-python#506]
ev3dev version: 4.14.61-ev3dev-2.2.2-ev3
ev3dev-lang-python version:
ii python3-ev3dev 1.2.0 all Python language bindings for ev3dev
ii python3-ev3dev2 2.0.0~beta1 all Python language bindings for ev3dev

I have two problems with the new function **play_tone()**, part of python-ev3dev v2. 
Firstly, it's very similar to the v1 function **tone()** except that **tone()** needs a time in milliseconds whereas **play_tone()** needs seconds (in line with EB3-G) and that **tone()** can accept a tone sequence as an argument whereas **play_tone()** cannot. It's confusing to have two such similar functions so I hope that the older function **tone()** will one day be suppressed but before that happens **play_tone()** needs to be able to accept a tone sequence as an argument.

The second problem with **play_tone()** is that it does not appear to work. When I run either of these
`sound.play_tone(1000, 3)`
`sound.play_tone(1000, 3, delay=0.0, volume=100, play_type=0)`
I get an error:
Traceback (most recent call last):
  File "/home/robot/robots/EDUCATOR/demo_sound.py", line 39, in <module>
    sound.play_tone(1000, 3) #, delay=0.0, volume=100, play_type=0)
  File "/usr/lib/python3/dist-packages/ev3dev2/sound.py", line 224, in play_tone
    play.wait()
AttributeError: **'NoneType' object has no attribute 'wait'**

Similarly, with this 
`sound.play_note('D4', 2, volume=100, play_type=0)`
I get
  File "/home/robot/robots/EDUCATOR/demo_sound.py", line 53, in <module>
    sound.play_note('D4', 2, volume=100, play_type=0)
  File "/usr/lib/python3/dist-packages/ev3dev2/sound.py", line 258, in play_note
    return self.play_tone(freq, duration=duration, volume=volume, play_type=play_type)
  File "/usr/lib/python3/dist-packages/ev3dev2/sound.py", line 224, in play_tone
    play.wait()
AttributeError: **'NoneType' object has no attribute 'wait'**

**Comment by WasabiFan** [comment]
Fix released in `2.0.0~beta2`. To upgrade:

```
sudo apt-get update
sudo apt-get install --only-upgrade python3-ev3dev2
```
