### ISSUE TITLE
gyro.reset() error - needs bytes-like object not int

### ISSUE THREAD

**Issue by matskew** [ev3dev/ev3dev-lang-python#510]
- **ev3dev version: 4.14.61-ev3dev-2.2.2-ev3
- **ev3dev-lang-python version:
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                      Version           Architecture      Description
+++-=========================-=================-=================-=======================================================
ii  python3-ev3dev            1.2.0             all               Python language bindings for ev3dev
ii  python3-ev3dev2           2.0.0~beta1       all               Python language bindings for ev3dev

To reset a lego mindstorms gyro, one needs to write the byte 17 directly to the UART.
sensor/lego.py attempts to do this by doing:

self.set_attr_raw(self._direct, 'direct', 17)

This maps to a file IO write, which can only take a bytes-like object and not the int 17.

Changing the "17" to "bytes((17,))" seems to fix the problem. "bytes([17])" would also work, but is less efficient.

**Comment by matskew** [comment]
Let me say that my suggestion fixes the problem of "GyroSensor.reset() throws an exception." However, successfully writing that 0x11 into the UART doesn't seem to reset the angle read off of the gyro. It doesn't seem to do anything at all, really.

The old hack of changing the mode of the gyro (e.g. changing it to MODE_GYRO_RATE and then back to MODE_GYRO_ANG) to reset the current angle to zero still works, but I thought GyroSensor.reset() was supposed to be the new and improved technique.

**Comment by dlech** [comment]
What is the date stamp on your gyro sensor? e.g. "22N5"

**Comment by matskew** [comment]
My lego gyro sensor is O5N8 as best I can tell. I purchased it new from lego in August 2018.

**Comment by WasabiFan** [comment]
@dlech where'd we get this technique for resetting the sensor? I don't see a mention in the docs (I might be missing something) and the relevant issue seems to suggest just resetting the mode: https://github.com/ev3dev/ev3dev/issues/402

**Comment by dlech** [comment]
It comes from the official LEGO programming software. https://github.com/ev3dev/ev3dev-lang-python/issues/362
