### ISSUE TITLE
New site to promote python3-ev3dev v2

### ISSUE THREAD

**Issue by ndward** [ev3dev/ev3dev-lang-python#511]
I've been working on a new site devoted to EV3dev Python v2 and the VS Code workflow. From today I've made it accessible to anyone with this link: https://sites.google.com/site/ev3devpython/ but search engines should not be able to find it yet so you are the only people who know of its existence. 
It's a copy of my older v1 site at https://sites.google.com/site/ev3python which has been extensively modified to match EV3dev Python v2. Currently the domain name ev3python.com points to the old site but at some point I will make it point to the new site which has links back to the old one for people still using the older functions. Both sites are aimed mainly at a beginner audience.

I invite you to visit the new site and to provide feedback here. Two pages in particular 'Keyboard control' and 'Sensor Modes' probably are not needed with EV3 Python v2 and should be deleted? I'm aware of a number of other problems such as a few scripts that don't work.

Assuming the new site is useful and not too full of errors then when should it be made public and linked to from the old site, with ev3python.com pointing to the new site? Obviously not yet because there are still significant problems with EV3 Python v2 such as the mis-handling of negative or zero angles by the 'on' commands. Also some of the scripts try to use the IR sensor to measure the proximity of objects but @wasabifan tells me that in EV3 Python IR proximity refers only to the proximity of the IR _beacon_, although EV3-G can also measure the proximity of _objects_.

I understand that EV3dev Python v2 is still in beta but the suppression of **speed_pct** has already been done (issue #508, now closed) so perhaps there won't be many more breaking changes. Please let me know if any breaking changes ARE expected. Version 2 is so superior to version 1, especially for beginners since it is much more similar to EV3-G, that I am keen to encourage my beginner audience to switch as soon as possible to the new version 2 functions.

**Comment by WasabiFan** [comment]
Version 2 of this library, and ev3dev-stretch as a whole, are currently considered a "beta". That means that it should be entirely usable and is expected to work well, but we may still change things that would cause code which works now to not work after an upgrade. So my suggestion would be to wait at least until we release the next beta release of this library, which will be probably in the next few weeks. We don't know exactly what other breaking changes might be made until we remove the "beta" label.

> in EV3 Python IR proximity refers only to the proximity of the IR beacon, although EV3-G can also measure the proximity of objects.

ev3dev does the same thing that EV3-G does, whatever that is. The sensing logic is built in to the sensor; we ask the sensor for the "proximity" value and it returns it. So, if LEGO built the sensor so it attempts to guess distance to objects, it will do that. However, the IR sensor is _literally just an infrared LED connected to a processor chip_, so if it does claim to measure distance to objects, all it can do is shine some light out and see how much comes back. That will be extremely inaccurate (both in EV3-G and ev3dev). My suggestion would be to use an ultrasonic sensor which is built for distance sensing.

If you still have issues with the IR sensor, please open a new issue.

**Comment by ndward** [comment]
I've just redirected the domain name **ev3python.com** to point to the new site which is devoted to version 2 of EV3dev Python. The old site devoted to version 1 can still be accessed at **v1.ev3python.com**.

**Comment by dwalton76** [comment]
@ndward thank you for doing this! :) Will take a look at it this weekend. 

One thing to clarify on the site is "version 2 of ev3dev-lang-python" vs "version 2 of python".
` In October 2018 another huge improvement was made with the introduction of a new Python library (version 2)`

We are only using python version 3 now but the line above might confuse folks.

**Comment by ndward** [comment]
I've changed a few references from 'Python' to 'EV3 Python' or 'EV3dev Python' to reduce the risk of confusion. I thank you in advance for pointing out errors on my site - I'm sure you will find many!

**Comment by dwalton76** [comment]
@ndward can I mention your new site in this thread?
https://www.eurobricks.com/forum/index.php?/forums/topic/168586-ev3dev-venturing-into-the-world-of-ev3dev-and-python/&page=2

**Comment by ndward** [comment]
Of course! 😀
