### ISSUE TITLE
Add port name constants for stacked BrickPi's

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev-lang-python#527]
Mentioned here: https://github.com/ev3dev/ev3dev-lang-python/issues/525

It seems it would be easy enough to add those. I believe the limit is 4 stacked BrickPi's at once.

**Comment by dwalton76** [comment]
Cool I did not know you could stack them :)

**Comment by WasabiFan** [comment]
Fixed by #562 and #572
