### ISSUE TITLE
rate_and_angle() should be renamed angle_and_rate()

### ISSUE THREAD

**Issue by ndward** [ev3dev/ev3dev-lang-python#531]
4.14.61-ev3dev-2.2.2-ev3
ii  python3-ev3dev 1.2.0        all          Python language bindings for ev3d
ii  python3-ev3dev 2.0.0~beta2  all          Python language bindings for ev3d

Gyro: rate_and_angle() reports angle and rate, in that order. The function should, IMHO, be renamed angle_and_rate()

**Comment by dwalton76** [comment]
Looking at #362 the EVG block we were following uses angle_and_rate() so yeah seems like a logical change.
