### ISSUE TITLE
play() and play_file() are almost identical. Do we need both?

### ISSUE THREAD

**Issue by ndward** [ev3dev/ev3dev-lang-python#532]
4.14.61-ev3dev-2.2.2-ev3
ii  python3-ev3dev 1.2.0        all          Python language bindings for ev3d
ii  python3-ev3dev 2.0.0~beta2  all          Python language bindings for ev3d

play() and play_file() are apparently identical except that one can set the volume with play_file(). Do we need both functions? Can one be suppressed? Is it clear which one should be used (it's not clear to me).

**Comment by dwalton76** [comment]
Seems like we can combine them. #358 has the EV3-G blocks for sound.
