### ISSUE TITLE
wait_until_angle_changed_by(delta) is not direction-sensitive

### ISSUE THREAD

**Issue by ndward** [ev3dev/ev3dev-lang-python#534]
4.14.61-ev3dev-2.2.2-ev3
ii  python3-ev3dev 1.2.0        all          Python language bindings for ev3d
ii  python3-ev3dev 2.0.0~beta2  all          Python language bindings for ev3d

https://python-ev3dev.readthedocs.io/en/ev3dev-stretch/sensors.html#ev3dev2.sensor.lego.GyroSensor.wait_until_angle_changed_by

wait_until_angle_changed_by(delta): Wait until angle has changed by specified amount.

It's not clear from the above description whether this is direction-sensitive. For example, if I have delta = +90° (clockwise rotation) and the sensor is turned 100° counterclockwise, does that mean the angle has changed by delta?

My tests make me think that the direction does NOT matter, but quite often users will be looking for a turn _in a specific direction_, so I'm surprised the function cannot handle that. Maybe the function can be made direction-sensitive?

**Comment by dwalton76** [comment]
The code is using the abs() of the delta so the direction does not matter.

**Comment by WasabiFan** [comment]
@dwalton76 I think Nigel is suggesting that it would be useful to make it direction-sensitive. It seems reasonable to me that we could add an argument which skipped the `abs` call to enable that scenario.
