### ISSUE TITLE
How to use sensors in Python?

### ISSUE THREAD

**Issue by coffeedood** [ev3dev/ev3dev-lang-python#535]
I'm wondering what you use for sensors for example is it "spi0.1:S1"?  I mostly want to try to have a sensor on Input S1 on the 1st brickpi and have it turn the motor on spi0.1:ME.  What should I use to control the Ev3 TouchSensor on S1?

**Comment by WasabiFan** [comment]
Please see the examples in our README. We have constants for the various port names so you just have to use the named constants.

```python
from ev3dev2.motor import OUTPUT_A
from ev3dev2.sensor import INPUT_1

ts = TouchSensor(INPUT_1)
m = LargeMotor(OUTPUT_A)
```

**Comment by coffeedood** [comment]
hmmm I still haven't been able to get sensors to work.  Here is a giant list of attempts to get it working.  the touch sensor is plugged into S2 and it generally comes up with the same error each time. 
This is what my python script looks like before I try to run it. 

```python
#!/usr/bin/env python3
from ev3dev.brickpi3 import *

from ev3dev2.motor import LargeMotor, OUTPUT_A, OUTPUT_B, SpeedPercent, MoveTank
from ev3dev2.sensor import INPUT_2
from ev3dev2.sensor.lego import TouchSensor
from ev3dev2.led import Leds

ts = TouchSensor(INPUT_2)
m = LargeMotor(OUTPUT_A)

while True:
    if ts1.value() == 0:
      m.stop(stop_action="brake")
    else:
      m.run_forever(speed_sp=180)   # equivalent to power=20 in EV3-G
```

the error generally says
```
Traceback (most recent call last):
  File "run21.py", line 9, in <module>
    ts = TouchSensor(INPUT_2)
  File "/home/robot/ev3dev2/sensor/lego.py", line 49, in __init__
    super(TouchSensor, self).__init__(address, name_pattern, name_exact, driver_name=['lego-ev3-touch', 'lego-nxt-touch'], **kwargs)
  File "/home/robot/ev3dev2/sensor/__init__.py", line 103, in __init__
    super(Sensor, self).__init__(self.SYSTEM_CLASS_NAME, name_pattern, name_exact, **kwargs)
  File "/home/robot/ev3dev2/__init__.py", line 191, in __init__
    raise DeviceNotFound("%s is not connected." % self) from None
ev3dev2.DeviceNotFound: TouchSensor(spi0.1:S2) is not connected.
```
any suggestions?

**Comment by dlech** [comment]
BrickPis cannot automatically detect sensors. You must create a port object for each port, then select the proper mode for the port. Some modes also require that you set the `set_device` property to the appropriate sensor. There is more discussion about this in #280.

**Comment by dwalton76** [comment]
coffeedood did David’s suggestion help?

**Comment by coffeedood** [comment]
I think the brickpi3 recognizes the touch sensor but I can't seem to get python programs to run with them.  I am trying to get a python program to run that would run the motor when you push the touch sensor.  This is the program I'm running but it doesn't seem to work.  Any suggestions?

import ev3dev.brickpi3 as ev3

p = ev3.LegoPort(ev3.INPUT_1)
p.mode = "nxt-analog"
p.set_device = "lego-nxt-touch"

ts = ev3.TouchSensor(ev3.INPUT_1)
m=ev3.LargeMotor(ev3.OUTPUT_B)

while not ts.value():
        m.run_timed(time_sp=100, speed_sp=500)

**Comment by dlech** [comment]
In your original comment, you say you have an EV3 Touch sensor, but in your code you are configuring the BrickPi3 for an NXT Touch sensor. These are two different devices.

**Comment by WasabiFan** [comment]
Is there still an issue to be fixed here or can this be closed?
