### ISSUE TITLE
DistanceValue classes

### ISSUE THREAD

**Issue by dwalton76** [ev3dev/ev3dev-lang-python#541]
I am a big fan of the way the SpeedValue classes have turned out, I think we should do the same for distances.  Potential classes

- DistanceValue
- DistanceMilliMeters
- DistanceCentiMeters
- DistanceMeters
- DistanceInches
- DistanceFeet

**Comment by WasabiFan** [comment]
I think this makes sense. What use cases do we have? Right now it would be the differential drive class?

**Comment by dwalton76** [comment]
Yep MoveDifferential could use this, right now all distances have to be in mm. Odometry (not implemented yet) would be another one. 

DistanceStuds would be another handy class.

**Comment by ddemidov** [comment]
May be at this point it is worth looking at something like https://pint.readthedocs.io.
