### ISSUE TITLE
SpeedValue sanity checks only happen in to_native_units()

### ISSUE THREAD

**Issue by dwalton76** [ev3dev/ev3dev-lang-python#545]
Today the SpeedValue child classes perform a sanity check when to_native_units is called.  We should use a setter method so that we sanity check the value when the user tries to assign it.

**Comment by WasabiFan** [comment]
Are there supported cases right now where you set the property on an existing `SpeedValue`? If not we might just be able to move the check into the constructor.

**Comment by dwalton76** [comment]
We support multiplication of SpeedValue by an int or float (once MoveDifferential goes in).  Even without that there isn't anything in place to prevent the user for setting the main speed variable in each child class, to something that would fail in to_native_units().

**Comment by dwalton76** [comment]
Once I started implementing this I quickly realized you can only do the sanity checks if you know what motor you are sanity checking against. The motor obj is not stored as part of the class it is passed in to to_native_units(). Am going to close this one.
