### ISSUE TITLE
Push button to run motors?

### ISSUE THREAD

**Issue by coffeedood** [ev3dev/ev3dev-lang-python#561]
- **ev3dev version:** PASTE THE OUTPUT OF `uname -r` HERE
- **ev3dev-lang-python version:** INSERT ALL VERSIONS GIVEN BY `dpkg-query -l python3-ev3dev*` HERE

when I run this program it doesnt quite do what I want.  I mostly just want it to run the motor when I push the touch sensor.  This is the program I'm running.

```python
#!/usr/bin/env python3
from ev3dev.brickpi3 import *

from ev3dev2.motor import LargeMotor, OUTPUT_A, OUTPUT_B, SpeedPercent, MoveTank
from ev3dev2.sensor import INPUT_1
from ev3dev2.sensor.lego import TouchSensor
from ev3dev2.led import Leds

ts = TouchSensor(INPUT_1)
m = LargeMotor(OUTPUT_B)

while True:
    if ts.value() == 0:
      m.stop(stop_action="brake")
    else:
      m.run_forever(speed_sp=180)   # equivalent to power=20 in EV3-G
```

When I run the program it just turns the motor but when I unplug the touch sensor the motor stops.  I guess I still haven't been able to find a way to simply touch the touch sensor and have it turn the motor.

**Comment by dwalton76** [comment]
It seems like it would run as long as you are holding down the touch sensor. Add a “break” after the run_forever() call so that you drop out of that while True loop.

**Comment by dwalton76** [comment]
@coffeedood did you get this one figured out?

**Comment by coffeedood** [comment]
I still have not figured this out yet.  I've tried two different methods And both haven't worked.  It seems like it recognizes the touch sensor but the python script isn't working.  Any advice.

**Comment by dwalton76** [comment]
What is the exact behavior you are seeing and can you post your latest code? 

For next steps I would start putting in print() statements to help figure out what is happening

**Comment by WasabiFan** [comment]
Is there an issue that still needs to be fixed here or can this be closed?

**Comment by happyFox1982** [comment]
try this code, and find the differences:

         import ev3dev.ev3 as ev3
         import time

         print('I am ready!')

          l = ev3.LargeMotor('outA')
          r = ev3.LargeMotor('outD')
          ts = ev3.TouchSensor()

           while ts.is_pressed==False :
            continue

           ev3.Sound.speak('I shall run!').wait()

           l.run_timed(time_sp=3000, speed_sp=700)
           r.run_timed(time_sp=4000, speed_sp=700)
