### ISSUE TITLE
Gyro sensor bug 

### ISSUE THREAD

**Issue by mistrjirka** [ev3dev/ev3dev-lang-python#568]
- **ev3dev version: 4.14.80-ev3dev-2.3.1-ev3
- **ev3dev-lang-python version: ii  python3-ev3dev                    1.2.0                 all                   Python language bindings for ev3dev

Hi.
When I'm trying to get value from gyro sensor in mode GYRO-ANG. This error sometimes occurs when the sensor is in backwards motion. 

traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 169, in do
    self.TrueTurn.straight(-1, self.motor_speed, self.straight_tolerance)
  File "/home/robot/robotnasoutez-pacman/trueturn.py", line 189, in straight
    while self.GS.value() not in field:
  File "/usr/lib/python3/dist-packages/ev3dev2/sensor/__init__.py", line 216, in value
    self._value[n], value = self.get_attr_int(self._value[n], 'value'+str(n))
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 278, in get_attr_int
    return attribute, int(value)
ValueError: invalid literal for int() with base 10: ''

**Comment by mistrjirka** [comment]
Yeah I don't know how to do pull request (sorry I'm an idiot), so here is what fixed my problems and it is real s***t. 
all changes are in __init__.py in the folder /ev3dev2
replace function on the line 286 with this:

```
def get_attr_int(self, attribute, name):
        attribute, value = self._get_attribute(attribute, name)
        
        if RepresentsInt(value):
                return attribute, int(float(value))
        else:
                return attribute, 0

```
and add this function to the head of the script
```
def RepresentsInt(s):
    try: 
        int(s)
        return True
    except ValueError:
        return False

```

PS: this is not fix of the bug this is only walk-around, it may case wrong values from the sensors.

**Comment by WasabiFan** [comment]
What was the bad value returned? Could you add a `print(s)` in the `except` so we can see?

**Comment by mistrjirka** [comment]
I thought it was something like "0/n". I will look at it after school.

**Comment by dwalton76** [comment]
Am testing with this
```
#!/usr/bin/env python3


from ev3dev2.sensor import INPUT_2
from ev3dev2.sensor.lego import GyroSensor
from time import sleep
import logging
import sys

# logging
logging.basicConfig(level=logging.DEBUG,
                    format="%(asctime)s %(levelname)5s: %(message)s")
log = logging.getLogger(__name__)

gyro = GyroSensor(INPUT_2)

for x in range(10):
    print("{}: angle {}".format(gyro, gyro.angle))
    print("{}: rate {}".format(gyro, gyro.rate))
    print("{}: angle_and_rate {}\n".format(gyro, gyro.angle_and_rate))
```

And am rotating the bot around...everything appears to be working.

**Comment by mistrjirka** [comment]
It doesn't show that error every time I move it, it almost only happens when I try to move it backwards. I maybe find an issue in my code. I reset the sensor and immediately I try to get values from it. Is that a problem?

**Comment by WasabiFan** [comment]
It's certainly possible that reading immediately after resetting the sensor causes it to not behave well. What's the use case that requires that? Could you add a short delay after the reset?

**Comment by mistrjirka** [comment]
It was used for direction correction when turning. I reset the sensor every time I turned, because sometimes I was getting value overflow error on the sensor value.

**Comment by dwalton76** [comment]
@mistrjirka are you still seeing this issue with the gyro?

**Comment by dwalton76** [comment]
please re-open if this is still an issue

**Comment by WesleyJ-128** [comment]
I'm getting the same issue. I think in my case it's related to reading the angle repeatedly in a short amount of time (again, in a drive control loop).

**Comment by dlech** [comment]
The error `ValueError: invalid literal for int() with base 10: ''` is generally caused by reading the same value from different threads concurrently.

**Comment by WesleyJ-128** [comment]
I figured that out but forgot to mention it here; that's exactly what I was doing (and didn't need to be).
