### ISSUE TITLE
MoveJoystick super() bug 

### ISSUE THREAD

**Issue by scprotz** [ev3dev/ev3dev-lang-python#575]
Using the MoveJoystick function with a Logitech F710 and evdev.  Set everything up and created a separate thread to update MoveJoystick function from motor.py.

The MoveJoystick function has a small bug.  It tries to call MoveTank.off(), but MoveTank.off() is not a static method and so throws an error.  it should be super.off() since MoveTank is parent to MoveJoystick.

In 2.0.0b it is line 1957 of motor.py.  If I knew how to push the change, I'd do it, but I'm  not very good with git.

**Comment by WasabiFan** [comment]
Thanks for reporting! Yes, this looks like a bug we introduced when changing how `off` works.
