### ISSUE TITLE
Connecting nxt ultrasonic sensor with a hitechnic sensor multiplexer does not work

### ISSUE THREAD

**Issue by w1ref1re** [ev3dev/ev3dev-lang-python#586]
ev3dev version:
 4.14.80-ev3dev-2.3.1-ev3

ev3dev-lang-python version:
ii  python3-ev3dev 1.2.0        all          Python language bindings for ev3d
ii  python3-ev3dev 2.0.0~beta2  all          Python language bindings for ev3d

I am trying to connect a lego nxt ultrasonic sensor to my ev3 through an hitechnic sensor multiplexer.
I read that i have to manually set the device with  "set_device = "lego-nxt-us"".
I am always getting an OSError: [Errno 22] Invalid argument error.

My code:

```python
port = LegoPort(address="in2:i2c8:mux2")
port.mode = 'i2c'
port.set_device = "lego-nxt-us"
us = UltrasonicSensor(address="in2:i2c8:mux")
```

The error:

```python
line 3, in <module>    
    port.set_device = "lego-nxt-us"
 File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 3077, in set_device
    self._set_device = self.set_attr_string(self._set_device, 'set_device', value)
 File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 229, in set_attr_string
    return self._set_attribute(attribute, name, value)
 File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 211, in _set_attribute
    attribute.write(value.encode())
OSError: [Errno 22] Invalid argument
```

I tried everything and need your help now.
Thanks in advance.

**Comment by dlech** [comment]
This mux itself also show up as a sensor. You can use the generic `Sensor` class for this. If I recall, you have to put the mux in `RUN` mode before you can read any values. The `DETECT` mode can be a bit temperamental, but it should be able to be used to detect the LEGO NXT Ultrasonic sensor. Also, the `UltrasonicSensor` class is probably just for the EV3 Ultrasonic sensor, not the NXT one, so you probably need to use the generic `Sensor` class for that too.

* https://python-ev3dev.readthedocs.io/en/ev3dev-stretch/sensors.html#base-sensor
* http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-jessie/sensor_data.html#ht-nxt-smux
* http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-jessie/sensor_data.html#lego-nxt-us

**Comment by w1ref1re** [comment]
I declared the mux as a sensor, but if I tried to use the Ultrasonic sensor I got an 
`ev3dev2.DeviceNotFound: Sensor(in2:i2c8:mux1) is not connected` error.

Here is the code: 

`smux = Sensor(address="in2:i2c8")`
`smux.command = "HALT"`
`smux.command = "DETECT"`

`us = Sensor(address="in2:i2c8:mux1")`

**Comment by dlech** [comment]
Check the Device Browser on the EV3 to make sure you are using the correct `address`.

You should also check the state of `smux` to make sure it is actually running. And you will probably need a delay before creating the ultrasonic sensor device to allow the kernel some time to create the device node.

**Comment by w1ref1re** [comment]
The sensor is not shown up in the Device Browser, not even the as `nxt-analog` like the empty ports.
And when I check the values of `smux`I get:
`value(0) = 2`
`value(1) = 2`
So it has the Run State `Run` but the Status`halted`??

If I run `dmesg | tail` there are the lines
`[ 1277.145774] ht-nxt-smux-i2c-sensor: probe of ev3-ports:in2:i2c8:mux1:lego-nxt-us failed with error -12
[ 1277.146681] lego-port port12: Added new device 'ev3-ports:in2:i2c8:mux1:lego-nxt-us'
`

**Comment by dlech** [comment]
Good thinking to check `dmesg`. `-12` means `ENOMEM`. Looking at the driver code, it looks like we have a serious mistake. We are forgetting to allocate some memory for the sensor modes.

I've started https://github.com/ev3dev/ev3dev/issues/1210 to track the issue since this isn't a python problem. Further comments should be made there.
