### ISSUE TITLE
Release planning for v2.0.0-beta3

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev-lang-python#588]
We've been sitting on unreleased code for a long time, so I'd like to try to get another release out.

The associated milestone is [here](https://github.com/ev3dev/ev3dev-lang-python/milestone/6).

I think micropython support for buttons should be pushed back, as there isn't an obvious solution to that and I will need to do some more investigation. We should certainly have some basic docs for Micropython, but I would be OK with cutting corners on that for now in the interest of getting a release out.

Is there anything else that we should consider for this milestone? If there are no objections I intend to publish the release this weekend.

**Comment by WasabiFan** [comment]
I haven't gotten any objections here... I didn't finish my end-to-end testing over the weekend but I'll probably publish the release when I finish that up.

**Comment by dlech** [comment]
"Release early and release often" :smile:

**Comment by dlech** [comment]
I would like to make a new snapshot image soon. Anything I can do to help get this release out?

**Comment by WasabiFan** [comment]
Oof, I took on some new responsibilities recently and haven't even sat down at my desk in a week :grimacing: I need to just sit down and get the release out the door.

**Comment by WasabiFan** [comment]
I'm working on this now and will publish the new release tonight.

**Comment by WasabiFan** [comment]
@dlech I ran into an error while trying to publish the new release (via the release script) and I'm not sure what exactly it is saying. Do you have any suggestions?

```
...
Successfully signed dsc, buildinfo, changes files
Checking signature on .changes
gpg: /home/wasabifan/pbuilder-ev3dev/debian/stretch-amd64/python-ev3dev2_2.0.0~beta3_amd64.changes: Valid signature from 1CA78C2C5786C0E3
Checking signature on .dsc
gpg: /home/wasabifan/pbuilder-ev3dev/debian/stretch-amd64/python-ev3dev2_2.0.0~beta3.dsc: Valid signature from 1CA78C2C5786C0E3
Uploading to ev3dev-debian (via sftp to reprepro.ev3dev.org):
Enter passphrase for key '/home/wasabifan/.ssh/id_rsa':
  Uploading python-ev3dev2_2.0.0~beta3.dsc:
[Errno 2] No such file
E: Error uploading file.
wasabifan@kaelin-packaging-vm:~/ev3dev-lang-python$ find ~/ | grep beta3.dsc
/home/wasabifan/python-ev3dev2_2.0.0~beta3.dsc
/home/wasabifan/pbuilder-ev3dev/debian/stretch-amd64/python-ev3dev2_2.0.0~beta3.dsc
/home/wasabifan/pbuilder-ev3dev/debian/stretch-armel/python-ev3dev2_2.0.0~beta3.dsc
/home/wasabifan/pbuilder-ev3dev/raspbian/stretch-armhf/python-ev3dev2_2.0.0~beta3.dsc
```

**Comment by dlech** [comment]
Are you using the `./debian/release.sh` script? (I suspect not since I see an armel build that is not supposed to be there).

Are you using the broken dput version from Ubuntu 18.04?

**Comment by WasabiFan** [comment]
> Are you using the ./debian/release.sh script?

Yes. If there are additional build products it's because I have manually built them previously. Here I just ran `release.sh`.

> Are you using the broken dput version from Ubuntu 18.04?

In theory I downgraded it then `hold`ed it but I can check to make sure something didn't go wrong.

**Comment by dlech** [comment]
https://bugs.launchpad.net/ubuntu/+source/dput/+bug/1762567

Maybe need to adjust the `~/.dput.cf` file?

**Comment by WasabiFan** [comment]
Package has been uploaded and deployed to PyPi. Let me know if any issues are found.
