### ISSUE TITLE
LargeMotor(OUTPUT_A) cannot find motor

### ISSUE THREAD

**Issue by danioyuan** [ev3dev/ev3dev-lang-python#591]
```
- **ev3dev version:** 4.14.80-ev3dev-2.3.1-ev3
- **ev3dev-lang-python version:** 
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name             Version       Architecture  Description
+++-================-=============-=============-======================================
ii  python3-ev3dev   1.2.0         all           Python language bindings for ev3dev
ii  python3-ev3dev2  2.0.0~beta2   all           Python language bindings for ev3dev
```

Just had ev3dev + VC Code set up today. Able to run hello.py from https://github.com/ev3dev/vscode-hello-python successfully.

Now I'm just following the example here to run the following code:
```python
#!/usr/bin/env python3
from ev3dev2.motor import LargeMotor, OUTPUT_A, OUTPUT_B, SpeedPercent, MoveTank
from ev3dev2.sensor import INPUT_1
from ev3dev2.sensor.lego import TouchSensor
from ev3dev2.led import Leds

m = LargeMotor(OUTPUT_A)
m.on_for_rotations(SpeedPercent(75), 5)
```

The following error appears even I can see the motor on Input A on ev3 brick interface. I also tried to plug in all 4 inputs with large motors.

The error says:
```
Traceback (most recent call last):
  File "/Users/bingchen/Downloads/vscode-hello-python-master/single_motor.py", line 11, in <module>
    m = LargeMotor(OUTPUT_A)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ev3dev2/motor.py", line 1041, in __init__
    super(LargeMotor, self).__init__(address, name_pattern, name_exact, driver_name=['lego-ev3-l-motor', 'lego-nxt-motor'], **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ev3dev2/motor.py", line 316, in __init__
    super(Motor, self).__init__(self.SYSTEM_CLASS_NAME, name_pattern, name_exact, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ev3dev2/__init__.py", line 201, in __init__
    chain_exception(DeviceNotFound("%s is not connected." % self), None)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ev3dev2/__init__.py", line 38, in chain_exception
    raise exception from cause
ev3dev2.DeviceNotFound: LargeMotor(outA) is not connected.
```

There is also a minor warning saying:
Import warning: Failed to import "evdev". Button will be unusable!

**Comment by dlech** [comment]
You have to run the program on the EV3, you can't run it on your computer.

If you start a new project, make sure to copy the `.vscode` folder from https://github.com/ev3dev/vscode-hello-python or manually configure `launch.json`.

**Comment by danioyuan** [comment]
Thanks!

How do I know it is running on the ev3 or not? I didn't create a new
project. I made a new file under the same directory as hello.py, and then
right clicked the program and clicked "download and run". So I feel it was
running on ev3, isn't it?

**Comment by dlech** [comment]
> How do I know it is running on the ev3 or not?

I could tell by the path name in the error message `/Library/Frameworks/Python.framework/...`. It looks like you are using a Mac.

If you right-clicked something and it said, "download and run", it is not part of the ev3dev VS Code extension.

If you just added a file to the vscode-hello-python project, then you should be able to use the "Download and Run Current File" option in the debugger panel - assuming that the file you want to run is open in the text editor.

![selection_017](https://user-images.githubusercontent.com/963645/51849300-021fbb80-22e5-11e9-9053-bf5baab8300f.png)

**Comment by danioyuan** [comment]
It worked!

Sorry I was typing on my phone yesterday. What I clicked after right click
was "Run Python file in terminal", not "download and run". No wonder it
didn't work.

Is clicking "download and run current file" the only way? Are breakpoints
possible for programs running on EV3?

Thanks a lot for your help.

Best,

Yuan

**Comment by dlech** [comment]
Remote debugging is theoretically possible, but I had trouble getting it to work on the EV3 in the past. I haven't tried the latest version though. PTVSD is pre-installed in ev3dev. You can read more about how it is supposed to work in the docs for Microsoft's Python extension for VS Code.
