### ISSUE TITLE
VS Code Extension

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev-lang-python#592]
I made a new VS Code extension for ev3dev-lang-python

https://marketplace.visualstudio.com/items?itemName=ev3dev.ev3dev-lang-python

Basically, it helps you set up a new project folder and helps you get stuff installed to make code completion work.

**Comment by WasabiFan** [comment]
Nice! That's quite exciting; I'll have to try it out 😁

**Comment by dlech** [comment]
Well, I need to take this down temporarily (for reasons). Sorry for the inconvenience.
