### ISSUE TITLE
ev3dev2.sound.Sound.play_song converts notes to uppercase and breaks flats

### ISSUE THREAD

**Issue by lisjump** [ev3dev/ev3dev-lang-python#594]
- **ev3dev version:** 4.14.80-ev3dev-2.3.1-ev3
- **ev3dev-lang-python version:** ii  python3-ev3dev 1.2.0 

#!/usr/bin/env python3

from ev3dev2.sound import *

sound = Sound()
sound.play_song((
      ('Db4', 'e3'),      
    ))

will produce an error:

Traceback (most recent call last):
  File "./soundtest.py", line 7, in <module>
    ('Db4', 'e3'),      
  File "/usr/lib/python3/dist-packages/ev3dev2/sound.py", line 487, in play_song
    raise ValueError('invalid note (%s)' % e)
ValueError: invalid note ('DB4')

Sharps work, so I think this is because the b has been capitalized in self._NOTE_FREQUENCIES[note.upper()] and is different than the key error that happens when you have an actual invalid note.

**Comment by dlech** [comment]
GitHub lets you transfer issues now. So this issue is in the right place now.

**Comment by WasabiFan** [comment]
Oh, cool! I didn't know that. Thanks!
