### ISSUE TITLE
Add rest notes to sound.Sound.play_song()

### ISSUE THREAD

**Issue by lisjump** [ev3dev/ev3dev-lang-python#595]
It would be nice if sound.Sound.play_song() had rest notes as a possibility.  My student was looking through all sorts of music he wanted to make his robot play and to quote him, "All music has rests, well at least all good music."

It can be solved by breaking apart songs on the rest notes and adding a delay, but that is rather messy.

**Comment by dwalton76** [comment]
The only musical instrument I can play is a radio so you are speaking greek to me :) Would your student be interested in submitting a pull requests to add the rests to the Sound class?

**Comment by lisjump** [comment]
No, but I may be once I finish a current, time-sensitive project.

**Comment by mvolfik** [comment]
@lisjump or anyone else - is this some standard notation, and if so, which one?
If not, can I use "R" as a "note" for rest and state it in the docs?

**Comment by lisjump** [comment]
Yeah, I have no idea. Using R sounds great to me.  Thanks for taking it on,
I meant to and then life happened.
