### ISSUE TITLE
Using HiTechnic Sensor in Ev3-dev

### ISSUE THREAD

**Issue by PrabhathTangella** [ev3dev/ev3dev-lang-python#596]
I haven't been able to use HiTechnic compass sensor in ev3dev-stretch. When I run the code it keeps saying that it is not connected. 
#!/usr/bin/env python3
from ev3dev2.motor import *
from ev3dev2.sensor import *
import time
c = Sensor(adress=INPUT_1, name_pattern='ht-nxt-compass')
num = c.mode()

**Comment by WasabiFan** [comment]
Can you post the output of `ev3dev-sysinfo -m`?

Also, the output of `cat /sys/class/lego-sensor/*/driver_name`.

**Comment by WasabiFan** [comment]
Actually, should that be "driver_name" rather than "name_pattern" in your code?

**Comment by PrabhathTangella** [comment]
I will try this but I think the device is connected to the brick because when I go to the device browser I can see the device and read values.

**Comment by PrabhathTangella** [comment]
ht-nxt-compass: This is the output of the cat command. 


**System info (from `ev3dev-sysinfo`)**
```
Image file:         ev3dev-stretch-ev3-generic-2018-11-13
Kernel version:     4.14.80-ev3dev-2.3.1-ev3
Brickman:           0.10.0
BogoMIPS:           148.88
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=0016534A4864
BOARD_INFO_TYPE=main
```
 : This is the output of the system information command.

**Comment by WasabiFan** [comment]
Can you try replacing `name_pattern` with `driver_name` in your code?

**Comment by PrabhathTangella** [comment]
I did it still doesn't connect. I think it isn't connecting because the compass sensor is an I2C sensor

**Comment by PrabhathTangella** [comment]
from ev3dev2.sensor import *
c = Sensor(address=INPUT_1, driver_name='ht-nxt-compass')
debug_print(c.address)
value = c.value
debug_print(value)

ev3-ports:in1:i2c1
<bound method Sensor.value of Sensor(ev3-ports:in1)>

With driver name it worked but I couldn't read values out of the sensor.

**Comment by WasabiFan** [comment]
`value` is a function; you must call it. https://python-ev3dev.readthedocs.io/en/ev3dev-stretch/sensors.html#base-sensor

**Comment by dwalton76** [comment]
@PrabhathTangella can you change `value = c.value` to `value = c.value()`

**Comment by dwalton76** [comment]
Please re-open with requested information
