### ISSUE TITLE
ev3dev-2.3.1

### ISSUE THREAD

**Issue by lazenbyace** [ev3dev/ev3dev-lang-python#598]
- **ev3dev version:** PASTE THE OUTPUT OF `uname -r` HERE
- **ev3dev-lang-python version:** INSERT ALL VERSIONS GIVEN BY `dpkg-query -l python3-ev3dev*` HERE

**Comment by lazenbyace** [comment]
running version ev3dev-2.3.1 brickman v0.10.0
Using stretch image & VS Code

I have followed all of the tutorials that I could find, but I am still getting the ModuleNotFoundError when trying to import ev3dev2 such as:

from ev3dev2.motor import MoveTank, OUTPUT_B, OUTPUT_C 

results in Unable to import 'ev3dev2.motor'

Please advise. I've installed python 3. I've installed ev3dev2. I've created a virtual environment and tried running out of that in VS Code. We can't move forward with building our robots until we're able to resolve this fundamental error. 

We can successfully run Python programs on the brick that do not require importing from ev3dev2. 

Thank you.

**Comment by dlech** [comment]
Can you please give the exact steps to reproduce the problem?

**Comment by lazenbyace** [comment]
Thanks for responding. 

Our steps were first to follow videos 1-3 released by Nigel Ward for EV3 Python. This involved flashing the stretch image onto an SD card, installing VS Code, connecting to the brick, etc. - basically following steps from https://www.ev3dev.org/downloads/.  

The last few steps in video 3 download VSCODE-HELLO-PYTHON-MASTER folder. Following his videos, we modified the .json files and removed several files, leaving hello.py & motordemo.py. hello.py works fine while motordemo.py results in the error that ev3dev2 cannot be found.  The motordemo.py imports from ev3dev instead of ev3dev2, so I changed it to ev3dev2. This did not work. 

I went through this documentation: https://github.com/ev3dev/ev3dev-lang-python/commit/6af0b14145bc5ebc6ec516bc2127efc5ba191971

I then followed the steps in this documentation: https://github.com/ev3dev/vscode-hello-python with particular attention to the bottom where it instructs to create a virtual environment and install python-ev3dev2.

When I press PF5 to download and run the program motordemo.py, it returns the ModuleNotFoundError. 

If I didn't respond with the information that you need, please let me know and I'll do my best.

Thank you.

**Comment by dlech** [comment]
> When I press PF5 to download and run the program motordemo.py, it returns the ModuleNotFoundError.

This sounds like `.vscode/launch.json` is not setup correctly.

You probably have something like this for `hello.py`.

```jsonc
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Download and Run",
			"type": "ev3devBrowser",
			"request": "launch",
			"program": "/home/robot/${workspaceRootFolderName}/hello.py"
		}
	]
}
```

So you need to add a new entry for `motordemo.py`.

```jsonc
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Download and Run",
			"type": "ev3devBrowser",
			"request": "launch",
			"program": "/home/robot/${workspaceRootFolderName}/hello.py"
		},
		{
			"name": "Download and Run",
			"type": "ev3devBrowser",
			"request": "launch",
			"program": "/home/robot/${workspaceRootFolderName}/motordemo.py"
		}
	]
}
```

**Comment by lazenbyace** [comment]
I actually have it set up to run the relative program and it is trying to run it because I get the error on each import statement. 

```jsonc
"configurations": [
        {
            "name": "Download and Run Current File",
            "type": "ev3devBrowser",
            "request": "launch",
            "program": "/home/robot/${workspaceRootFolderName}/${relativeFile}"
        }
```

**Comment by bpmerkel** [comment]
@lazenbyace Indeed that works! It properly launches the current open file on the EV3.
