### ISSUE TITLE
BrickPi: DeviceNotFound at every first start of the program

### ISSUE THREAD

**Issue by Jawaisch** [ev3dev/ev3dev-lang-python#599]
========== ev3dev-sysinfo ==========
Image file:         ev3dev-stretch-rpi2-generic-2018-11-13
Kernel version:     4.14.94-ev3dev-2.3.2-rpi2
Brickman:           0.10.0
BogoMIPS:           38.40
Bluetooth:          
Board:              board0
BOARD_INFO_HW_REV=A02082
BOARD_INFO_MODEL=Raspberry Pi 3 Model B Rev 1.2
BOARD_INFO_TYPE=main
Board:              board1
BOARD_INFO_FW_VER=1.4.6
BOARD_INFO_HW_REV=3.2.1
BOARD_INFO_MODEL=Dexter Industries BrickPi3
BOARD_INFO_TYPE=aux

- **ev3dev-lang-python version: 
python3-ev3dev      1.2.0                                                  
python3-ev3dev2    2.0.0~beta3

```
#!/usr/bin/env python3
import ev3dev.auto as ev3
from ev3dev2.motor import Motor, MoveTank, OUTPUT_A, OUTPUT_B, OUTPUT_C
from ev3dev2.sensor import INPUT_1, INPUT_2, INPUT_3, INPUT_4
from ev3dev2.sensor.lego import TouchSensor
from ev3dev2.port import LegoPort

p4 = LegoPort(INPUT_4)
p4.mode = "nxt-analog"              
p4.set_device = "lego-nxt-touch"

p3 = LegoPort(INPUT_3)
p3.mode ="ev3-analog"
p3.set_device = "lego-ev3-touch"

ts_end  = TouchSensor(INPUT_3)
ts_ackn = TouchSensor(INPUT_4)
```

After each restart of the system, when I'm start the program from the command line, using: 
sudo python3
I get the following error.

```
Traceback (most recent call last):
  File "NotFound.py", line 16, in <module>
    ts_end  = TouchSensor(INPUT_3)
  File "/usr/lib/python3/dist-packages/ev3dev2/sensor/lego.py", line 49, in __init__
    super(TouchSensor, self).__init__(address, name_pattern, name_exact, driver_name=['lego-ev3-touch', 'lego-nxt-touch'], **kwargs)
  File "/usr/lib/python3/dist-packages/ev3dev2/sensor/__init__.py", line 94, in __init__
    super(Sensor, self).__init__(self.SYSTEM_CLASS_NAME, name_pattern, name_exact, **kwargs)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 210, in __init__
    chain_exception(DeviceNotFound("%s is not connected." % self), None)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 38, in chain_exception
    raise exception from cause
ev3dev2.DeviceNotFound: TouchSensor(spi0.1:S3) is not connected.
```

But if I start it again without any changes it runs without any problems.

**Comment by dlech** [comment]
Try adding a short delay after the last `set_device`.

    import time

    ...

    time.delay(0.5)

It takes some time for the device to be configured in the background. But after you run the program once, the device is already configured.

**Comment by Jawaisch** [comment]
That works.
Thanks for that and for all the great work you're doing here!

But I have one more question.
Any idea why the function 
`wait_until_not_moving()`
doesn't work on my BrickPi? They never returns, no matter how hard I hold the Motor.

**Comment by dwalton76** [comment]
@Jawaisch can you `cat` the file with the state of the motor when it is in this condtion so we can see what the motor state is at the time.

**Comment by dwalton76** [comment]
David has been hammering out some bugs recently in the brickpi3 motor driver:
- https://github.com/ev3dev/ev3dev/issues/1237
- https://github.com/ev3dev/ev3dev/issues/1248

The `wait_until_not_moving()` issue is probably due to 1248 (it is for me).
