### ISSUE TITLE
Bad link in Stretch documentation

### ISSUE THREAD

**Issue by ndward** [ev3dev/ev3dev-lang-python#602]
These sections
https://python-ev3dev.readthedocs.io/en/ev3dev-stretch/display.html#ev3dev2.display.Display.text_pixels
and
https://python-ev3dev.readthedocs.io/en/ev3dev-stretch/display.html#ev3dev2.display.Display.text_grid
include bad links to 
http://ev3dev-lang.readthedocs.io/projects/python-ev3dev/en/ev3dev-stretch/other.html#bitmap-fonts

**Comment by WasabiFan** [comment]
ReadTheDocs hadn't triggered a rebuild after #601 was merged... I just did it manually and it looks like the links are OK now.
