### ISSUE TITLE
Problems with on_to_position()

### ISSUE THREAD

**Issue by ndward** [ev3dev/ev3dev-lang-python#608]
Previously I had the impression that if on_to_position() is used to instruct a motor to turn to a position where it happens to already be located then this will freeze the program. I think that's been fixed, but I still have had lots of problems with the on_to_position() function, which often causes my scripts to freeze for other reasons. This is true for both the medium motor and the large motor and seems to be worse when one movement is immediately followed by another and when the speed setting is low (e.g. 30).

Here below is my test script. The script should cause the position to be printed 7 times, so if that is not the case it means the program froze. The position values are often not what one would expect - I suppose the motor has not yet settled. The position values are as expected when the sleep() statement is enabled.

This script measures the position before the move rather than after to highlight the fact that the position is zero each time the script is started, something that should be noted in the documentation. The exception is when the motor was disconnected and reconnected before the script was launched - that caused the position to appear as 9284 and caused the program to freeze while the motor span forever. Perhaps not forever - perhaps it was turning through 9274 degrees. A workaround for that problem is to specifically set the position to zero as the program starts, such as by enabling the corresponding command in the sample script.

```python
#!/usr/bin/env python3
from ev3dev2.motor import OUTPUT_B, MediumMotor, LargeMotor
from time import sleep
from sys import stderr

#motor = MediumMotor()
motor = LargeMotor(OUTPUT_B)

def goto(pos):
    print('motor.position = '+ str(motor.position), file = stderr)
    motor.on_to_position(speed=30, position=pos)
    #sleep(0.5)

#motor.position = 0
goto(10)
goto(20)
goto(-20)
goto(-30)
goto(-40)
goto(-50)
goto(-60)

Here are some results:
Medium motor run #1, speed = 30, sleep disabled
motor.position = -24
motor.position = 9

Medium motor run #2, speed = 30, sleep disabled
motor.position = 0
motor.position = 14

Medium motor run #3, speed = 30, sleep disabled
motor.position = 0
motor.position = 12

Medium motor run #4, speed = 50, sleep disabled
motor.position = 0
motor.position = 13
motor.position = 25
motor.position = -18
motor.position = -37
motor.position = -47
motor.position = -57

Large motor run #1, speed = 30, sleep disabled
motor.position = 0
motor.position = 14

Large motor run #2, speed = 30, sleep disabled
motor.position = 0
motor.position = 18
motor.position = 27
motor.position = -26
motor.position = -38
motor.position = -46
motor.position = -58

Large motor run #3, speed = 30, sleep disabled
motor.position = 0
motor.position = 12

Large motor run #4, speed = 30, sleep enabled
motor.position = 0
motor.position = 11
motor.position = 20
motor.position = -20
motor.position = -30
motor.position = -40
motor.position = -50

Large motor, after disconnecting and reconnecting, speed = 30, sleep enabled
(The motor ran forever)
motor.position = 9284
```

**System info (from `ev3dev-sysinfo`)**
```
Image file:         ev3dev-stretch-ev3-generic-2018-11-30
Kernel version:     4.14.80-ev3dev-2.3.1-ev3
Brickman:           0.10.0
BogoMIPS:           148.88
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=00165340377E
BOARD_INFO_TYPE=main
```

PS It often seems to be the case, as it is today Dec 7 2018, that the Stretch image proposed on ev3dev.org is not the latest one, as proposed on https://oss.jfrog.org/list/oss-snapshot-local/org/ev3dev/brickstrap/  Is there a reason why we would not want people to use the latest version?

**Comment by ndward** [comment]
I give the results of nine consecutive runs. In the first 4 runs the medium motor was never disconnected and the program froze for 3 of the four runs. Then I switched to a large motor. For the first four runs with the large motor I never disconnected it and the program froze in two of those four runs. Then I disconnected and reconnected the large motor, between the fourth and fifth runs with the large motor, just to see what would happen, and that exposed a new problem. So I think there are two problems:

- using this function often causes the program to freeze

- disconnecting and reconnecting the motor causes the position to not equal zero which is otherwise always the case when a script is launched. This problem is presumably not caused by the on_to_position() function since the problem occurs before the function is run and can be worked around in the way I indicated in my first message.

Can someone run the script and confirm that these problems exist? The freezing is not due to a faulty motor - I tried with two different medium motors and programs froze with both motors.

**Comment by dwalton76** [comment]
@ndward now that #583 is resolved can you check if this is still an issue?

**Comment by ndward** [comment]
I just ran this script using the April 8 image:
```
#!/usr/bin/env python3
from ev3dev2.motor import MediumMotor
from sys import stderr
from time import sleep

medium_motor = MediumMotor()

print(medium_motor.position, file= stderr)
for angle in (-10, 10, 19, 27, 33):
    medium_motor.on_to_position(speed=50, position=angle)
    sleep(0.5)
    print(medium_motor.position, file= stderr)
```
   
The script froze after printing out:
0
-10
10
19
27
In other words it can do the larger movements but can fail for small angles. In this case the 8 degree move worked but the 7 degree movement failed.
I ran again and got this printout
0
-10
10
19
So it could not manage the 8 degree turn from 19 to 27.

I conclude that this function on_to_position() can fail for turn angles less than about 10 degrees. This is much worse than i thought previously - I used to think that the freeze would only happen if the motor were instructed to move to its exact current position.

**Comment by WasabiFan** [comment]
@dwalton76 Do we need to re-open #583, or has the fix you tested not made it into a release yet? I believe we haven't released it yet. Perhaps we should do a release soon to package up these various fixes.

**Comment by dwalton76** [comment]
yeah it is probably worth doing a release soon.

**Comment by dwalton76** [comment]
@ndward can you test with the latest of ev3dev-lang-python and see how it behaves?
```
$ cd ~/
$ git clone https://github.com/ev3dev/ev3dev-lang-python.git
$ export PYTHONPATH=~/ev3dev-lang-python/
$ run-your-test-program.py
```

**Comment by ndward** [comment]
I'd like to do that but I seem unable to open a normal SSH session from VS
Code. I don't have the possibility of typing anything. I'm using  the April
8 image. I tried with two different EV3s. Maybe I need to use an older
image in order to be able to use SSH? I used to have no problems with SSH.

**Comment by WasabiFan** [comment]
@ndward hit enter a few times... there was a bug in VS Code on Windows a release or two ago.

**Comment by dwalton76** [comment]
@ndward is this still an issue or can we close?

**Comment by gabahr** [comment]
Hi,
I have to report that I recently had an issue with on_to_position() freezing my program. 
My original function looked like this:
`left_motor = LargeMotor(OUTPUT_D) def move_left(position):
left_motor.on_to_position(SPEED, position)`

**Comment by gabahr** [comment]
Hi,
I have to report that I had a problem with `on_to_position()` freezing. I have the speed set to 10 which is pretty low so I don’t know if that is the problem and I can’t set the speed to a higher number because the robot can’t move that fast.
 My original function looked like this:

```python
left_motor = LargeMotor(OUTPUT_D) 

def move_left(position): 
	left_motor.on_to_position(SPEED, position) 
```

And later I added a condition that prevented calling `on_to_position()` if it already is located in that position but that didn’t solve the freezing.
I looked at the implementation of `on_to_position()` and I think the problem is with calling `wait()` as it is described in the issue #583 .
I set the attribute block to False and implemented a function that waits until the motor is finished with the movement.

```python
def move_left(position): 
	if(left_motor.position == position): 
		return 	left_motor.on_to_position(SPEED, position, block=False) 
	wait_motor_stop(left_motor) 

def wait_motor_stop(motor): 	
	pos = motor.position 	
	sleep(1) 	
	while(motor.position != pos): 
		pos = motor.position 
```

This seems to solve the issue in my program. But I just wanted to let you know that the issue is still there.

**Comment by WasabiFan** [comment]
@gabahr Interesting...

You suggest the problem is similar to #583. What version of this library are you using? If it is `2.1.0`, it should include the fix mentioned there; if not, could you try upgrading?

Regarding the shown workaround, be aware that there may be odd behavior due to a) the timing of the `while` loop and b) the fact that "position" is read twice per iteration. You might want to check whether the motor position has changed over a given period of time instead.
