### ISSUE TITLE
How do I input some coordinate values into the lego ev3 brick so that the robot and return to the x, y position that was provided as an input to it

### ISSUE THREAD

**Issue by anzy0621** [ev3dev/ev3dev-lang-python#612]
How do I input some coordinate values into the lego ev3 brick so that the robot and return to the x, y position that was provided as an input to it

_Originally posted by @anzy0621 in https://github.com/ev3dev/ev3dev-lang-python/issues/194#issuecomment-478786646_

**Comment by WasabiFan** [comment]
Could you clarify what you're trying to do? Which coordinates are you referring to?

**Comment by anzy0621** [comment]
So if I have the lego robot starting at one starting point and it is following a prescribed path to reach its destination point. The condition is that if the bot goes out of the prescribed path then it is said to be lost and it has to take in (read) position values( probably x y coordinates of the starting point) to return back to the initial position. Is there a way we can input any value to the brickman?? Is there a read command of such?

**Comment by dwalton76** [comment]
We do not have a way to do this today but I should be able to add this as part of the Odometry #235 work.  I have the code done that tracks the robots (x, y) position in mm.  It should not be too difficult to add a basic `goto_x_y()` method to calculate how far to turn in place and then how far to go in a straight line.  That all assumes there is nothing blocking our path though...is this going to be useful? For scenarios like a FLL board there are going to be obstacles that need to be avoided.  We could always add support for that scenario later.

**Comment by dwalton76** [comment]
@anzy0621 this is in now in the MoveDifferential class, see https://github.com/ev3dev/ev3dev-lang-python/blob/ev3dev-stretch/ev3dev2/motor.py#L2064-L2077
```
        from ev3dev2.motor import OUTPUT_A, OUTPUT_B, MoveDifferential, SpeedRPM
        from ev3dev2.wheel import EV3Tire
        STUD_MM = 8
        # test with a robot that:
        # - uses the standard wheels known as EV3Tire
        # - wheels are 16 studs apart
        mdiff = MoveDifferential(OUTPUT_A, OUTPUT_B, EV3Tire, 16 * STUD_MM)

        # Enable odometry
        mdiff.odometry_start()

        # Use odometry to drive to specific coordinates
        mdiff.on_to_coordinates(SpeedRPM(40), 300, 300)

        # Use odometry to go back to where we started
        mdiff.on_to_coordinates(SpeedRPM(40), 0, 0)

        # Use odometry to rotate in place to 90 degrees
        mdiff.turn_to_angle(SpeedRPM(40), 90)

        # Disable odometry
        mdiff.odometry_stop()
```

**Comment by anzy0621** [comment]
wow, that is good news! Looking at this code it means now the robot can take values as coordinate values right? Assuming that whichever place the robot started is (0,0 ) So are the coordinates w.r.t. inches or mm or cm?

**Comment by WasabiFan** [comment]
They are millimeters.

**Comment by dwalton76** [comment]
yep it starts out at (0,0) and angle 90. The logic being if you drive straight forward the robot will be at a 90 degree angle from the x-axis.  Since you will be the first person using this please help us improve the docs in the `MoveDifferential` docstring.

You can use the `Distance` classes to use whatever unit of measure you want but in the end the coordinates are in millimeters.  This should drive the robot in a triangle 1-foot wide and 2-feet tall 
```
from ev3dev2.unit import DistanceFeet
mdiff.on_to_coordinates(SpeedRPM(40), DistanceFeet(1).mm, DistanceFeet(2).mm)
mdiff.on_to_coordinates(SpeedRPM(40), DistanceFeet(1).mm, 0)
mdiff.on_to_coordinates(SpeedRPM(40), 0, 0)
```

**Comment by anzy0621** [comment]
I keep running into this error, should I be downloading  ev3 stretch software again? because it says odometry class is not there in move differential
![thumbnail_image001](https://user-images.githubusercontent.com/37059022/56364548-cb0ec700-61bc-11e9-9bcb-ed8532e9ee3f.png)

**Comment by dwalton76** [comment]
You will need to install the latest ev3dev-lang-python from the repo.  ssh to your ev3 and then do:
```
$ cd /home/robot/
$ git clone https://github.com/ev3dev/ev3dev-lang-python.git
$ echo "export PYTHONPATH='/home/robot/ev3dev-lang-python'" >> ~/.bashrc
```

That might be all you need but I am not 100% sure if using visual studio will honor the PYTHONPATH environment variable.  If you still hit the error you can do:
```
$ cd ev3dev-lang-python
$ sudo python3 setup.py install
```

**Comment by dwalton76** [comment]
@anzy0621 any issues with the new odometry support or can we close this one?

**Comment by anzy0621** [comment]
No issues! It works perfectly fine! You can close this issue! And how can
help with the documentation

**Comment by dwalton76** [comment]
> No issues! It works perfectly fine! You can close this issue! And how can help with the documentation

If you can think of things to add to this section:
https://github.com/ev3dev/ev3dev-lang-python/blob/ev3dev-stretch/ev3dev2/motor.py#L2069-L2086

to make the odometry feature easier to use just submit a pull request with the changes.
