### ISSUE TITLE
Bluetooth communication between two EV3 blocks 

### ISSUE THREAD

**Issue by usmanov-danil** [ev3dev/ev3dev-lang-python#619]
How can I do communication between two blocks via bluetooth? Does exist something implemented  for it? Or I should write my own sh script?

**Comment by dwalton76** [comment]
We do not have support for it in our repo but there is another python repo that has implemented the EV3 protocol. It supports connecting via bluetooth https://github.com/ChristophGaukel/ev3-python3/blob/master/ev3.py#L283-L290

That would be a good example to follow.

**Comment by dwalton76** [comment]
See #677 and #699
