### ISSUE TITLE
'int' object has no attribute 'on_for_rotations'

### ISSUE THREAD

**Issue by lizisawizard** [ev3dev/ev3dev-lang-python#621]
I'm developed a function called 'turn' and it includes the 'on_for_rotations' function for the motors. I have it implemented in 2 different programs. It works in one, but not the other. The programs are nearly identical so I'm unsure of what is wrong. I keep getting the error 'int' object has no attribute 'on_for_rotations'.

Code:
```python
#!/usr/bin/env python3
from ev3dev2.motor import MoveTank, MediumMotor, OUTPUT_B,OUTPUT_C,OUTPUT_D   #we're importing the motor function
from time import sleep

a = MoveTank(OUTPUT_B,OUTPUT_C)
k = MediumMotor(OUTPUT_D)

def lift(direction):
    if(direction == 0):
        k.on_for_rotations(-80,8)
    else:
        k.on_for_rotations(80,8)


def move(dist):
    j = (0.0564*dist) + .0305
    a.on_for_rotations(20,20,.1,False)
    a.on_for_rotations(32,32,j-.05,brake=True)

def turn(direction = 1):
    if(direction == 1):
        a.on_for_rotations(-10,10,.91,True)
    elif(direction == 2):
        a.on_for_rotations(-10,10,.91,True)
    else:
        a.on_for_rotations(10,-10,(.91*2),True)
        
        
moves = [0,0,40,0,40,-73,73,-73,0,0]

for t in range(len(moves) - 2):
    a = moves[t]
    b = moves[t+2]
    if(b > a):
        turn(1)
        move(b-a)
    elif(a > b):
        turn(0)
        move(a-b)
    else:
        pass
```

It's supposed to just turn like usual. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Connection Type: USB
 - Other software: Visual Studios

**Robot (please complete the following information):**
 - Device: Ev3dev2 brickman
 - Versions: SD CARD 16 GB

**Comment by dlech** [comment]
It looks like you are using the variable `a` for two different things.

```python
a = MoveTank(OUTPUT_B,OUTPUT_C)
```

```python
    a = moves[t]
```

I would suggest giving your `MoveTank` variable a different name.

**Comment by lizisawizard** [comment]
Thank you!
