### ISSUE TITLE
need to delete old branches

### ISSUE THREAD

**Issue by dwalton76** [ev3dev/ev3dev-lang-python#623]
Is it safe to delete any of these?
* micropython - last updated 2 years ago by @ddemidov 
* support-micropython - last updated 2 years ago by @WasabiFan 
* brickpi-ev3dev-2.0.0 - merged, last updated 1 year ago by @dlech 
* ev3dev-stretch-1.x - last updated 9 months ago by @ddemidov

**Comment by ddemidov** [comment]
`ev3dev-stretch-1.x` is used as an active branch (that is, there is a documentation version for it) on readthedocs. Not sure if it is still needed though.

**Comment by WasabiFan** [comment]
`ev3dev-stretch-1.x` should stick around as a reference for the version of the 1.x library on Stretch. The Micropython ones are no longer needed. I can't recall the final state of the other branch, but my recollection was that we ported those changes into our main branches.

**Comment by dwalton76** [comment]
I deleted `micropython` and `support-micropython` but now I see a `micropython-support` branch that was not there a few days ago.  It says it was last updated 7 months ago by @WasabiFan ...is this one safe to delete too?

@WasabiFan something in your workflow is creating branches on the main repo (instead of your fork)...the `feature/initial-micropython-docs` and `feature/add-port-constant-docs` are two examples.

Do we need to keep `ev3dev-stretch-2.0.0-release-wip`?

**Comment by WasabiFan** [comment]
Yeah, I just branch and work in this repo rather than my fork. If that's annoying I can change it.

AFAIK no Micropython branches are needed anymore.

**Comment by dwalton76** [comment]
yeah I think it would be less confusing if you made them in your fork.

I deleted the other micropython library and `feature/add-port-constant-docs` (it had been merged already)

**Comment by dwalton76** [comment]
Ended up with

- `ev3dev-stretch`
- `ev3dev-stretch-1.x`
- `ev3dev-stretch-2.0.0-release-wip`
- `ev3dev-jessie`
- `feature/initital-micropython-docs` there is WIP PR open for this one so it will go away once that PR is wrapped up.

**Comment by ensonic** [comment]
Please keep ev3dev-stretch alive. While micropython sounds like a good idea, a transition for open roberta is beyond what I can do alone.
