### ISSUE TITLE
I need help with getting either the library to work or how to ping with the ultrasonic sensor and assign the result to a variable

### ISSUE THREAD

**Issue by TechMarauder** [ev3dev/ev3dev-lang-python#624]
I'm using the latest versions of ev3dev (2.3.1), ev3dev_browser (1.0.3), Python (2019.4.11881), and VSCode (1.33.1), however, this is the first time I've used VSCode, and cannot figure out how to get the library to work. Additionally, when trying to upgrade the library with this recommended code in the terminal
`sudoapt-get update
sudo apt-get install --only-upgrade python3-ev3dev` 
when entering the password as maker (which should be the default) it says it's incorrect.
I have tried for weeks to figure out formatting and the like and without much information and a library that I have no idea how to get to work or if it's even installed progress with programming the EV3 has been unbearably slow. If anyone could walk me through how to set up VSCode with the EV3Dev library, I would really appreciate it.

If this is not easy to do, then if someone could tell me how to assign the value of the result of pinging with the ultrasonic sensor to a variable so that I may store its value and access it later
that would solve my immediate problem.

Here is the program I am trying to get to work
```python
#!/usr/bin/env python3
"""
This script is a simple demonstration of the ultrasonic sensor and medium
motor.
"""
import ev3dev.ev3 as ev3
from ev3dev2.motor import (MoveSteering, MediumMotor, OUTPUT_A, OUTPUT_B, OUTPUT_C)
from ev3dev2.sensor.lego import UltrasonicSensor
from ev3dev2.sound import Sound
from time import sleep

motor_pair = MoveSteering(OUTPUT_B, OUTPUT_C)
medium_motor = MediumMotor(OUTPUT_A)
ultrasonic_sensor = UltrasonicSensor()
sound = Sound()

""" Here is where I'm trying to get it to ping distance and assign the result to a variable """

x = ultrasonic_sensor.distance_centimeters_ping()
sound.speak(x)

""" Start robot moving forward """

while True:
    motor_pair.on(steering=0, speed=40)

    """ Wait until robot less than 15cm from nearest front facing object """

    while ultrasonic_sensor.distance_centimeters > 15:
        sleep(0.01)

    """ Stop moving forward """
    motor_pair.off()

    """ Lower robot arm """
    medium_motor.on_for_degrees(speed=-100, degrees=120)
   
    sleep(.5)

    """ Raise robot arm """
    medium_motor.on_for_degrees(speed=50, degrees=120)

    """ Back up for 2 seconds """
    motor_pair.on_for_seconds(steering=0, speed=-20, seconds=2)
```

Also, I have no idea why the code formatting on git hub isn't applying to all of the code I inserted but that's not important.

**Comment by WasabiFan** [comment]
What's the error you're seeing or behavior you didn't expect? It's hard to know what's going wrong if we don't know what it  is doing.

I don't know why the default password isn't working; do other commands work? Paste the output of `ev3dev-sysinfo -m`. If you're running commands in the right place, perhaps you're accidentally pasting extra stuff into the password prompt.

**Comment by dwalton76** [comment]
Please re-open with requested info
