### ISSUE TITLE
Time To Launch slow?

### ISSUE THREAD

**Issue by MrGibbage** [ev3dev/ev3dev-lang-python#627]
ev3dev version: 4.14.96-ev3dev-2.3.2-ev3
ev3dev-lang-python version:
ii python3-ev3dev 1.2.0 all Python language bindings for ev3dev
ii python3-ev3dev2 2.0.0~beta3 all Python language bindings for ev3dev

I am evaluating ev3dev for potential use in FLL. One thing I have noticed so far is that it takes a long time for programs to launch once they are selected. Like on the order of ten to fifteen seconds or so. Unfortunately, that is unacceptable for FLL. But before I give up on ev3dev, I want to make sure I'm not doing something wrong, or that there isn't an easy way to make programs load and launch faster.

My test program is pretty simple, so I don't think it's a matter of that being the problem

```
#!/usr/bin/env python3
from ev3dev.ev3 import *
import os
os.system('setfont Lat15-TerminusBold14')
mL = LargeMotor('outB'); mL.stop_action = 'hold'
mR = LargeMotor('outC'); mR.stop_action = 'hold'
mL.run_to_rel_pos(position_sp= 840, speed_sp = 250)
mR.run_to_rel_pos(position_sp=-840, speed_sp = 250)
mL.wait_while('running')
mR.wait_while('running')
```

**Comment by dwalton76** [comment]
Try micropython it will load much faster

**Comment by MrGibbage** [comment]
That definitely sped things up a lot, but it is still taking five to seven seconds to launch.

```
#!/usr/bin/env micropython
#from ev3dev2 import *
from ev3dev2.motor import LargeMotor, OUTPUT_A, OUTPUT_B, SpeedPercent, MoveTank
from ev3dev2.sensor import INPUT_1
from ev3dev2.sensor.lego import TouchSensor
from ev3dev2.led import Leds
from ev3dev2.button import Button
import os
os.system('setfont Lat15-TerminusBold14')
mL = LargeMotor('outB'); mL.stop_action = 'hold'
mR = LargeMotor('outC'); mR.stop_action = 'hold'
#print('Hello, my name is EV3!')
#Sound.speak('Hello, my name is EV3!').wait()
mL.run_to_rel_pos(position_sp= 840, speed_sp = 250)
mR.run_to_rel_pos(position_sp=-840, speed_sp = 250)
mL.wait_while('running')
mR.wait_while('running')
```

**Comment by WasabiFan** [comment]
Yeah, this is a common issue; loading is pretty slow. The suggested approach would be to have your program wait for a button to be pressed before continuing; so you let it load beforehand and then tell it to go at the last minute. That being said, I think this library doesn't support buttons on Micropython yet (you can test to confirm) so you'd have to use the normal one (python3).

Alternately, there's now a distribution of ev3dev which is officially distributed through LEGO which uses a separate interface library which you can also try: see https://education.lego.com/en-us/support/mindstorms-ev3/python-for-ev3.

**Comment by dwalton76** [comment]
#571 for button support in micropython

**Comment by dwalton76** [comment]
We have micropython button support now so am going to close this one since there isn't much else for us to do.  The idea being for FLL scenario you would launch one program at the start and then use button pushes to move on to the next phase of the program instead of launching a new program each time and paying the startup time penalty multiple time.

@MrGibbage please let us know if you end up using ev3dev-lang-python for FLL.
