### ISSUE TITLE
Pixy Camera for LEGO non recognized by ev3dev2

### ISSUE THREAD

**Issue by Nercy99** [ev3dev/ev3dev-lang-python#640]
Hi, 
I am using the following version of ev3dev I downloaded last August: 
 
![image](https://user-images.githubusercontent.com/51016318/58368861-f63eb180-7ef2-11e9-896e-ca18174a8b23.png)

I wrote the following test program using ev3dev2. I also tried switching to ev3dev (line 2 in commentary) with the same result. 

![image](https://user-images.githubusercontent.com/51016318/58368872-1ec6ab80-7ef3-11e9-8ec8-9c9f94a43ea3.png)

I got the following bug message:  

![image](https://user-images.githubusercontent.com/51016318/58368886-5a617580-7ef3-11e9-8dc7-11df674f6d5a.png)

However, the Pixy camera for Lego is well connected to the 4th port of the EV3 LEGO Mindstorm brick and I did not have any problem during the training phase of the camera with PixyMon. 
There is no USB cable connected to the EV3 brick or the Pixy camera for LEGO. The EV3 brick is autonomous and not connected to my computer. That’s why I use sound to follow the execution of my program. 
I updated the EV3 brick with the latest version of the operating system and the camera works with the block diagram programming. 

 I also used a Pixy2 camera for LEGO and got the same bug with ev3dev. 

I am also going to try the latest version of ev3dev but I think I am missing a key step in my program to help ev3dev recognize the Pixy camera for LEGO: 
-	A parameter of the camera to evaluate with PixyMon, 
-	A different call in my programming to affect the Pixy camera for LEGO to the 4th port. 

I was wondering what were your thoughts on the matter. 

Thank you for your help.

**Comment by dwalton76** [comment]
I do not have one myself so don’t have much to add other than upgrading to the latest ev3dev sounds like a good first step.

**Comment by dlech** [comment]
Does the camera show up in the Device Browser on ev3dev? There is no support for the Pixy2 in ev3dev at this time (but you can probably use the Python SMBUS library to talk to it).

**Comment by Nercy99** [comment]
@dlech 
I am connected under the username robot and I don't know the root password. 

I don’t know how to browse the devices connected to the brick

Two large motors are connected to the B and C ports. A color sensor is connected to the 3rd port and the Pixy camera is connected to the 4th port. 
The led in front of the Pixy camera flashes after the connexion to the EV3 brick on the 4th port. 

![image](https://user-images.githubusercontent.com/51016318/58381700-a3cbc680-7fc0-11e9-903e-ecd38e6938c9.png)

I did not launch any Python program. 
The commands ls* available (for the username robot) are : 
ls
lsblk
lsinitramfs
lslocks
lsmod
lsusb
lsattr
lscpu
lsipc
lslogins
lsns

I am connected to the EV3 brick via SSH with a USB link. 
robot@ev3dev:~$ lsusb
Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

However, I could not launch the command lspci under the username robot. 
robot@ev3dev:~$ sudo lspci
[sudo] password for robot:
sudo: lspci: command not found

The lsblk and lsmod commands are not useful here: 

robot@ev3dev:~$ lsblk -a
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0         7:0    0        0 loop
loop1         7:1    0        0 loop
loop2         7:2    0        0 loop
loop3         7:3    0        0 loop
mmcblk0     179:0    0  7.4G  0 disk
|-mmcblk0p1 179:1    0   48M  0 part /boot/flash
`-mmcblk0p2 179:2    0  7.3G  0 part /
zram0       254:0    0   96M  0 disk [SWAP]

robot@ev3dev:~$ lsmod
Module                  Size  Used by
iptable_nat             1728  0
nf_conntrack_ipv4       5927  1
nf_defrag_ipv4          1634  1 nf_conntrack_ipv4
nf_nat_ipv4             5140  1 iptable_nat
nf_nat                 14692  1 nf_nat_ipv4
nf_conntrack           87388  3 nf_conntrack_ipv4,nf_nat_ipv4,nf_nat
libcrc32c               1100  2 nf_conntrack,nf_nat
usb_f_rndis            15528  2
usb_f_ecm               6278  2
u_ether                12402  2 usb_f_ecm,usb_f_rndis
ev3_uart_sensor_ld      7439  1
ev3_uart_sensor        13506  1 ev3_uart_sensor_ld
ev3_pru                 4044  1
virtio_rpmsg_bus        9194  0
rpmsg_core              7085  2 ev3_pru,virtio_rpmsg_bus
ti_pru_rproc            3036  0
remoteproc             21570  1 ti_pru_rproc
virtio                  7203  2 virtio_rpmsg_bus,remoteproc
virtio_ring            15777  2 virtio_rpmsg_bus,remoteproc
ti_pru_intc             4496  0
ti_pruss                1426  0
suart_emu              21593  0
nxt_i2c_sensor         35440  1 ev3_uart_sensor
servo_motor_class       6378  1 nxt_i2c_sensor
uinput                  8046  0
sunrpc                228280  1
libcomposite           41646  16 usb_f_ecm,usb_f_rndis
ip_tables              10235  1 iptable_nat
x_tables               19456  1 ip_tables

**Comment by dlech** [comment]
> I don’t know how to browse the devices connected to the brick

![image](https://user-images.githubusercontent.com/963645/58385512-28b1e280-7fb7-11e9-9639-382d6cc7ac70.png)

Select `Device Browser` and press the center button.

**Comment by Nercy99** [comment]
@dlech 
Thanks a lot. It was easier than I thought. 
![image](https://user-images.githubusercontent.com/51016318/58386405-b3b6cb00-7fff-11e9-9f3d-43226141dd18.png)

The port of the color sensor is correct: lego-ev3-color at ev3-ports:In3
The problem is that the port of the camera Pixy isn't  ev3-ports:In4 as expected but: 
pixy-lego at I2c-legoev36:I2cl

How to make it work?

**Comment by dlech** [comment]
I think you need to upgrade the kernel to fix the port name. (fixed in kernel version `...-ev3dev-2.3.0-...`)

**Comment by Nercy99** [comment]
I downloaded the latest ev3dev image file and the problem is solved.

Thanks a lot for your help.
