### ISSUE TITLE
Unable to find TouchSensor on PiStorms

### ISSUE THREAD

**Issue by RobinMarchart** [ev3dev/ev3dev-lang-python#643]
- ev3dev version:4.14.114-ev3dev-2.3.4-rpi2
- ev3dev-lang-python version:
  - python3-ev3dev            1.2.0
  - python3-ev3dev2           2.0.0~beta3

On PiStorms-v2 using ev3dev
I Tried using TouchSensor and got this Error:
```python
import ev3dev.pistorms as ev3
ev3.TouchSensor(ev3.INPUT_2).address
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 1664, in address
    self._address, value = self.get_attr_string(self._address, 'address')
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 226, in get_attr_string
    return self._get_attribute(attribute, name)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 202, in _get_attribute
    raise Exception("%s is not connected" % self)
Exception: Sensor(pistorms:BAS2) is not connected
```
I looked inside the sys filesystem and figured out that (touch) sensors are only shown if the mode is set to `ev3-analog` in `/sys/class/lego-port/port<n>/mode`.
after setting this value the sensor was shown in `/sys/class/lego-sensor` and the previous code worked.

This should propably be indicated in the docs or automatically be set.
 **when setting not connected  `/sys/class/lego-port/port<n>/mode` to  `ev3-analog` it seems to be shown as not pressed sensor**

**Comment by dlech** [comment]
Can you share your code?

Sensors are not automatically detected on PiStorms like they are on EV3, so you have to configure the mode of the port first.

**Comment by dlech** [comment]
@KWSmit might have some example code for PiStorms.

**Comment by KWSmit** [comment]
I think my tic-tac-toe is a good exemple, see repo https://github.com/KWSmit/KSmEV3TicTacToe--PiStorms-version-

**Comment by dwalton76** [comment]
Please re-open with the requested info
