### ISSUE TITLE
Cython support?

### ISSUE THREAD

**Issue by ghost** [ev3dev/ev3dev-lang-python#646]
Sorry I could not fill out the template. My robot is in school so I could not get the details.

I am using ev3dev stretch. Was just wondering if I could use the ev3dev-lang-python library with cython for added performance. 

I am aware that micropython is not supported for now so I am looking for alternatives to reduce startup time in testing.

**Comment by dwalton76** [comment]
We support micropython for everything except the Display class and text support for that is in the works. You should give it a try :)

**Comment by dwalton76** [comment]
Regarding the cython part of the question yes, that should be doable.
