### ISSUE TITLE
Restart a service on ev3dev2?

### ISSUE THREAD

**Issue by adrielgomes** [ev3dev/ev3dev-lang-python#652]
ev3-uart@ev3\x2dports:in1.service  loaded failed failed  LEGO MINDSTORMS EV3 UART Sensors
ev3-leds.service  loaded active exited  LEGO MINDSTORMS EV3 LEDs

I can restart the service: ev3-leds.service
But I can't restart or start the service: ev3-uart@ev3\x2dports:in1.service

I need your help, because every time I turn on blick-ev3 it boots with either sensor off or bluetoch off.

uname -r: 4.14.117-ev3dev-2.3.4-ev3

When an ev3dev2 initialization fails to identify a sensor or motor, how can I restart or start this service that failed using an SSH connection?

**Comment by dlech** [comment]
My first thought is that if you are seeing errors like this, there is something else wrong, like a bad SD card.

Also, make sure you run `sudo apt update && sudo apt upgrade` (when the EV3 is connected to the Internet) to get the latest fixes. There was a recent update that should fix the Bluetooth issue.

**Comment by adrielgomes** [comment]
Sorry, but there are no problems with SD card. I use 6 new SD cards. The updates are ok (07/29/2019). I would like to know how to restart or start modules that were not loaded during blink ev3 initialization using ssh. Has anyone ever done this?

**Comment by WasabiFan** [comment]
This repo is for the Python library. As your issue isn't with the Python library, it isn't appropriate here. If you still have an issue I suggest you open an issue at https://github.com/ev3dev/ev3dev/issues and include details about what you are trying to do and what isn't working.
