### ISSUE TITLE
Dropping the "beta" from v2.0

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev-lang-python#656]
If all goes as planned I'm going to be publishing `python-ev3dev2 2.0.0~beta4` tonight. It's been a while since we released the first `2.0.0-beta` release, and I think at this point we should consider dropping the `beta` tag and calling it "stable". Once we do that, we should be following semver and breaking changes would require incrementing the major version.

Thoughts/objections? For now I'm still following the `beta` progression but we can publish a non-beta release of the same bits later if we want.

**Comment by dwalton76** [comment]
+1 for dropping beta tag

**Comment by WasabiFan** [comment]
Done.
