### ISSUE TITLE
polarity('inversed') got error: 'str' object is not callable 

### ISSUE THREAD

**Issue by danioyuan** [ev3dev/ev3dev-lang-python#659]
- **ev3dev version:** 18.7.0
- **ev3dev-lang-python version:** 4.14.96-ev3dev-2.3.2-ev3

I'm trying to invert my medium motor but it got an error message.

Code:
#!/usr/bin/env python3
from ev3dev2.motor import (LargeMotor, MediumMotor,
                           OUTPUT_A, OUTPUT_B, OUTPUT_C, OUTPUT_D,
                           SpeedPercent, MoveTank, MoveSteering)
from ev3dev2.sensor import INPUT_1, INPUT_2, INPUT_3, INPUT_4
from ev3dev2.sensor.lego import ColorSensor

import string
from threading import Thread

left_motor = MediumMotor(OUTPUT_A)
right_motor = MediumMotor(OUTPUT_B)
left_motor.polarity(left_motor.POLARITY_INVERSED)

Error:
Traceback (most recent call last):
  File "/home/robot/getting_started/main.py", line 15, in <module>
    left_motor.polarity(left_motor.POLARITY_INVERSED)
TypeError: 'str' object is not callable
Exited with error code 1.

**Comment by ddemidov** [comment]
Could it be
```py
left_motor.polarity = left_motor.POLARITY_INVERSED
```
?

**Comment by danioyuan** [comment]
That's plausible. I'll have to test later today.

Thanks!

**Comment by danioyuan** [comment]
It works! Thanks!
left_motor.polarity = left_motor.POLARITY_INVERSED

I thought it's a function.

A separate issue is that, there doesn't seem to be a way to inverse one of the motors when using MoveTank.
