### ISSUE TITLE
Warning when importing sensor (sensor will be unusable)

### ISSUE THREAD

**Issue by bidaian** [ev3dev/ev3dev-lang-python#660]
System:

4.14.96-ev3dev-2.3.2-ev3

ii  python3-ev3dev     1.2.0          all            Python language bindings for ev3dev
ii  python3-ev3dev2    2.0.0~beta3    all            Python language bindings for ev3dev

Warning:

```
robot@ev3dev:~$ pybricks-micropython 
MicroPython v1.9.4 on 2019-03-26; linux version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> from ev3dev2.sensor.lego import ColorSensor
WARN:ev3dev2.button:Import warning: Failed to import "evdev". Button will be unusable!
>>> 
```

It happens for the other sensors as well.

**Comment by dlech** [comment]
`pybricks-micropython` is for https://education.lego.com/en-us/support/mindstorms-ev3/python-for-ev3

To use ev3dev-lang-python, just use regular `micropython`

Also, be sure to run it with `brickrun` if you want to use the display.

    brickrun -r -- micropython

**Comment by bidaian** [comment]
I did it manually, copying what Visual Code Studio was doing, just to better see the error. I happens with that tool and sd card image at the site right now.

But I checked the repository, upgraded to beta5 (both ev3dev2 and micropython) and now everything works (also the MoveTank "follow line" method, that does not seem to exist in beta3 and throws an exception).

So, unless it is important for this to work in beta3, I guess this can be closed.

**Comment by WasabiFan** [comment]
- Yes, as @dlech said you should use normal `micropython`. `pybricks-micropython` is for a different library.
- Button support under Micropython was [added in `beta4`/`beta5`](https://github.com/ev3dev/ev3dev-lang-python/blob/ev3dev-stretch/debian/changelog#L13), so you need at least that version for buttons to work (and for that warning to go away).
- In your case, you weren't using buttons, but our sensor code apparently imports the button code as a side-effect (it's used for the `InfraredSensor` remote). You could ignore that warning as long as you aren't using the IR sensor.
