### ISSUE TITLE
MoveTank.follow_line with inversed motor

### ISSUE THREAD

**Issue by danioyuan** [ev3dev/ev3dev-lang-python#661]
- **ev3dev version:** 18.7.0
- **ev3dev-lang-python version:** ev3dev-stretch-ev3-generic-2019-03-03.zip

I'm trying to use the MoveTank.follow_line() to follow line with pid method. But my robot has a inversed motor. Is there a way to set a motor to be inversed in MoveTank and thus making follow_line() workable?

Thanks!

**Comment by WasabiFan** [comment]
Even if polarity is set on one of the motors, I'm doubtful that calculations which rely on encoder feedback in our `MoveTank` code will handle it properly -- I expect the motors to spin out of control. That being said, try this and see if it works, being ready to stop your robot if it does something weird:

```python
my_move_tank.left_motor.polarity = LargeMotor.POLARITY_INVERSED
```

You can replace `left_motor` with `right_motor` if appropriate. Do this immediately after constructing your `MoveTank` object and before using it.

**Comment by danioyuan** [comment]
Thanks!

This line does work without error, and when I call my_move_tank.on_for_degrees(), it does apply the correct speed (meaning that I can now treat as if both motors are polarity normal).

However, my current ev3dev version doesn't have the follow_line() function. Not sure why since I just install the whole set up a few days ago. So I wrote my own pid follow line and it works okay.

Even if I had the follow_line() function, I would be curious how the Kp, Ki and Kd should be adjusted as now it becomes a black box.

**Comment by danioyuan** [comment]
How can I update my ev3dev to the latest version here so I can try the follow_line() function?

Thanks!

**Comment by WasabiFan** [comment]
Please see [our FAQ page](https://python-ev3dev.readthedocs.io/en/ev3dev-stretch/faq.html):

```
sudo apt-get update
sudo apt-get install --only-upgrade python3-ev3dev2 micropython-ev3dev2
```

**Comment by danioyuan** [comment]
Just updated to 2.0.0-beta5. Thanks!

**Comment by danioyuan** [comment]
Just tested MoveTank.follow_line with one motor inversed, and it worked!!!

To summarize, here is how:
my_move_tank.left_motor.polarity = LargeMotor.POLARITY_INVERSED
my_move_tank.follow_line(...)
