### ISSUE TITLE
Importing pygame onto ev3dev

### ISSUE THREAD

**Issue by DigitalRookie4** [ev3dev/ev3dev-lang-python#663]
I am trying to use a joystick to control my robot. I have made all the code, and it is loaded onto the robot, I have downloaded some kind of pygame snippet onto my robot and in the code on visual studio there is not error saying unable to import pygame.base, but when I run the file in the robot either via the robot itself or visual studio it just gives off the error saying unable to import pygame.base. I have put the whole pygame folder into the folder that the program is in and downloaded that onto the robot. The robot has said it downloaded it but it appear to still be saying that it is unable to import pygame.base

**Comment by dlech** [comment]
There is not a python3 version of pygame for ev3dev-stretch, so you will have to compile it yourself or wait for ev3dev-buster.

A better option in any case would probably be to use the evdev (not to be confused with ev3dev) interface for joystick input events. https://python-evdev.readthedocs.io/en/latest/

It will load much faster than pygame. And if you want to go really light weight, you can skip the evdev library and read raw input events from `/dev/input/...` directly.

**Comment by DigitalRookie4** [comment]
I am trying to but I am unable to install pip onto my computer I have tried the normal way but that did not work

**Comment by dwalton76** [comment]
I use a USB NES controller to control brickman, this uses the `evdev` library David mentioned above
https://github.com/dwalton76/ev3dev-brickman-gamepad

**Comment by WasabiFan** [comment]
> I am trying to but I am unable to install pip onto my computer I have tried the normal way but that did not work

Why do you need to install pip on your computer? You only need the software on the robot.

**Comment by DigitalRookie4** [comment]
@WasabiFan Actually that is not related to this problem sorry. I got mixed up

**Comment by DigitalRookie4** [comment]
@WasabiFan  Because pip is the only tool that can install evdev (NOT ev3dev)

**Comment by DigitalRookie4** [comment]
@dwalton76  That could work, but my plan that I want to stick to is using a wired PS1 remote

**Comment by WasabiFan** [comment]
@DigitalRookie4 but you don't need any extra software on your computer, unless you intend to have the remote connected to your computer. If the remote is connected to the EV3 directly, you only need to install software on the EV3.

**Comment by dlech** [comment]
evdev is already installed on the EV3 by default :smile:

**Comment by DigitalRookie4** [comment]
@dlech  cheers for letting me know. I have been coding for about 3 years now and I am only 15 so I am not fully advanced but thanks anyway! :)

**Comment by DigitalRookie4** [comment]
@WasabiFan  the remote is going to be connected up to my PC (its a PS1 remote)

**Comment by WasabiFan** [comment]
Ah, OK; do you know how you plan to communicate between your PC and your EV3? You'll need some sort of a connection (Wi-Fi, bluetooth, USB, etc.) so that your PC can forward the joystick input to your EV3.

If the remote is wireless anyway, it's probably easier to connect it directly to the EV3. Otherwise you need to implement the relay code yourself to get the joystick input to the robot.

**Comment by DigitalRookie4** [comment]
@WasabiFan   Ah. I have not thought that out yet. Do you possibly have any suggestions on what I can possibly do

**Comment by DigitalRookie4** [comment]
@dlech  @dwalton76 @WasabiFan  I have a huge error while trying to do `pip install evdev` and comes up with this HUGE error:

`Collecting evdev
  Using cached https://files.pythonhosted.org/packages/fe/6e/3fa84a43571dec4d00dc26befccc9867b6b3263651531cbc1345f718860f/evdev-1.2.0.tar.gz
Building wheels for collected packages: evdev
  Building wheel for evdev (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\user\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-kxmk534a\\evdev\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-kxmk534a\\evdev\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\User\AppData\Local\Temp\pip-wheel-tin_dbn1' --python-tag cp37
       cwd: C:\Users\User\AppData\Local\Temp\pip-install-kxmk534a\evdev\
  Complete output (37 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.7
  creating build\lib.win32-3.7\evdev
  copying evdev\device.py -> build\lib.win32-3.7\evdev
  copying evdev\ecodes.py -> build\lib.win32-3.7\evdev
  copying evdev\eventio.py -> build\lib.win32-3.7\evdev
  copying evdev\eventio_async.py -> build\lib.win32-3.7\evdev
  copying evdev\events.py -> build\lib.win32-3.7\evdev
  copying evdev\evtest.py -> build\lib.win32-3.7\evdev
  copying evdev\ff.py -> build\lib.win32-3.7\evdev
  copying evdev\genecodes.py -> build\lib.win32-3.7\evdev
  copying evdev\uinput.py -> build\lib.win32-3.7\evdev
  copying evdev\util.py -> build\lib.win32-3.7\evdev
  copying evdev\__init__.py -> build\lib.win32-3.7\evdev
  running build_ext
  running build_ecodes
  The 'linux/input.h' and 'linux/input-event-codes.h' include files
  are missing. You will have to install the kernel header files in
  order to continue:

      yum install kernel-headers-$(uname -r)
      apt-get install linux-headers-$(uname -r)
      emerge sys-kernel/linux-headers
      pacman -S kernel-headers

  In case they are installed in a non-standard location, you may use
  the '--evdev-headers' option to specify one or more colon-separated
  paths. For example:

      python setup.py \
        build \
        build_ecodes --evdev-headers path/input.h:path/input-event-codes.h \
        build_ext --include-dirs  path/ \
        install
  ----------------------------------------
  ERROR: Failed building wheel for evdev
  Running setup.py clean for evdev
Failed to build evdev
Installing collected packages: evdev
  Running setup.py install for evdev ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-kxmk534a\\evdev\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-kxmk534a\\evdev\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-9i0rbs7f\install-record.txt' --single-version-externally-managed --compile --user --prefix=
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-kxmk534a\evdev\
    Complete output (37 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\evdev
    copying evdev\device.py -> build\lib.win32-3.7\evdev
    copying evdev\ecodes.py -> build\lib.win32-3.7\evdev
    copying evdev\eventio.py -> build\lib.win32-3.7\evdev
    copying evdev\eventio_async.py -> build\lib.win32-3.7\evdev
    copying evdev\events.py -> build\lib.win32-3.7\evdev
    copying evdev\evtest.py -> build\lib.win32-3.7\evdev
    copying evdev\ff.py -> build\lib.win32-3.7\evdev
    copying evdev\genecodes.py -> build\lib.win32-3.7\evdev
    copying evdev\uinput.py -> build\lib.win32-3.7\evdev
    copying evdev\util.py -> build\lib.win32-3.7\evdev
    copying evdev\__init__.py -> build\lib.win32-3.7\evdev
    running build_ext
    running build_ecodes
    The 'linux/input.h' and 'linux/input-event-codes.h' include files
    are missing. You will have to install the kernel header files in
    order to continue:

        yum install kernel-headers-$(uname -r)
        apt-get install linux-headers-$(uname -r)
        emerge sys-kernel/linux-headers
        pacman -S kernel-headers

    In case they are installed in a non-standard location, you may use
    the '--evdev-headers' option to specify one or more colon-separated
    paths. For example:

        python setup.py \
          build \
          build_ecodes --evdev-headers path/input.h:path/input-event-codes.h \
          build_ext --include-dirs  path/ \
          install
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\user\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-kxmk534a\\evdev\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-kxmk534a\\evdev\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-9i0rbs7f\install-record.txt' --single-version-externally-managed --compile --user --prefix= Check the logs for full command output`

**Comment by DigitalRookie4** [comment]
Sorry it didn't come out in the correct format it was being all akward

**Comment by dlech** [comment]
evdev only works on Linux, so doubt that it is possible to install it on Windows.

**Comment by DigitalRookie4** [comment]
@dlech  Does it work on python3.7 (because thats what python I use normally)

**Comment by DigitalRookie4** [comment]
@dlech  Is there a way you can install evdev onto my windows computer (I have got a debian terminal and a ubuntu terminal and a kali virtual machine)

**Comment by dlech** [comment]
Why do you need it on you computer? Code completion?

**Comment by dlech** [comment]
Oh, right, you are connecting your PS1 controller to your computer. In that case, why not install pygame on your computer? My earlier advice was under the assumption that pygame would be running on the EV3, not on you computer.

**Comment by DigitalRookie4** [comment]
@dlech  I just felt like it would have helped. But the problem that I am thinking about is that my computer would have to send the joystick signals somehow to the robot. I mean there is a wifi dongle attached to the robot's USB slot. Also the other problem that I am seeing is that when I execute the python file on the robot it would come up saying `no module named pygame`

**Comment by DigitalRookie4** [comment]
@dlech  I do have pygame installed on my computer and I have just now tried running pygame on the computer and running the python file via the robot and it has still given off the erro `no module named 'pygame'`

**Comment by DigitalRookie4** [comment]
@dlech  My **ORIGINAL** idea was to put the pygame folder all onto the ev3.  I do have pygame installed on my computer. I have just now tried running the pygame module on the computer and running the python file via the robot (with no pygame folder on the ev3 robot) and it has still given off the error `no module named 'pygame'` on the robot

**Comment by DigitalRookie4** [comment]
@dlech  @dwalton76 @WasabiFan  Do any of you have a possible suggestion on what I might be able to do :)

**Comment by DigitalRookie4** [comment]
@dlech  One thing I forgot to mention a while ago is that I am using the micropython software because I am only 14 and it is quite easy to understand

**Comment by DigitalRookie4** [comment]
@dlech  @dwalton76 @WasabiFan  Something tells me that pygame is able to work on the robot because it is only these modules which are not being found:

`from pygame.base import *
from pygame.constants import *
from pygame.version import *
from pygame.rect import Rect
from pygame.compat import geterror, PY_MAJOR_VERSION
from pygame.rwobject import encode_string, encode_file_path
import pygame.surflock
import pygame.color
Color = color.Color
import pygame.bufferproxy
BufferProxy = bufferproxy.BufferProxy
import pygame.math`

All the code above that is working successfully obviously and in __init__.py where the error is coming from there is some code which is successfully working above the code with errors. So this does explain something that pygame is able to work. But the other issue is that how do I fix the `no module named pygame` error. Sorry about the indentation (python and github were being awkward about it).

**Comment by dwalton76** [comment]
> @dlech @dwalton76 @WasabiFan Do any of you have a possible suggestion on what I might be able to do :)

Can you give a quick summary of what your end goal is?  I take it you want to connect a PS1 controller to your laptop and have the data from the controller passed along to your EV3?  Is the ultimate goal just to use a game controller to control the EV3?  If so I would take the laptop out of the picture and just connect your controller to the EV3 via bluetooth or usb.

**Comment by DigitalRookie4** [comment]
@dwalton76  Sorry. What I want to do is is make my ev3 robot be able to be controlled via my ps1 remote that is connected to my computer. I am trying to make the ps1 remotes signal's go into my computer and then get sent to my ev3. But yeah what you have basically said is what my target is to do with the ev3 and the remote. But the issue with that would be that I would just have a ps1 remote stuck in my ev3 and when I would execute my code it would not work because it would not show the error but there would be `no module named pygame.base`  because originally I ran the python file (that was on the robot) using my computer and it showed the error up on my screen.

**Comment by dwalton76** [comment]
> But yeah what you have basically said is what my target is to do with the ev3 and the remote
Now we are getting somewhere :)  So your goal is to remotely control the ev3 and you have a PS1 controller.  Do you have any other gaming controllers that support bluetooth?  Or do you have a smart phone or tablet?  If so you could do this:
https://www.youtube.com/watch?v=x5VauXr7W4A

That is on ev3dev but is using python3 instead of micropython.  I imagine you could get it going via micropython with some work though.

> But the issue with that would be that I would just have a ps1 remote stuck in my ev3 and when I would execute my code it would not work because it would not show the error but there would be `no module named pygame.base` because originally I ran the python file (that was on the robot) using my computer and it showed the error up on my screen.

That is just a matter of having your program running on the ev3 log output to a logfile. You then copy the logfile off the ev3 to your laptop to view the errors.

**Comment by DigitalRookie4** [comment]
@dwalton76 I have just used the logfile and it has shown my the exact same error as it did before:
`Traceback (most recent call last):
  File "/home/robot/drive/main.py", line 10, in <module>
  File "/home/robot/drive/pygame/__init__.py", line 136, in <module>
ImportError: no module named 'pygame.base'`

**Comment by dwalton76** [comment]
Forget pygame for now...is controlling your robot via a smartphone or tablet acceptable?

**Comment by DigitalRookie4** [comment]
@dwalton76  Yes. I do have a device that I could use and a wii remote which I am quite sure can connect via bluetooth.

**Comment by dwalton76** [comment]
ok lets start with the easiest way to get this up and running.  

- You could use your smartphone to control your robot, there is an example [here](https://github.com/ev3dev/ev3dev-lang-python-demo/blob/stretch/robots/EV3D4/EV3D4WebControl.py).  This is using python3 though not micropython.

- If you want to use micropython you will need to port [this code](https://github.com/ev3dev/ev3dev-lang-python/blob/ev3dev-stretch/ev3dev2/control/webserver.py) to be compatible with micropython.  If you decide to do that let me know and I will assign you https://github.com/ev3dev/ev3dev-lang-python/issues/638. We are always looking for more contributors so you are more than welcome to run with this.

- You could use your wiimote to control your robot via bluetooth.  I haven't done this myself but from googling several folks have. https://www.ev3dev.org/projects/2014/12/13/Wiimote-Controlled-Rover/ and https://www.ev3dev.org/projects/2017/02/05/ROS-and-wiimote/  

To me all of these are much simpler/cleaner than using your laptop with pygame as a middleman.

**Comment by DigitalRookie4** [comment]
@dwalton76  I will give this a go but first I need to recharge my robot's batteries. I will get back to you once I have charged the batteries and tried what you have said

**Comment by DigitalRookie4** [comment]
@dwalton76  WAIT!......... I am only 15 and I have got GCSE exams coming up. I mean I will take it into consideration. But I want to ask what is "#638".  I do not really know how to "port" code. 

- I am only trying to do this because I have a PS1 remote I am quite experienced with python and I have a Lego ev3 robot. I have never converted software before (even in python)! I usually only make games with pygame!

**Comment by dwalton76** [comment]
By port I just mean take code that currently runs on python3 and make it run on micropython.

**Comment by DigitalRookie4** [comment]
@dwalton76  I have tried installing cwiid onto my computer and by using `sudo apt-get install python-cwiid`. which appears to come from debian I installed it on my computer's debian terminal that I downloaded. It successfully downloaded it but when I put `import cwiid` into python 3 on my computer it gave off the error ` No module named 'cwiid'`. Then I tried using `pip install cwiid` on my command prompt and this **MASSIVE** error came up:

`Collecting cwiid
  Using cached https://files.pythonhosted.org/packages/fa/e8/d0f03c60bbdc583a7fa37a126e9b20055fb3752861820c25bd212dc62756/cwiid-3.0.0.tar.gz
Building wheels for collected packages: cwiid
  Building wheel for cwiid (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\user\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-5u62qkij\\cwiid\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-5u62qkij\\cwiid\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\User\AppData\Local\Temp\pip-wheel-wyh6vuju' --python-tag cp37
       cwd: C:\Users\User\AppData\Local\Temp\pip-install-5u62qkij\cwiid\
  Complete output (5 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'cwiid' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for cwiid
  Running setup.py clean for cwiid
Failed to build cwiid
Installing collected packages: cwiid
  Running setup.py install for cwiid ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-5u62qkij\\cwiid\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-5u62qkij\\cwiid\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-blsu2x3j\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-5u62qkij\cwiid\
    Complete output (5 lines):
    running install
    running build
    running build_ext
    building 'cwiid' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\user\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-5u62qkij\\cwiid\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-5u62qkij\\cwiid\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-blsu2x3j\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
WARNING: You are using pip version 19.2.2, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.`

**Comment by DigitalRookie4** [comment]
Collecting cwiid Using cached https://files.pythonhosted.org/packages/fa/e8/d0f03c60bbdc583a7fa37a126e9b20055fb3752861820c25bd212dc62756/cwiid-3.0.0.tar.gz Building wheels for collected packages: cwiid Building wheel for cwiid (setup.py) ... error ERROR: Command errored out with exit status 1: command: 'c:\users\user\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\User\AppData\Local\Temp\pip-install-5u62qkij\cwiid\setup.py'"'"'; file='"'"'C:\Users\User\AppData\Local\Temp\pip-install-5u62qkij\cwiid\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\User\AppData\Local\Temp\pip-wheel-wyh6vuju' --python-tag cp37 cwd: C:\Users\User\AppData\Local\Temp\pip-install-5u62qkij\cwiid Complete output (5 lines): running bdist_wheel running build running build_ext building 'cwiid' extension error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/ ERROR: Failed building wheel for cwiid Running setup.py clean for cwiid Failed to build cwiid Installing collected packages: cwiid Running setup.py install for cwiid ... error ERROR: Command errored out with exit status 1: command: 'c:\users\user\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\User\AppData\Local\Temp\pip-install-5u62qkij\cwiid\setup.py'"'"'; file='"'"'C:\Users\User\AppData\Local\Temp\pip-install-5u62qkij\cwiid\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-blsu2x3j\install-record.txt' --single-version-externally-managed --compile cwd: C:\Users\User\AppData\Local\Temp\pip-install-5u62qkij\cwiid Complete output (5 lines): running install running build running build_ext building 'cwiid' extension error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/ ERROR: Command errored out with exit status 1: 'c:\users\user\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\User\AppData\Local\Temp\pip-install-5u62qkij\cwiid\setup.py'"'"'; file='"'"'C:\Users\User\AppData\Local\Temp\pip-install-5u62qkij\cwiid\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-blsu2x3j\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output. WARNING: You are using pip version 19.2.2, however version 19.2.3 is available. You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by DigitalRookie4** [comment]
@dwalton76 I have tried installing cwiid onto my computer and by using sudo apt-get install python-cwiid. which appears to come from debian I installed it on my computer's debian terminal that I downloaded. It successfully downloaded it but when I put import cwiid into python 3 on my computer it gave off the error No module named 'cwiid'. Then I tried using pip install cwiid on my command prompt and this MASSIVE error came up: (sorry about the format it is due to the ->""" <- . I think they sort of glitched by what format github thinks three speech marks is):

```
Collecting cwiid Using cached https://files.pythonhosted.org/packages/fa/e8/d0f03c60bbdc583a7fa37a126e9b20055fb3752861820c25bd212dc62756/cwiid-3.0.0.tar.gz Building wheels for collected packages: cwiid Building wheel for cwiid (setup.py) ... error ERROR: Command errored out with exit status 1: command: 'c:\users\user\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\User\AppData\Local\Temp\pip-install-5u62qkij\cwiid\setup.py'"'"'; file='"'"'C:\Users\User\AppData\Local\Temp\pip-install-5u62qkij\cwiid\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\User\AppData\Local\Temp\pip-wheel-wyh6vuju' --python-tag cp37 cwd: C:\Users\User\AppData\Local\Temp\pip-install-5u62qkij\cwiid Complete output (5 lines): running bdist_wheel running build running build_ext building 'cwiid' extension error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/ ERROR: Failed building wheel for cwiid Running setup.py clean for cwiid Failed to build cwiid Installing collected packages: cwiid Running setup.py install for cwiid ... error ERROR: Command errored out with exit status 1: command: 'c:\users\user\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\User\AppData\Local\Temp\pip-install-5u62qkij\cwiid\setup.py'"'"'; file='"'"'C:\Users\User\AppData\Local\Temp\pip-install-5u62qkij\cwiid\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-blsu2x3j\install-record.txt' --single-version-externally-managed --compile cwd: C:\Users\User\AppData\Local\Temp\pip-install-5u62qkij\cwiid Complete output (5 lines): running install running build running build_ext building 'cwiid' extension error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/ ERROR: Command errored out with exit status 1: 'c:\users\user\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\User\AppData\Local\Temp\pip-install-5u62qkij\cwiid\setup.py'"'"'; file='"'"'C:\Users\User\AppData\Local\Temp\pip-install-5u62qkij\cwiid\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-blsu2x3j\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output. WARNING: You are using pip version 19.2.2, however version 19.2.3 is available. You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by DigitalRookie4** [comment]
@dwalton76  I also have trouble connecting up to the wiimote and I keep getting access denied

**Comment by bru02** [comment]
> I have tried installing cwiid onto my computer

Why do you want to install cwiid on your computer?

Btw, the solution is literally in your error:

> Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

**Comment by DigitalRookie4** [comment]
@bru02. I was trying to see that if it could install on my computer as well to see if I was getting a similar error to what the robots error was.  You don't fully understand. What I have being trying to do above is by using SSH to access the robot's terminal I have tried installing `pip3 install cwiid` (pip itself does not work) and I get a massive error. I cannot currently do it because I am busy and I have got GCSEs coming up so I will try to get back to you as soon as possible :).

**Comment by DigitalRookie4** [comment]
> (Btw, the solution is literally in your error:

> Microsoft` Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": `https://visualstudio.microsoft.com/downloads/)`

But I already have visual studio 2017 installed!

**Comment by DigitalRookie4** [comment]
@dlech @dwalton76 @WasabiFan @bru02 Has anybody got any suggestions from my comments above on what I can do

**Comment by dlech** [comment]
It seems like your goal keeps changing, so I'm not sure what the goal is any more.

If the goal is still to use the PS1 controller, the first thing I would do is write a game, just for a regular computer, that uses the PS1 controller so that I could understand how that controller works by itself. Then I would write or copy and change a program that remotely controls the EV3, without using the PS1 controller, just so I could understand how that works by itself. Then I would try to put the two ideas together one I understood them.

**Comment by DigitalRookie4** [comment]
@dlech Sorry I have not been on for a while (I have been revising for exams). Also sorry for confusing you. I sometimes accidentally don't make myself always clear (sorry). I have made a game with my PS1 remote with pygame ages ago on my PC and it did work. I also do understand the concept of how the joystick controller works. When the joystick it up the y axis is negative and when the joystick is down the y axis is positive. When the joystick is right the x axis is positive and when the joystick is left the x axis is negative.  There are also buttons on the controller which are controlled by pressing and releasing them and each button has a place in an array to make them different. I am using the same code as I use for pygame on my PC as I am on my robots program. The other issue is that other people are suggesting to me to possibly use controllers such as the wiimote (which I have got). To be honest I am not sure which is best. Which do you think is best. The reason I typically got rid of the idea of the pygame joystick was because the pygame kept giving off an impossible to fix error inside the robot.

**Comment by DigitalRookie4** [comment]
@dlech @dwalton76 @WasabiFan  Another thing I forgot to mention is that I am using micropython which is built on ev3dev

**Comment by dwalton76** [comment]
@DigitalRookie4 how are things going with using the PS1 controller?
