### ISSUE TITLE
How to determine PID parameters?

### ISSUE THREAD

**Issue by danioyuan** [ev3dev/ev3dev-lang-python#664]
- **ev3dev version:** 2.0.0-beta5
- **ev3dev-lang-python version:** 2.0.0-beta5

Finally I got MoveTank.follow_line() working with an inversed motor. However, the default values of the PID parameters are quite large. It also gives error message of "the speed of the robot is too high to follow line". Isn't the whole purpose of using PID is to follow line accurately with high speed?

So my question is, is it possible to provide a guideline of how to choose the right PID parameters?

Thanks!

**Comment by dwalton76** [comment]
The ideal PID values for one robot may be very different from another robot.  You can use this to try to select better PID values for your particular robot:
https://github.com/ev3dev/ev3dev-lang-python/blob/ev3dev-stretch/utils/line-follower-find-kp-ki-kd.py

**Comment by WasabiFan** [comment]
You'll have to change the motors and polarity here: https://github.com/ev3dev/ev3dev-lang-python/blob/48fbd29fd06c69f57e88efcf59955ea49bcc7ace/utils/line-follower-find-kp-ki-kd.py#L109

**Comment by danioyuan** [comment]
Just tried this. The program worked, but it's not consistent. Each time I run it, it can get very different result. So far, my best PID result is to write it myself using a loop that keeps changing MoveTank speed on the two motors. My pid parameters are calculated following the guidance from this webpage: http://www.inpharmix.com/jps/PID_Controller_For_Lego_Mindstorms_Robots.html
