### ISSUE TITLE
Using ports 1-4 for motors

### ISSUE THREAD

**Issue by DigitalRookie4** [ev3dev/ev3dev-lang-python#671]
I was just wondering I am able to use the ports 1-4 on my ev3 robot to run motors because I have 4 large motors and 2 medium motors. I want to try to use all these motors in one go (meaning I want to use **ALL** motors on the robot at once). I have tried doing this before but what happened is that to program stopped working and mentioned about a signal issue. Does anybody know why this reason might be because

**Comment by WasabiFan** [comment]
Ports 1-4 are for sensors and use a different connector and signals; you can't run motors on them.

**Comment by DigitalRookie4** [comment]
@WasabiFan  Are there any adaptors that I can use that can use two motors on one port

**Comment by WasabiFan** [comment]
Yes. There's a list here: http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-stretch/muxs.html#supported-multiplexers

Beware that sometimes multiplexers add complexity, so you have to be ready to deal with that.

**Comment by DigitalRookie4** [comment]
@WasabiFan  I am using micropython to program my robot do you have any suggestions on how I could program this. What my idea is doing:
`motor_one = Motor(port.A), 
motor_two = Motor(port.A),
motor_one.run_target(100, 360)
,motor_two.run_target(100, 360)`
I also want to know are they safe to use for the robot (for example none of the hardware breaks when using the adapter wires). 
And also do you know where I can try to buy these. (amazon would be the best for me personally).
One more thing as well are they guaranteed to work with both large motors and medium motors

**Comment by WasabiFan** [comment]
To use motors on a multiplexer you need to replace the typical port constants with strings given from the docs I linked to.

It sounds like you are using the pybricks library, which is not associated with this repo. I can't provide support for using the pybricks library here.

> I also want to know are they safe to use for the robot (for example none of the hardware breaks when using the adapter wires).

It's designed not to break, but like any other product, it could.

> And also do you know where I can try to buy these. (amazon would be the best for me personally).

You can find them on their manufacturers' websites. You might be able to look it up and find them on Amazon.

> One more thing as well are they guaranteed to work with both large motors and medium motors

With some configuration, yes; but it doesn't sound like you are ready to figure out how to do that so I'd suggest sticking with the built-in ports and no multiplexer.
