### ISSUE TITLE
Alternatives for pygame.joystick for controlling ev3dev robot

### ISSUE THREAD

**Issue by DigitalRookie4** [ev3dev/ev3dev-lang-python#672]
I have tried using pygame.joystick to control my robot. however may people have suggested to me that it might not work so I am asking anyone out there who knows any joystick modules. Is there a joystick module that can successfully work for a Lego ev3 robot.

**Comment by dwalton76** [comment]
You can do this:
https://youtu.be/x5VauXr7W4A

See here for an example:
https://github.com/ev3dev/ev3dev-lang-python-demo/blob/stretch/robots/EV3D4/EV3D4WebControl.py
