### ISSUE TITLE
MoveTank.follow_line ?

### ISSUE THREAD

**Issue by JohnHZheng** [ev3dev/ev3dev-lang-python#675]
This is related to [this issue](https://github.com/ev3dev/ev3dev-lang-python/issues/670). We cannot find the right kp, kd, ki to make the follow_line work. We tried the find kpkikd in the link and spent a lot of hours by tweaking the parameters. It never worked out for us. We get values like kp=4.7, ki=0.1, and kd=3. But it will always ends with lost the line exception no matter what tweaking we can make. We did print the PDF and use an oval for our testing field. Any suggestions?

**Comment by WasabiFan** [comment]
I haven't done this specifically with our new line follow function, but my suggestion would be to manually tune it like this:
- Start with all parameters 0.
- Choose some P value. Maybe 1.
- Tell it to follow the line and watch what it does.
- If it begins to "oscillate" around the line (goes left, then right, over and over, or turns so fast it loses the line) then decrease P. If it drives off in the wrong direction without trying to adjust much, increase P. Repeat until it roughly follows the line.
- Once it's roughly in the right spot, you have two options:
  - If it's not adjusting to curves aggressively enough, add some more P and introduce some D. D counteracts oscillation, so add more D if it still swerves back and forth, and decrease it if the robot doesn't correct fast enough. The idea is that you can keep increasing both P and D together as a pair until the system is too unstable to control.
  - If it's often slightly off from the line, add a small amount of I. I can lead to hard-to-tune issues, so only do this if it really isn't sticking close enough to the line. Adding I can sometimes mean you have to decrease some P.

This is all about A) understanding the scale of values (e.g., is a change of 1 "P unit" a huge amount or a very small amount?) so you can adjust appropriately and B) making sure to not over-complicate it with, say, I when you don't need I.

**Comment by dwalton76** [comment]
How fast is your robot moving?  Maybe make it go super slow?

**Comment by JohnHZheng** [comment]
Appreciate your help here. We tried again with different values (lower speed such as 3%, P, I, D with your suggestions). Unfortunately, the result is not quite satisfactory. It works in one run and failed on the other. So we finally decide to write our own simple line following and it works quite stable. Maybe PID next season. Thanks
