### ISSUE TITLE
RPyC update docs and make it easier to use

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev-lang-python#677]
The page https://ev3dev-lang.readthedocs.io/projects/python-ev3dev/en/ev3dev-stretch/rpyc.html?highlight=rpyc#working-with-ev3dev-remotely-using-rpyc says to install rpyc on the EV3, but it is already installed by default.

**Comment by WasabiFan** [comment]
Is the correct solution to delete step 1?

**Comment by dlech** [comment]
Only half of it. It still needs to be installed on the users computer.

**Comment by dwalton76** [comment]
Per the end of the #385 discussion we are going to update our RPyC docs and see what we can do to make it really easy to use.
