### ISSUE TITLE
Did you know you can win some substantial prizes using ev3dev-lang-python?

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev-lang-python#678]
Amazon and LEGO have just announced a contest that connects Amazon Alexa to LEGO MINDSTORMS EV3... and it uses ev3dev-lang-python!

There are a large number of substantial prizes for the contest, so be sure to check it out!

https://www.hackster.io/contests/alexa-lego-voice-challenge

**Comment by dwalton76** [comment]
wow!!

**Comment by WasabiFan** [comment]
Super cool! If anyone runs into issues that are blocking their work on this, mention that and I'll see if I can prioritize it.

**Comment by naynt** [comment]
interesting!

**Comment by dlech** [comment]
Winners were announced today: https://www.hackster.io/contests/alexa-lego-voice-challenge
