### ISSUE TITLE
Problem Importing Button Using Micropython

### ISSUE THREAD

**Issue by ghost** [ev3dev/ev3dev-lang-python#681]
- **ev3dev version: 18.7.0
- **ev3dev-lang-python version: ev3dev-stretch-ev3-generic-2019-03-03.img 

---------------------------------------------
I get this error when running programs trying to import button and console.
```
WARN:ev3dev2.button:Import warning: Failed to import "evdev". Button will be unusable!
```

These are my import statements and bit of test code, and I think they are correct..
```
#!/usr/bin/env micropython
from ev3dev2.motor import LargeMotor, MoveSteering, MoveTank, OUTPUT_A, OUTPUT_D
from ev3dev2.sensor.lego import GyroSensor, ColorSensor, LightSensor
from ev3dev2.sensor import INPUT_1, INPUT_2, INPUT_3, INPUT_4
from ev3dev2.button import Button

import sys
from time import sleep
from math import pi, cos, sin, e

btn = Button()
print('Press Left Button', file=sys.stderr)
btn.wait_for_bump('left')
```

This is the error message for the code above.
```
Started.
----------
WARN:ev3dev2.button:Import warning: Failed to import "evdev". Button will be unusable!
Traceback (most recent call last):
  File "/home/robot/District2019/playroom.py", line 14, in <module>
  File "ev3dev2/button.py", line 234, in __init__
AttributeError: type object 'ButtonBase' has no attribute '__init__'
----------
Exited with error code 1.
```

Also, when I try to import console
`from ev3dev2.console import Console`

I get this error:
`ImportError: no module named 'ev3dev2.console'`

**Comment by WasabiFan** [comment]
Please upgrade the library:

```
sudo apt-get update
sudo apt-get install --only-upgrade python3-ev3dev2 micropython-ev3dev2
```

**Comment by ghost** [comment]
Thanks for the answer.

I am working on a Mac and it seems apt-get doesn't work. I found some work
arounds, but I am really over my head.

Edit - Durr...I read the documentation and ssh'd into the robot. sudo works just fine.

I think the problem is that have an older version installed. Someone else
had a similar issue now that I searched for the right issue.

Edit - Thank you for being kind to me in my boomer-moment.

**Comment by Technonati** [comment]
Hmm - what is the latest version:
2.0.0~beta3 or beta5?

Here's what popped up on in the terminal after running the commands.

robot@ev3dev:~$ sudo apt-get update
Err:1 http://httpredir.debian.org/debian stretch InRelease                     
  Could not resolve 'httpredir.debian.org'
Err:2 http://security.debian.org stretch/updates InRelease                     
  Could not resolve 'security.debian.org'
Err:3 http://archive.ev3dev.org/debian stretch InRelease                 
  Could not resolve 'archive.ev3dev.org'
Reading package lists... Done        
W: Failed to fetch http://httpredir.debian.org/debian/dists/stretch/InRelease  Could not resolve 'httpredir.debian.org'
W: Failed to fetch http://security.debian.org/dists/stretch/updates/InRelease  Could not resolve 'security.debian.org'
W: Failed to fetch http://archive.ev3dev.org/debian/dists/stretch/InRelease  Could not resolve 'archive.ev3dev.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
robot@ev3dev:~$ sudo apt-get install --only-upgrade python3-ev3dev2 micropython-ev3dev2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
micropython-ev3dev2 is already the newest version (2.0.0~beta3).
python3-ev3dev2 is already the newest version (2.0.0~beta3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by WasabiFan** [comment]
Did you run the commands on the robot via SSH? If so, it should have upgraded the library. Is your issue resolved?

**Comment by ghost** [comment]
I have to use Bluetooth to connect to the internet, and it isn't working.
It connects, then disconnects.

GDBus.Error:org.bluez.Error.Failed: Protocol not available.

In all fairness, by Bluetooth antenna was cut by my Mac's previous owner,
for some ungodly reason, but I can connect to device if it is laying on my
keyboard, but the connection is lost.

I'll go on a PC laptop I have for my FLL team and load up everything and
try that one.

I'll update tomorrow.

Thanks for your help.

>

**Comment by dlech** [comment]
You can't use USB to connect to the Internet? Upgrading packages via Bluetooth usually fails no matter how good the connection is.

**Comment by ghost** [comment]
As far as I can tell, when I connect the brick via the miniUSB port, I can't network because the brick IP address was self-generated, so my computer is telling me when I go to the network options.

I may be missing something in my understanding, I hope....

**Comment by ghost** [comment]
OK I was missing something. I was tethering my brick via USB.

Let me try to follow the instructions...might be a good idea, no?

**Comment by ghost** [comment]
Something isn't working right. 

The brick isn't changing from Connected to Online.

I am backing out and going to the beginning...tomorrow morning in a few hours.

I'll report how it goes.

Thanks for the help. I really appreciate it.

**Comment by ghost** [comment]
1. I don't see the "CDC Composite Gadget" as stated in the tutorial page on connecting via USB in System Preferences>Netwworks. After connecting the brick, EV3+ev3dev shows up in Networking (using Mojave 10.14.6) with a self assigned IP. Otherwise, everything looks like step 1.

2. Assuming that is what it is supposed to be, in Sharing. I share my connection from Wi-Fi with the EV3+ev3dev and have internet sharing, screen sharing and internet connection checked for Computers using EV3+ev3dev, more or less as the tutorial shows.

3. On the brick in Wired Connection - it doesn't change from Connected to Online - it shows connected.

4. I ssh in to the brick, run fortune and show I am connected.

5. I run sudo apt-get update.

...and it is working - updating to 2.0.0-beta5

I know where I made the mistake now (well two).

1. Doing it at 2 am.
2. Not setting "Share your connection from: "WiFi" on the Sharing screen.

Durr.

I'll try the brick out in a few hours to see if that takes care of the button problem and report back.

**Comment by ghost** [comment]
Works like a charm!

Thank you all so very much.

May I repay your help by writing up an update to the "Connect to the USB Page" and making a "Update your Brick" page for the tutorials on ev3dev.org?

I'll be having my FLL team do it as part of a guide to quickly getting set up to use EV3DEV for FLL, which will be directed at kids who haven't programmed in a real language, but will be moving soon to FTC (and for adults who don't know anything about shells, programming, IDEs or anything).

**Comment by dlech** [comment]
Ideally, I would like to migrate that sort documentation to http://docs.ev3dev.org/en/ev3dev-stretch/ so that if/when there is an ev3dev-buster, we can have multiple versions of the docs at the same time.

**Comment by dlech** [comment]
> making a "Update your Brick" page for the tutorials on ev3dev.org?

This page already exists: https://www.ev3dev.org/docs/tutorials/upgrading-ev3dev/

**Comment by ghost** [comment]
Thanks again for the help.

Ev3Dev2 works better than the Lego version, wrto motor control. Faster, more even, better consistency.
