### ISSUE TITLE
Exporting EV3 data to csv file format using ev3.dev2 python via Visual Studio.

### ISSUE THREAD

**Issue by naynt** [ev3dev/ev3dev-lang-python#683]
**Visual Studio 1.38.1**
** ev3dev2 stretch version 2019.03.03**
** EV3 Brickman 0.10.0 **
** Windows 10 **

Hello, I am interested in collecting data obtained from my EV3/NXT sensors and transferring it to csv format using ev3dev2 micro-python. I am using a HI-Technic NXT Barometric sensor and wish to collect data on humidity over time.
I am somewhat of a beginner with python and I was wondering what would be the best way to go about this. I wrote the following script:

My question is, am I on the right track with this script?

```python
#!/usr/bin/env python3
from ev3.dev2.sensor import Sensor, INPUT_1
from ev3dev2.port import LegoPort

a = LegoPort(INPUT1)
a.set_device = 'ht-nxt-barometric'
a.mode = 'PRESS'
sleep(1)
baro = Sensor()
baro.value

print('value = ', end=' ', file = stderr)

with open('w', newline='') as output file:
      output_list = csv.writer(output_file, delimiter ='\t')
      data_output =[]
      data_output.append[baro.value]
      for b in data_out_put:
            output_list.writerow(b)
```

**Comment by WasabiFan** [comment]
Yeah, that definetely looks like the right track! Does it do the right thing?

**Comment by naynt** [comment]
Unfortunately, I have been having a hard time obtaining the data values from the NXT Barometer. So I wrote a script to get the sensor to display the temperature value every 2 seconds for a total of ten times on Visual Studio Code output terminal. The script is:

```python
#!/usr/bin/env python3 

from ev3dev2.sensor.lego import Sensor
import sys
from ev3dev2.port import LegoPort
from sys import stderr
from time import sleep
from ev3dev2.sensor import INPUT_1
from os import system

c = LegoPort(INPUT_1)
c.set_device = 'ht-nxt-barometric'
c.mode = 'TEMP' 
sleep(1)
temp = Sensor()
x = temp.value

count=0
while True:
    count = count + 1
    print(x, end=' ',file = stderr)
    sleep(2)

    if count == 10:
        break

print(' ') # start a new line
```

The following is the error I get:

```
Traceback (most recent call last):
  File "/home/robot/Lone Script/NXT Barometer and Temp.py", line 20, in <module>
    c.set_device = 'ht-nxt-barometric'
  File "/usr/lib/python3/dist-packages/ev3dev2/port.py", line 140, in set_device
    self._set_device = self.set_attr_string(self._set_device, 'set_device', value)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 321, in set_attr_string
    return self._set_attribute(attribute, name, value)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 264, in _set_attribute
    self._raise_friendly_access_error(ex, name)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 287, in _raise_friendly_access_error
    raise driver_error
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 261, in _set_attribute
    attribute.write(value)
OSError: [Errno 95] Operation not supported
----------
Exited with error code 1.
```

Do you have any idea what I am doing wrong? This is would be extremely appreciated!

**Comment by dlech** [comment]
This sensor should be automatically detected, so it should not be necessary to use `set_device`.

**Comment by naynt** [comment]
Thanks for that. So I altered that part of the script, I got no error, however I still did not get any temperature values.

```python
#!/usr/bin/env python3 

from ev3dev2.sensor.lego import Sensor
import sys
from ev3dev2.port import LegoPort
from sys import stderr
from time import sleep
from ev3dev2.sensor import INPUT_1
from os import system


temp = Sensor(INPUT_1)
temp.mode = 'TEMP'
x = temp.value

count=0
while True:
    count = count + 1
    print(x, end=' ',file = stderr)
    sleep(2)

    if count == 10:
        break

print(' ') # start a new line
```

**output:**

```
<bound method Sensor.value of Sensor(ev3-ports:in1)> <bound method Sensor.value of Sensor(ev3-ports:in1)> <bound method Sensor.value of Sensor(ev3-ports:in1)> <bound method Sensor.value of Sensor(ev3-ports:in1)> <bound method Sensor.value of Sensor(ev3-ports:in1)> <bound method Sensor.value of Sensor(ev3-ports:in1)> <bound method Sensor.value of Sensor(ev3-ports:in1)> <bound method Sensor.value of Sensor(ev3-ports:in1)> <bound method Sensor.value of Sensor(ev3-ports:in1)> <bound method Sensor.value of Sensor(ev3-ports:in1)> ----------
Completed successfully.
```

**Comment by naynt** [comment]
I tried it out for my Lego temperature sensor, but I also get ----------, instead of temperature values. So there must be something wrong with my script. Do I need to modify the script further to get the values to display on the Visual Studio Code output?

**Comment by bpmerkel** [comment]
Is value a method??? And needs to called with parents?? Value()

**Comment by dlech** [comment]
Yup. e.g. `print(x(0), end=' ',file = stderr)`

**Comment by naynt** [comment]
print(x(0), end=' ',file = stderr) comes backs with a error showing:

TypeError:'Sensor' object is not callable.

**Comment by naynt** [comment]
Yes that worked. Thank you  very much guys, you are awesome!

**Comment by WasabiFan** [comment]
Glad this was resolved! Can this issue be closed now?

**Comment by naynt** [comment]
Yes it can, thank you!
________________________________
