### ISSUE TITLE
Is it possible to query connected devices?

### ISSUE THREAD

**Issue by gantzm** [ev3dev/ev3dev-lang-python#684]
- **ev3dev version:** 4.14.117-ev3dev-2.3.4-ev3
- **ev3dev-lang-python version:** 
```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                      Version                   Architecture              Description
+++-=========================================-=========================-=========================-========================================================================================
ii  micropython-ev3dev2                       2.0.0~beta5               all                       Python language bindings for ev3dev for MicroPython
ii  python3-ev3dev                            1.2.0                     all                       Python language bindings for ev3dev
ii  python3-ev3dev2                           2.0.0~beta5               all                       Python language bindings for ev3dev

```

Is it possible to query if a specific device is on a specific port and responding?

I'd like to be able to determine if there is a functioning LargeMotor on OUTPUT_B for example.

Or I'd like to determine if there is a functioning GyroSensor on INPUT_1.

For a sensor I could probably just query for its value and if I get an exception then it's not working.  But does the same work for a motor?  

I'm trying to avoid doing something to the device, like moving the motor, if there is a facility for just querying what's on the bus.

**Comment by WasabiFan** [comment]
If you want to try a particular device, I'd suggest just instantiating that device and catching the exception if it's thrown.

Another option is this function: https://ev3dev-lang.readthedocs.io/projects/python-ev3dev/en/ev3dev-stretch/spec.html#ev3dev2.list_devices
