### ISSUE TITLE
PyPi release failing on CI server

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev-lang-python#693]
https://travis-ci.org/ev3dev/ev3dev-lang-python/jobs/616502703#L452

It's getting a bad version number and as a result failing to publish. Unclear why; I'll try to take a look soon. The Debian package should be good-to-go though.

**Comment by ddemidov** [comment]
When I do `git describe` locally, I get `ev3dev-stretch/2.0.0` instead of `2.0.0`. This probably means that the `2.0.0` tag is not annotated (created without `-a` switch).

**Comment by WasabiFan** [comment]
I created it as an annotated tag (`-a`) when I originally tagged it; the message is visible on GitHub:

![image](https://user-images.githubusercontent.com/3310349/69515453-80e48580-0f03-11ea-9d62-ccc58511c0af.png)

I think this is because I created the `2.0.0` tag before running the release script (which in turn uses `gbp` to create the `stretch/2.0.0` debian release tag). I did it in this order because I realized that doing it in the other order would cause the `version.py` file in the published package to include the old version.

I should be able to modify `git_version.py` to filter out bad tags.

**Comment by ddemidov** [comment]
> I think this is because I created the 2.0.0 tag before running the release script (which in turn uses gbp to create the stretch/2.0.0 debian release tag).

Yes, that should be the case:
```
git tag --sort taggerdate | tail -n 3
2.0.0beta5
2.0.0
ev3dev-stretch/2.0.0
```

**Comment by WasabiFan** [comment]
🎉 Fixed now: https://pypi.org/project/python-ev3dev2/#history
