### ISSUE TITLE
What's the process for getting a new Artifactory release with updated changes?

### ISSUE THREAD

**Issue by nshenoy** [ev3dev/ev3dev-lang-python#706]
I was curious about what the process was for getting an updated release on http://oss.jfrog.org/list/oss-snapshot-local/org/ev3dev/brickstrap/ ? I'd like to grab an image with the latest changes (including my new gyro changes :) ) . Is there a monthly cadence, or are these images created on demand?

**Comment by dlech** [comment]
It is just whenever we have time and when there is a good reason to. First, a new release of the ev3dev-lang-python debian package has to be done, then it will be automatically picked up in the next SD card image snapshot.

**Comment by WasabiFan** [comment]
There have been a fair amount of changes to the library over the past few weeks so it would be good for me to publish a release soon. After that, the full image releases are done separately, but it's easy to install a new release on an older image via `apt`.

**Comment by WasabiFan** [comment]
All the changes to this library have been released in the `2.1.0` package release, which is now available via `apt` and `pip`. It will be included in the next ev3dev image release., although I can't say when that will be.

**Comment by dlech** [comment]
Soon. I'll probably make another release candidate tomorrow.

https://www.ev3dev.org/news/2020/03/11/ev3dev-stretch-r3-release-candidate/
