### ISSUE TITLE
Invert gyro angle in code for MoveTank.follow_gyro_angle?

### ISSUE THREAD

**Issue by WesleyJ-128** [ev3dev/ev3dev-lang-python#736]
- **ev3dev version:  4.14.117-ev3dev-2.3.4-ev3
- **ev3dev-lang-python version:
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  micropython-ev 2.0.0~beta5  all          Python language bindings for ev3d
ii  python3-ev3dev 1.2.0        all          Python language bindings for ev3d
ii  python3-ev3dev 2.0.0~beta5  all          Python language bindings for ev3d

In my robot, the gyro sensor is mounted such that the gyro is inverted relative to the motors.  This means that when the robot turns clockwise, the angle decreases instead of increasing.  Therefore, when I run 
`tank = MoveTank(OUTPUT_B, OUTPUT_C)`
`tank.gyro = GyroSensor(INPUT_2)`
`tank.follow_gyro_angle(kp, ki, kd, Speed, Heading, 0.01, follow_for_forever)`
with `kp`, `ki`, `kd`, `Speed`, and `Heading` equaling 1, 0, 0, 25, and 0, respectively, the robot tries to correct in the wrong direction, and the robot spirals faster and faster until the program throws the `FollowGyroAngleErrorTooFast` error.  Is there any way for the gyro angle to be inverted in code?  I have tried `tank.gyro.circle_angle()`, but this causes the program to throw the same error as before, before the robot moves at all.

**Comment by WasabiFan** [comment]
Interesting! There's no way to explicitly rotate it as far as I know, but you I believe can make it behave like that. Can you negate your P, I and D coefficients so that `kp=-1` and `ki=kd=0` and try again?

**Comment by WesleyJ-128** [comment]
I have tried that already, and when I try to run the program, it gives the same error, before it moves at all.

**Comment by WasabiFan** [comment]
@WesleyJ-128 It sounds to me like your `kp` might be too large. Could you change it to `0.1` and try again, with both positive and negative signs just in case?

**Comment by WesleyJ-128** [comment]
This worked! Thank you.
