### ISSUE TITLE
Move Differential

### ISSUE THREAD

**Issue by monsfortis1940** [ev3dev/ev3dev-lang-python#739]
**Question**

I am trying to use "Move Differential"for my Robot with wheels (diameter 81.6 mm and wheel _distance 120 mm )

Not clear for me how to implement these wheels in the env python3 code:

from ev3dev2.wheel import ??????
STUD_MM 8
mdiif = MoveDifferential(OUTPUT_B, OUTPUT_C,    ???????,   15xSTUD_MM )

kind regards monsfortis1940

**Comment by dwalton76** [comment]
You could create your own Wheel class...something like
```
from ev3dev2.wheel import Wheel

class MyWheel(Wheel):
    def __init__(self):
        Wheel.__init__(self, 81.6, 30)

STUD_MM 8
mdiif = MoveDifferential(OUTPUT_B, OUTPUT_C, MyWheel, 15xSTUD_MM )
```
The `30` above is the width of your tire...I just made something up

**Comment by monsfortis1940** [comment]
hello

Thank you very much for your prompt reply
Problem has been solved

kind regards monsfortis1940

Op di 28 apr. 2020 om 16:55 schreef Daniel Walton <notifications@github.com
