### ISSUE TITLE
EV3dev Python3: tacho_counts

### ISSUE THREAD

**Issue by monsfortis1940** [ev3dev/ev3dev-lang-python#742]
**Question**

How do you ...?

I have a question about tacho counts.

Is it possible to run the tacho motors based upon the tacho counts.
for instance:

count_left = tacho_count_left
count_right = tacho_count_right
error = count_left - count_right
tank_pair.on (left_speed = speed + error,  right_speed = speed - error) 

thank you in advance
mario

**Screenshots**
If applicable, add screenshots to help explain your question.

**Desktop (please complete the following information):**
 - OS and version: [e.g. Window 10 1809, macOS 10.14]
 - Connection Type: [e.g. USB, Bluetooth, Wi-Fi]
 - Software: [e.g. Visual Studio Code, PuTTY]

**Robot (please complete the following information):**
 - Device: [e.g. EV3, BrickPi3]
 - Versions: [see below - SD card image version, Linux kernel version, etc.]

```
Please paste the system info from the ev3dev VS Code extension or the output of `ev3dev-sysinfo -m` here!
```

**Comment by WasabiFan** [comment]
If you're asking whether you can provide speed in tacho counts per second, yes you can; you should use `SpeedNativeUnits`. So something like:

```
tank_pair.on (left_speed = SpeedNativeUnits(speed + error), right_speed = SpeedNativeUnits(speed - error))
```

The units are documented here for more info: https://python-ev3dev.readthedocs.io/en/ev3dev-stretch/motors.html#units

**Comment by monsfortis1940** [comment]
Hello WasabiFan,

Thank you for your prompt answer. but it is not exactly what I mean.
What I like to know for both motors ( f.i large_motor_B and large_motor_C) is
the tacho_counts/ time_unit.

With f.i. the following routine I will control the both motors
large _motor_B.on(SpeedRPM(30))
large_motor_C.on(SpeedRPM(30))

How can I be informed about the tacho_counts/time_unit ?

I hope You can help me

Thank you in advance
mario

**Comment by WasabiFan** [comment]
Ah, sorry, I misunderstood. To read the current motor speed you can use the `.speed` attribute of a Motor: https://ev3dev-lang.readthedocs.io/projects/python-ev3dev/en/ev3dev-stretch/motors.html#ev3dev2.motor.Motor.speed

If you are using a pair of motors (e.g. `MoveTank`), you can use `tank_pair.right_motor.speed` (or equivalently for `left_motor`).

**Comment by monsfortis1940** [comment]
hallo Wasabifan

Problem solved. Thank you very much

kind regards 
Mario

**Comment by WasabiFan** [comment]
Glad to hear it!
