### ISSUE TITLE
EV3Dev2 vs PyBricks2 APIs: are they converging or diverging going forward?

### ISSUE THREAD

**Issue by TheVinhLuong102** [ev3dev/ev3dev-lang-python#745]
In my understanding, EV3Dev2 and PyBricks are the 2 most prominent Python libraries today for programming the EV3. I notice that both projects are progressing very ambitiously, with key persons such as @dlech active in both.

As a developer and a teacher (e.g. I'm teaching my son and several other young kids to program in Python using EV3 as the medium), I would like the understand the high-level future directions of these 2 major projects, in order to pick one as the primary API to teach. Do we have a plan to merge them in the future, or will they continue to develop separately to serve different audiences & needs?

(I'm also asking the same question here: https://github.com/pybricks/pybricks-api/issues/22)

**Comment by WasabiFan** [comment]
I'm going to close this and post a response in https://github.com/pybricks/pybricks-api/issues/22, to keep things together in the same place.

**Comment by TheVinhLuong102** [comment]
sure, thanks @WasabiFan!
