### ISSUE TITLE
Error in docs

### ISSUE THREAD

**Issue by jollyroger182** [ev3dev/ev3dev-lang-python#749]
No, this is not about ev3dev itself. It's about [the Leds docs](https://ev3dev-lang.readthedocs.io/projects/python-ev3dev/en/stable/leds.html#ev3dev2.led.Leds.animate_cycle). There is something misspelled in the example: animate_cyle. It's not a big problem but I just can't stand seeing errors anywhere ... Please fix it. Thank you!

**Comment by jollyroger182** [comment]
<img width="640" alt="error" src="https://user-images.githubusercontent.com/22110069/87159983-c4ee9400-c2f4-11ea-9fc4-8fdb00836ff5.png">

**Comment by WasabiFan** [comment]
Fixed in https://github.com/ev3dev/ev3dev-lang-python/commit/5364b40ffd7d208c52b1772f11c5871a43a61511, thanks for the report.
