### ISSUE TITLE
Can't draw anything to the LCD screen.

### ISSUE THREAD

**Issue by mafteialbert** [ev3dev/ev3dev-lang-python#765]
- **ev3dev version:** 4.14.117-ev3dev-2.3.5-ev3
- **ev3dev-lang-python version:**

micropython-ev3dev2               2.1.0
python3-ev3dev                    1.2.0
python3-ev3dev2                   2.1.0

I am trying to draw a simple circle to the screen, yet this doesn't work. If it helps, pressing the buttons prints the regular linux arrow keys keycodes("[[^C") on some type of console.

```
#!/usr/bin/env python3
from ev3dev2.display import Display
from time import sleep
d=Display()
d.circle()

while True: 
    sleep(1)
```

I also tried drawing a line and it didn't work either.

**Comment by WesleyJ-128** [comment]
Just do ``d.update()`` to make the screen draw any pending changes.  ``circle()`` might also want some parameters.
